// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol

go 1.24

replace github.com/open-telemetry/opentelemetry-collector-contrib/processor/ddsketchprocessor => ../processor/ddsketchprocessor
