receivers:
  otlp/in:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  # ...

exporters:
  otlp/out: # https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md
    endpoint: 0.0.0.0:4318
    tls:
      insecure: true
    # if compression is enabled, make sure you have the respective library installed
    compression: none

service:
  pipelines:
    metrics:
      receivers: [otlp/in]
      processors: []
      exporters: [otlp/out]