[global_tags]
  scenario = "OTEL-KLL-bridge"

[agent]
  interval = "1ms"
  flush_interval = "100ms"
  flush_jitter = "0s"
  collection_jitter = "0s"
  round_interval = false
  metric_batch_size = 100000
  metric_buffer_limit = 25000000
  precision = "1us"
  debug = true
  logfile = "./out/telegraf-bench.log"

[[inputs.opentelemetry]]
  service_address = "0.0.0.0:4318"
  metrics_schema = "prometheus-v1"

[[inputs.internal]]
  per_instance = true
  collect_gostats = true

[[inputs.procstat]]
  exe = "telegraf"
  pid_finder = "native"
  interval = "1s"

[[outputs.file]]
  ## Still capture internal_* metrics for analysis.
  files = ["./out/telegraf-bench-internal.lp"]
  data_format = "influx"
  use_batch_format = false
  rotation_interval = "10m"
  rotation_max_size = "100MB"
  rotation_max_archives = 5
  namepass = ["internal_*", "procstat"]
