receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  countmin:
    mode: batch
    metric_name: "countmin_sketch"
    rows: 5
    columns: 2000
    transmit_sketch: true
    group_by: []
    drop_original: false

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [countmin]
      exporters: [prometheus]
  telemetry:
    metrics:
      level: basic
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
    logs:
      level: info
    resource:
      service.name: countminsketchcol-batch
