receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  countmin:
    metric_name: "cms_sketch_output"
    rows: 5
    columns: 1000
    seed: 1
    group_by: ["service.name", "method"]
    drop_original: true  # Do not forward the raw data, only the sketch
    window_interval: 10s # NEW: Aggregate 10s of data into 1 Sketch

  batch:
    send_batch_size: 5000 
    timeout: 1s

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [countmin, batch]
      exporters: [debug]