// Continuous distributed monitoring (CDM) wire contract — the edge↔coordinator
// reverse channel for Discipline B (continuous intra-window monitoring) from
// ASAPCollector docs/continuous-monitoring-tumbling-cost-analysis.md.
//
// This is the SOURCE OF TRUTH for the protocol. A byte-identical copy is
// vendored into the Go edge runtime at
//   ASAPCollector/asap-precompute-go/monitor/monitorpb/monitor.proto
// for `protoc --go_out --go-grpc_out` codegen. Keep the two in sync; the
// message field numbers and the service name are the cross-language contract.
//
// Protocol (Cormode–Muthukrishnan–Yi distributed functional monitoring over a
// tumbling window; one window = one independent monitoring epoch, reset at the
// boundary). Per monitor (agg_id, key) the coordinator runs rounds:
//   1. Δ = τ − global_estimate. If Δ ≤ ε·τ → fire GlobalAlert, epoch done.
//   2. local_slack = Δ/(2k), k = #edges. Broadcast SlackGrant to every edge.
//   3. An edge sends MonitorReport when local_value − round_baseline ≥ local_slack.
//   4. When reported mass crosses ~Δ/2 the coordinator closes the round
//      (PollLocal every edge), sets global_estimate = Σ local_value, round += 1,
//      and goto 1 with shrinking slack.
// Every report/grant carries window_start_ms; messages for a non-current epoch
// are dropped on both sides.
//
// NOTE: avoids the proto3 `optional` keyword so host protoc < 3.15 can compile
// the Go side (same constraint that drives PROTOC=vendored on the Rust side).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: monitor.proto

package monitorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// edge → coordinator: open-stream registration. Sent on connect and at the
// start of every new tumbling epoch (after a window boundary).
type MonitorRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`                         // stable per-edge identity (collector instance id)
	AggId         uint64                 `protobuf:"varint,2,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`                           // content-addressed aggregation id (matches edge + coordinator)
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                                             // CMS point-frequency key x; empty for Sum
	EpochWindowMs uint64                 `protobuf:"varint,4,opt,name=epoch_window_ms,json=epochWindowMs,proto3" json:"epoch_window_ms,omitempty"` // edge's tumbling window size — coordinator alignment guard
	WindowStartMs uint64                 `protobuf:"varint,5,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"` // edge's current epoch start — avoids coordinator clock skew
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorRegister) Reset() {
	*x = MonitorRegister{}
	mi := &file_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorRegister) ProtoMessage() {}

func (x *MonitorRegister) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorRegister.ProtoReflect.Descriptor instead.
func (*MonitorRegister) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *MonitorRegister) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *MonitorRegister) GetAggId() uint64 {
	if x != nil {
		return x.AggId
	}
	return 0
}

func (x *MonitorRegister) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MonitorRegister) GetEpochWindowMs() uint64 {
	if x != nil {
		return x.EpochWindowMs
	}
	return 0
}

func (x *MonitorRegister) GetWindowStartMs() uint64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

// edge → coordinator: the current local additive value for the named monitor,
// emitted when the edge's local increase since round start crossed its slack,
// or in response to a PollLocal at round close.
type MonitorReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	AggId         uint64                 `protobuf:"varint,2,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	WindowStartMs uint64                 `protobuf:"varint,4,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"` // epoch this value belongs to (stale-epoch drop)
	LocalValue    float64                `protobuf:"fixed64,5,opt,name=local_value,json=localValue,proto3" json:"local_value,omitempty"`           // current additive local value at report time
	Round         uint64                 `protobuf:"varint,6,opt,name=round,proto3" json:"round,omitempty"`                                        // round this report answers
	Seq           uint64                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`                                            // per-edge monotonic counter; idempotent-retransmit dedup
	Rate          float64                `protobuf:"fixed64,8,opt,name=rate,proto3" json:"rate,omitempty"`                                         // edge's observed items/window for this agg+key — feeds the coordinator's whole-sketch sampling floor (p_i = 1/(1+eps^2*rate_i))
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorReport) Reset() {
	*x = MonitorReport{}
	mi := &file_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorReport) ProtoMessage() {}

func (x *MonitorReport) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorReport.ProtoReflect.Descriptor instead.
func (*MonitorReport) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorReport) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *MonitorReport) GetAggId() uint64 {
	if x != nil {
		return x.AggId
	}
	return 0
}

func (x *MonitorReport) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MonitorReport) GetWindowStartMs() uint64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *MonitorReport) GetLocalValue() float64 {
	if x != nil {
		return x.LocalValue
	}
	return 0
}

func (x *MonitorReport) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *MonitorReport) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MonitorReport) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// coordinator → edge: this round's per-edge slack budget. The edge reports once
// its local increase since the grant reaches local_slack.
type SlackGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggId         uint64                 `protobuf:"varint,1,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Round         uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	LocalSlack    float64                `protobuf:"fixed64,4,opt,name=local_slack,json=localSlack,proto3" json:"local_slack,omitempty"`
	WindowStartMs uint64                 `protobuf:"varint,5,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	// sample_p is the distributed-NitroSketch update-sampling probability the
	// coordinator allocates this edge via the whole-sketch epsilon-floor
	// (p_i = 1/(1+eps^2*rate_i); see data_plane allocate_p / epsilon_sample_floor).
	// 0 (unset) => no sampling grant (p=1). The edge applies it via WithSampleP on
	// sampling-capable sketch wrappers (CMS/CountSketch/DDSketch) at the next
	// EpochReset; other families ignore it. Orthogonal to local_slack (CPU vs
	// bandwidth). See docs/distributed-nitrosketch-coordinated-sampling.md.
	SampleP       float64 `protobuf:"fixed64,6,opt,name=sample_p,json=sampleP,proto3" json:"sample_p,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlackGrant) Reset() {
	*x = SlackGrant{}
	mi := &file_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlackGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlackGrant) ProtoMessage() {}

func (x *SlackGrant) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlackGrant.ProtoReflect.Descriptor instead.
func (*SlackGrant) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *SlackGrant) GetAggId() uint64 {
	if x != nil {
		return x.AggId
	}
	return 0
}

func (x *SlackGrant) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SlackGrant) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SlackGrant) GetLocalSlack() float64 {
	if x != nil {
		return x.LocalSlack
	}
	return 0
}

func (x *SlackGrant) GetWindowStartMs() uint64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *SlackGrant) GetSampleP() float64 {
	if x != nil {
		return x.SampleP
	}
	return 0
}

// coordinator → edge: demand the current local value now (round close).
type PollLocal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggId         uint64                 `protobuf:"varint,1,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Round         uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	WindowStartMs uint64                 `protobuf:"varint,4,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollLocal) Reset() {
	*x = PollLocal{}
	mi := &file_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollLocal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollLocal) ProtoMessage() {}

func (x *PollLocal) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollLocal.ProtoReflect.Descriptor instead.
func (*PollLocal) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *PollLocal) GetAggId() uint64 {
	if x != nil {
		return x.AggId
	}
	return 0
}

func (x *PollLocal) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PollLocal) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *PollLocal) GetWindowStartMs() uint64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

// coordinator → edge: round closed; edge advances its round baseline.
type RoundClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggId         uint64                 `protobuf:"varint,1,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	WindowStartMs uint64                 `protobuf:"varint,3,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundClose) Reset() {
	*x = RoundClose{}
	mi := &file_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundClose) ProtoMessage() {}

func (x *RoundClose) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundClose.ProtoReflect.Descriptor instead.
func (*RoundClose) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *RoundClose) GetAggId() uint64 {
	if x != nil {
		return x.AggId
	}
	return 0
}

func (x *RoundClose) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *RoundClose) GetWindowStartMs() uint64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

// Out-of-band (NOT carried on the Monitor stream): the coordinator serializes
// this into the control-plane violation/notifier sink when the global aggregate
// crosses τ. Defined here so both sides share the shape for logging/tests.
type GlobalAlert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AggId          uint64                 `protobuf:"varint,1,opt,name=agg_id,json=aggId,proto3" json:"agg_id,omitempty"`
	Key            []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	GlobalEstimate float64                `protobuf:"fixed64,3,opt,name=global_estimate,json=globalEstimate,proto3" json:"global_estimate,omitempty"`
	Tau            float64                `protobuf:"fixed64,4,opt,name=tau,proto3" json:"tau,omitempty"`
	WindowStartMs  uint64                 `protobuf:"varint,5,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GlobalAlert) Reset() {
	*x = GlobalAlert{}
	mi := &file_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalAlert) ProtoMessage() {}

func (x *GlobalAlert) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalAlert.ProtoReflect.Descriptor instead.
func (*GlobalAlert) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *GlobalAlert) GetAggId() uint64 {
	if x != nil {
		return x.AggId
	}
	return 0
}

func (x *GlobalAlert) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GlobalAlert) GetGlobalEstimate() float64 {
	if x != nil {
		return x.GlobalEstimate
	}
	return 0
}

func (x *GlobalAlert) GetTau() float64 {
	if x != nil {
		return x.Tau
	}
	return 0
}

func (x *GlobalAlert) GetWindowStartMs() uint64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

// Upstream envelope (edge → coordinator).
type EdgeToCoord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*EdgeToCoord_Reg
	//	*EdgeToCoord_Report
	Msg           isEdgeToCoord_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeToCoord) Reset() {
	*x = EdgeToCoord{}
	mi := &file_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeToCoord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeToCoord) ProtoMessage() {}

func (x *EdgeToCoord) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeToCoord.ProtoReflect.Descriptor instead.
func (*EdgeToCoord) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *EdgeToCoord) GetMsg() isEdgeToCoord_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *EdgeToCoord) GetReg() *MonitorRegister {
	if x != nil {
		if x, ok := x.Msg.(*EdgeToCoord_Reg); ok {
			return x.Reg
		}
	}
	return nil
}

func (x *EdgeToCoord) GetReport() *MonitorReport {
	if x != nil {
		if x, ok := x.Msg.(*EdgeToCoord_Report); ok {
			return x.Report
		}
	}
	return nil
}

type isEdgeToCoord_Msg interface {
	isEdgeToCoord_Msg()
}

type EdgeToCoord_Reg struct {
	Reg *MonitorRegister `protobuf:"bytes,1,opt,name=reg,proto3,oneof"`
}

type EdgeToCoord_Report struct {
	Report *MonitorReport `protobuf:"bytes,2,opt,name=report,proto3,oneof"`
}

func (*EdgeToCoord_Reg) isEdgeToCoord_Msg() {}

func (*EdgeToCoord_Report) isEdgeToCoord_Msg() {}

// Downstream envelope (coordinator → edge).
type CoordToEdge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CoordToEdge_Grant
	//	*CoordToEdge_Poll
	//	*CoordToEdge_Close
	Msg           isCoordToEdge_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordToEdge) Reset() {
	*x = CoordToEdge{}
	mi := &file_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordToEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordToEdge) ProtoMessage() {}

func (x *CoordToEdge) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordToEdge.ProtoReflect.Descriptor instead.
func (*CoordToEdge) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *CoordToEdge) GetMsg() isCoordToEdge_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CoordToEdge) GetGrant() *SlackGrant {
	if x != nil {
		if x, ok := x.Msg.(*CoordToEdge_Grant); ok {
			return x.Grant
		}
	}
	return nil
}

func (x *CoordToEdge) GetPoll() *PollLocal {
	if x != nil {
		if x, ok := x.Msg.(*CoordToEdge_Poll); ok {
			return x.Poll
		}
	}
	return nil
}

func (x *CoordToEdge) GetClose() *RoundClose {
	if x != nil {
		if x, ok := x.Msg.(*CoordToEdge_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isCoordToEdge_Msg interface {
	isCoordToEdge_Msg()
}

type CoordToEdge_Grant struct {
	Grant *SlackGrant `protobuf:"bytes,1,opt,name=grant,proto3,oneof"`
}

type CoordToEdge_Poll struct {
	Poll *PollLocal `protobuf:"bytes,2,opt,name=poll,proto3,oneof"`
}

type CoordToEdge_Close struct {
	Close *RoundClose `protobuf:"bytes,3,opt,name=close,proto3,oneof"`
}

func (*CoordToEdge_Grant) isCoordToEdge_Msg() {}

func (*CoordToEdge_Poll) isCoordToEdge_Msg() {}

func (*CoordToEdge_Close) isCoordToEdge_Msg() {}

var File_monitor_proto protoreflect.FileDescriptor

const file_monitor_proto_rawDesc = "" +
	"\n" +
	"\rmonitor.proto\x12\x0fasap.monitor.v1\"\xa3\x01\n" +
	"\x0fMonitorRegister\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x15\n" +
	"\x06agg_id\x18\x02 \x01(\x04R\x05aggId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12&\n" +
	"\x0fepoch_window_ms\x18\x04 \x01(\x04R\repochWindowMs\x12&\n" +
	"\x0fwindow_start_ms\x18\x05 \x01(\x04R\rwindowStartMs\"\xd6\x01\n" +
	"\rMonitorReport\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x15\n" +
	"\x06agg_id\x18\x02 \x01(\x04R\x05aggId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12&\n" +
	"\x0fwindow_start_ms\x18\x04 \x01(\x04R\rwindowStartMs\x12\x1f\n" +
	"\vlocal_value\x18\x05 \x01(\x01R\n" +
	"localValue\x12\x14\n" +
	"\x05round\x18\x06 \x01(\x04R\x05round\x12\x10\n" +
	"\x03seq\x18\a \x01(\x04R\x03seq\x12\x12\n" +
	"\x04rate\x18\b \x01(\x01R\x04rate\"\xaf\x01\n" +
	"\n" +
	"SlackGrant\x12\x15\n" +
	"\x06agg_id\x18\x01 \x01(\x04R\x05aggId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\x12\x1f\n" +
	"\vlocal_slack\x18\x04 \x01(\x01R\n" +
	"localSlack\x12&\n" +
	"\x0fwindow_start_ms\x18\x05 \x01(\x04R\rwindowStartMs\x12\x19\n" +
	"\bsample_p\x18\x06 \x01(\x01R\asampleP\"r\n" +
	"\tPollLocal\x12\x15\n" +
	"\x06agg_id\x18\x01 \x01(\x04R\x05aggId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\x12&\n" +
	"\x0fwindow_start_ms\x18\x04 \x01(\x04R\rwindowStartMs\"a\n" +
	"\n" +
	"RoundClose\x12\x15\n" +
	"\x06agg_id\x18\x01 \x01(\x04R\x05aggId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12&\n" +
	"\x0fwindow_start_ms\x18\x03 \x01(\x04R\rwindowStartMs\"\x99\x01\n" +
	"\vGlobalAlert\x12\x15\n" +
	"\x06agg_id\x18\x01 \x01(\x04R\x05aggId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12'\n" +
	"\x0fglobal_estimate\x18\x03 \x01(\x01R\x0eglobalEstimate\x12\x10\n" +
	"\x03tau\x18\x04 \x01(\x01R\x03tau\x12&\n" +
	"\x0fwindow_start_ms\x18\x05 \x01(\x04R\rwindowStartMs\"\x84\x01\n" +
	"\vEdgeToCoord\x124\n" +
	"\x03reg\x18\x01 \x01(\v2 .asap.monitor.v1.MonitorRegisterH\x00R\x03reg\x128\n" +
	"\x06report\x18\x02 \x01(\v2\x1e.asap.monitor.v1.MonitorReportH\x00R\x06reportB\x05\n" +
	"\x03msg\"\xb0\x01\n" +
	"\vCoordToEdge\x123\n" +
	"\x05grant\x18\x01 \x01(\v2\x1b.asap.monitor.v1.SlackGrantH\x00R\x05grant\x120\n" +
	"\x04poll\x18\x02 \x01(\v2\x1a.asap.monitor.v1.PollLocalH\x00R\x04poll\x123\n" +
	"\x05close\x18\x03 \x01(\v2\x1b.asap.monitor.v1.RoundCloseH\x00R\x05closeB\x05\n" +
	"\x03msg2[\n" +
	"\x0eMonitorService\x12I\n" +
	"\aMonitor\x12\x1c.asap.monitor.v1.EdgeToCoord\x1a\x1c.asap.monitor.v1.CoordToEdge(\x010\x01BRZPgithub.com/ProjectASAP/asap-precompute-go/monitor/grpcclient/monitorpb;monitorpbb\x06proto3"

var (
	file_monitor_proto_rawDescOnce sync.Once
	file_monitor_proto_rawDescData []byte
)

func file_monitor_proto_rawDescGZIP() []byte {
	file_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_proto_rawDesc), len(file_monitor_proto_rawDesc)))
	})
	return file_monitor_proto_rawDescData
}

var file_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_monitor_proto_goTypes = []any{
	(*MonitorRegister)(nil), // 0: asap.monitor.v1.MonitorRegister
	(*MonitorReport)(nil),   // 1: asap.monitor.v1.MonitorReport
	(*SlackGrant)(nil),      // 2: asap.monitor.v1.SlackGrant
	(*PollLocal)(nil),       // 3: asap.monitor.v1.PollLocal
	(*RoundClose)(nil),      // 4: asap.monitor.v1.RoundClose
	(*GlobalAlert)(nil),     // 5: asap.monitor.v1.GlobalAlert
	(*EdgeToCoord)(nil),     // 6: asap.monitor.v1.EdgeToCoord
	(*CoordToEdge)(nil),     // 7: asap.monitor.v1.CoordToEdge
}
var file_monitor_proto_depIdxs = []int32{
	0, // 0: asap.monitor.v1.EdgeToCoord.reg:type_name -> asap.monitor.v1.MonitorRegister
	1, // 1: asap.monitor.v1.EdgeToCoord.report:type_name -> asap.monitor.v1.MonitorReport
	2, // 2: asap.monitor.v1.CoordToEdge.grant:type_name -> asap.monitor.v1.SlackGrant
	3, // 3: asap.monitor.v1.CoordToEdge.poll:type_name -> asap.monitor.v1.PollLocal
	4, // 4: asap.monitor.v1.CoordToEdge.close:type_name -> asap.monitor.v1.RoundClose
	6, // 5: asap.monitor.v1.MonitorService.Monitor:input_type -> asap.monitor.v1.EdgeToCoord
	7, // 6: asap.monitor.v1.MonitorService.Monitor:output_type -> asap.monitor.v1.CoordToEdge
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_monitor_proto_init() }
func file_monitor_proto_init() {
	if File_monitor_proto != nil {
		return
	}
	file_monitor_proto_msgTypes[6].OneofWrappers = []any{
		(*EdgeToCoord_Reg)(nil),
		(*EdgeToCoord_Report)(nil),
	}
	file_monitor_proto_msgTypes[7].OneofWrappers = []any{
		(*CoordToEdge_Grant)(nil),
		(*CoordToEdge_Poll)(nil),
		(*CoordToEdge_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_proto_rawDesc), len(file_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_proto_depIdxs,
		MessageInfos:      file_monitor_proto_msgTypes,
	}.Build()
	File_monitor_proto = out.File
	file_monitor_proto_goTypes = nil
	file_monitor_proto_depIdxs = nil
}
