// Continuous distributed monitoring (CDM) wire contract — the edge↔coordinator
// reverse channel for Discipline B (continuous intra-window monitoring) from
// ASAPCollector docs/continuous-monitoring-tumbling-cost-analysis.md.
//
// This is the SOURCE OF TRUTH for the protocol. A byte-identical copy is
// vendored into the Go edge runtime at
//   ASAPCollector/asap-precompute-go/monitor/monitorpb/monitor.proto
// for `protoc --go_out --go-grpc_out` codegen. Keep the two in sync; the
// message field numbers and the service name are the cross-language contract.
//
// Protocol (Cormode–Muthukrishnan–Yi distributed functional monitoring over a
// tumbling window; one window = one independent monitoring epoch, reset at the
// boundary). Per monitor (agg_id, key) the coordinator runs rounds:
//   1. Δ = τ − global_estimate. If Δ ≤ ε·τ → fire GlobalAlert, epoch done.
//   2. local_slack = Δ/(2k), k = #edges. Broadcast SlackGrant to every edge.
//   3. An edge sends MonitorReport when local_value − round_baseline ≥ local_slack.
//   4. When reported mass crosses ~Δ/2 the coordinator closes the round
//      (PollLocal every edge), sets global_estimate = Σ local_value, round += 1,
//      and goto 1 with shrinking slack.
// Every report/grant carries window_start_ms; messages for a non-current epoch
// are dropped on both sides.
//
// NOTE: avoids the proto3 `optional` keyword so host protoc < 3.15 can compile
// the Go side (same constraint that drives PROTOC=vendored on the Rust side).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: monitor.proto

package monitorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitorService_Monitor_FullMethodName = "/asap.monitor.v1.MonitorService/Monitor"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// One bidirectional stream per edge; the coordinator multiplexes every monitor
// for that edge over the single stream.
type MonitorServiceClient interface {
	Monitor(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EdgeToCoord, CoordToEdge], error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) Monitor(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EdgeToCoord, CoordToEdge], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitorService_ServiceDesc.Streams[0], MonitorService_Monitor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EdgeToCoord, CoordToEdge]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_MonitorClient = grpc.BidiStreamingClient[EdgeToCoord, CoordToEdge]

// MonitorServiceServer is the server API for MonitorService service.
// All implementations must embed UnimplementedMonitorServiceServer
// for forward compatibility.
//
// One bidirectional stream per edge; the coordinator multiplexes every monitor
// for that edge over the single stream.
type MonitorServiceServer interface {
	Monitor(grpc.BidiStreamingServer[EdgeToCoord, CoordToEdge]) error
	mustEmbedUnimplementedMonitorServiceServer()
}

// UnimplementedMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServiceServer struct{}

func (UnimplementedMonitorServiceServer) Monitor(grpc.BidiStreamingServer[EdgeToCoord, CoordToEdge]) error {
	return status.Errorf(codes.Unimplemented, "method Monitor not implemented")
}
func (UnimplementedMonitorServiceServer) mustEmbedUnimplementedMonitorServiceServer() {}
func (UnimplementedMonitorServiceServer) testEmbeddedByValue()                        {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_Monitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorServiceServer).Monitor(&grpc.GenericServerStream[EdgeToCoord, CoordToEdge]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_MonitorServer = grpc.BidiStreamingServer[EdgeToCoord, CoordToEdge]

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asap.monitor.v1.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Monitor",
			Handler:       _MonitorService_Monitor_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "monitor.proto",
}
