receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  ddsketch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [ddsketch]
      exporters: [prometheus]
  telemetry:
    metrics:
      level: basic               # basic/normal/detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888       # same port you wanted before
    logs:
      level: info
    resource:
      service.name: ddsketchcol
