aggregations:
- aggregationId: 1
  aggregationType: DDSketch
  aggregationSubType: ''
  labels:
    grouping: []
    rollup: [series_id]
    aggregated: []
  metric: google_cluster_2019_cpu_rate
  parameters:
    relative_accuracy: 0.01
  windowSize: 30
  windowType: tumbling
  numAggregatesToRetain: 6
  spatialFilter: ''
metrics:
  google_cluster_2019_cpu_rate:
  - series_id
