cleanup_policy:
  name: "circular_buffer"
metrics:
  http_requests_total_latency_ms_quantile:
  - zone
  - rack
  - node
  - pod
  http_requests_total_quantile:
  - zone
  - rack
  - node
  - pod
queries:
- aggregations:
  - aggregation_id: 1
    num_aggregates_to_retain: 6
  query: quantile_over_time(0.5, http_requests_total_latency_ms_quantile[1m])
- aggregations:
  - aggregation_id: 1
    num_aggregates_to_retain: 6
  query: quantile_over_time(0.9, http_requests_total_latency_ms_quantile[1m])
- aggregations:
  - aggregation_id: 1
    num_aggregates_to_retain: 6
  query: quantile_over_time(0.99, http_requests_total_latency_ms_quantile[1m])
- aggregations:
  - aggregation_id: 2
    num_aggregates_to_retain: 6
  query: quantile_over_time(0.99, http_requests_total_quantile[1m])
- aggregations:
  - aggregation_id: 1
    num_aggregates_to_retain: 6
  query: histogram_quantile(0.99, http_requests_total_latency_ms_quantile)
- aggregations:
  - aggregation_id: 1
    num_aggregates_to_retain: 6
  query: histogram_quantile(0.5, http_requests_total_latency_ms_quantile)
- aggregations:
  - aggregation_id: 1
    num_aggregates_to_retain: 6
  query: sum(http_requests_total_latency_ms_quantile)
- aggregations:
  - aggregation_id: 1
    num_aggregates_to_retain: 6
  query: sum_over_time(http_requests_total_latency_ms_quantile[1m])
