dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/serfcol
  name: serfcol
  description: Collector distribution including the Serf XOR compression processor
  output_path: ./cmd/serfcol/dist
  version: 0.141.0-dev

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.141.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.141.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.141.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.141.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.141.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/serfprocessor v0.141.0
    path: ./processor/serfprocessor

replaces:
  - go.opentelemetry.io/collector/pdata => ../../../../opentelemetry-collector/pdata
