dist:
  module: KLL
  name: KLL
  output_path: .

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.142.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.142.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.142.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/kllprocessor v0.0.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.142.0

replaces:
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/kllprocessor => ./processor/kllprocessor
  - go.opentelemetry.io/collector/pdata => ../opentelemetry-collector/pdata
  # - github.com/ProjectASAP/sketchlib-go => ../../sketchlib-go
