receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  KLL:
    k: 256
    write_seen: false
    quantiles: 
      - 0.5
      - 0.99
    drop_original: true
    is_int: false
  
  batch:
    send_batch_size: 5000
    timeout: 200ms

exporters:
  nop:

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
  
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [KLL, batch] 
      exporters: [nop]
