//! Byte-parity contract tests against fixtures produced by the Go
//! `gorillaprocessor` encoder (`opentelemetry-collector-contrib-patch/
//! processor/gorillaprocessor/`).
//!
//! ## How this works
//!
//! The Go side of the cold-engine writes blocks; this crate must read
//! them back bit-for-bit. The reverse must also hold: blocks emitted
//! by `asap-gorilla` must decode cleanly inside the Go side.
//!
//! For the Phase 1 PR we ship two layers of coverage:
//!
//! 1. **Self-round-trip** (always runs): a block produced by
//!    [`asap_gorilla::GorillaEncoder`] decodes back to the same
//!    samples via [`asap_gorilla::GorillaDecoder`]. This is the
//!    encoder/decoder symmetry test.
//!
//! 2. **Cross-language fixture round-trip** (runs only when the
//!    fixture file exists at `tests/golden/single_series.gor`): we
//!    decode the Go-produced bytes and assert they match a known
//!    sample set, then re-encode and assert byte-identical output.
//!
//! The fixture is regenerated by `tests/golden/regen.sh`, which
//! drives the Go encoder against a deterministic input set. The
//! fixture is *not* in this PR — running it requires `go test` inside
//! `opentelemetry-collector-contrib-patch/processor/gorillaprocessor/`
//! and we cannot exercise that during a Rust-only build. Once the
//! fixture lands the cross-language assertions activate automatically.

use std::fs;
use std::path::PathBuf;

use asap_gorilla::{GorillaDecoder, GorillaEncoder};

/// The deterministic input set used for both the Rust self-round-trip
/// and the Go-fixture regeneration. Keep in sync with
/// `tests/golden/regen.sh`.
fn fixture_samples() -> Vec<(u64, f64)> {
    let base = 1_700_000_000_000_000_000u64;
    let mut out = Vec::with_capacity(64);
    for i in 0..64u64 {
        // 1s interval, value = i * 0.5 (covers a few sig-bit-window
        // transitions in the value stream).
        out.push((base + i * 1_000_000_000, (i as f64) * 0.5));
    }
    out
}

fn fixture_metric() -> &'static str {
    "asap_gorilla_fixture_metric"
}

fn fixture_labels() -> Vec<(String, String)> {
    vec![
        ("env".to_string(), "test".to_string()),
        ("instance".to_string(), "i-fixture".to_string()),
        ("region".to_string(), "us-east-1".to_string()),
    ]
}

#[test]
fn self_byte_round_trip() {
    let samples = fixture_samples();
    let mut enc = GorillaEncoder::new(fixture_metric(), fixture_labels());
    for (t, v) in &samples {
        enc.append(*t, *v);
    }
    let bytes = enc.finalize().expect("encode");

    let dec = GorillaDecoder::from_reader(&bytes[..]).expect("decode header");
    let h = dec.header().unwrap();
    assert_eq!(h.metric, fixture_metric());
    assert_eq!(h.sample_count as usize, samples.len());

    let got: Vec<_> = dec.samples().collect::<Result<Vec<_>, _>>().unwrap();
    assert_eq!(got, samples);
}

#[test]
fn encoder_is_deterministic() {
    // Critical for the byte-parity contract: encoding the same input
    // twice must yield byte-identical output. Otherwise we cannot
    // pin the bytes against a checked-in fixture.
    let samples = fixture_samples();
    let encode = || {
        let mut enc = GorillaEncoder::new(fixture_metric(), fixture_labels());
        for (t, v) in &samples {
            enc.append(*t, *v);
        }
        enc.finalize().unwrap()
    };
    let a = encode();
    let b = encode();
    assert_eq!(a, b, "encoder is non-deterministic — byte-parity is impossible");
}

fn fixture_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests");
    p.push("golden");
    p.push("single_series.gor");
    p
}

#[test]
fn decode_telegraf_fixture_if_present() {
    let path = fixture_path();
    let bytes = match fs::read(&path) {
        Ok(b) => b,
        Err(_) => {
            // Fixture not yet regenerated — see tests/golden/regen.sh.
            // This skip is intentional and must NOT fail CI on the
            // initial Phase 1 PR. Once the fixture lands the test
            // body below activates.
            eprintln!(
                "skipping cross-language fixture round-trip: {} not found \
                 (run tests/golden/regen.sh to produce it)",
                path.display()
            );
            return;
        }
    };

    let dec = GorillaDecoder::from_reader(&bytes[..]).expect("decode Go-encoded fixture");
    let h = dec.header().unwrap().clone();
    assert_eq!(h.metric, fixture_metric());
    assert_eq!(h.sample_count as usize, fixture_samples().len());
    let got: Vec<_> = dec.samples().collect::<Result<Vec<_>, _>>().unwrap();
    assert_eq!(got, fixture_samples());
}

#[test]
fn reencode_telegraf_fixture_byte_identical_if_present() {
    let path = fixture_path();
    let golden = match fs::read(&path) {
        Ok(b) => b,
        Err(_) => {
            eprintln!(
                "skipping byte-identical re-encode check: {} not found",
                path.display()
            );
            return;
        }
    };
    let samples = fixture_samples();
    let mut enc = GorillaEncoder::new(fixture_metric(), fixture_labels());
    for (t, v) in &samples {
        enc.append(*t, *v);
    }
    let ours = enc.finalize().unwrap();
    assert_eq!(
        ours, golden,
        "byte-parity violation: asap-gorilla bytes differ from Go fixture"
    );
}
