dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/serfagentcol
  name: serfagentcol
  description: Agent collector that compresses metrics via Serf XOR/Qt and sends to backend
  output_path: ./cmd/serfagentcol/dist
  version: 0.141.0-dev

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.141.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/serfexporter v0.141.0
    path: ./exporter/serfexporter

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.141.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.141.0

replaces:
  - go.opentelemetry.io/collector/pdata => ../../../../opentelemetry-collector/pdata
