// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyDDSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesDDSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewDDSketchDataPoint()
				CopyDDSketchDataPoint(dest, src)
				assert.Equal(t, src, dest)
				CopyDDSketchDataPoint(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyDDSketchDataPointSlice(t *testing.T) {
	src := []DDSketchDataPoint{}
	dest := []DDSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyDDSketchDataPointSlice(dest, src)
	assert.Equal(t, []DDSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestDDSketchDataPointSlice()
	dest = CopyDDSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestDDSketchDataPointSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyDDSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestDDSketchDataPointSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyDDSketchDataPointSlice(dest, []DDSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyDDSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestDDSketchDataPointSlice(), dest)
}

func TestCopyDDSketchDataPointPtrSlice(t *testing.T) {
	src := []*DDSketchDataPoint{}
	dest := []*DDSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyDDSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, []*DDSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestDDSketchDataPointPtrSlice()
	dest = CopyDDSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestDDSketchDataPointPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyDDSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestDDSketchDataPointPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyDDSketchDataPointPtrSlice(dest, []*DDSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyDDSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestDDSketchDataPointPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONDDSketchDataPointUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewDDSketchDataPoint()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewDDSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalJSONDDSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesDDSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewDDSketchDataPoint()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteDDSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoDDSketchDataPointFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesDDSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			dest := NewDDSketchDataPoint()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoDDSketchDataPointUnknown(t *testing.T) {
	dest := NewDDSketchDataPoint()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewDDSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalProtoDDSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesDDSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewDDSketchDataPoint()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteDDSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufDDSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesDDSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.DDSketchDataPoint{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewDDSketchDataPoint()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesDDSketchDataPoint() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                     {0x02},
		"Attributes/wrong_wire_type":        {0x4c},
		"Attributes/missing_value":          {0x4a},
		"SeriesID/wrong_wire_type":          {0x84, 0x1},
		"SeriesID/missing_value":            {0x80, 0x1},
		"StartTimeUnixNano/wrong_wire_type": {0x14},
		"StartTimeUnixNano/missing_value":   {0x11},
		"TimeUnixNano/wrong_wire_type":      {0x1c},
		"TimeUnixNano/missing_value":        {0x19},
		"Count/wrong_wire_type":             {0x24},
		"Count/missing_value":               {0x21},

		"SumAsDouble/wrong_wire_type": {0x2c},
		"SumAsDouble/missing_value":   {0x29},

		"SumAsInt/wrong_wire_type": {0x64},
		"SumAsInt/missing_value":   {0x61},

		"MinAsDouble/wrong_wire_type": {0x34},
		"MinAsDouble/missing_value":   {0x31},

		"MinAsInt/wrong_wire_type": {0x6c},
		"MinAsInt/missing_value":   {0x69},

		"MaxAsDouble/wrong_wire_type": {0x3c},
		"MaxAsDouble/missing_value":   {0x39},

		"MaxAsInt/wrong_wire_type":  {0x74},
		"MaxAsInt/missing_value":    {0x71},
		"Sketch/wrong_wire_type":    {0x44},
		"Sketch/missing_value":      {0x42},
		"Encoding/wrong_wire_type":  {0x54},
		"Encoding/missing_value":    {0x50},
		"Exemplars/wrong_wire_type": {0x5c},
		"Exemplars/missing_value":   {0x5a},
		"Flags/wrong_wire_type":     {0x7c},
		"Flags/missing_value":       {0x78},
	}
}

func genTestEncodingValuesDDSketchDataPoint() map[string]*DDSketchDataPoint {
	return map[string]*DDSketchDataPoint{
		"empty":                  NewDDSketchDataPoint(),
		"Attributes/test":        {Attributes: []KeyValue{{}, *GenTestKeyValue()}},
		"SeriesID/test":          {SeriesID: uint64(13)},
		"StartTimeUnixNano/test": {StartTimeUnixNano: uint64(13)},
		"TimeUnixNano/test":      {TimeUnixNano: uint64(13)},
		"Count/test":             {Count: uint64(13)},
		"SumAsDouble/default":    {Sum: &DDSketchDataPoint_SumAsDouble{SumAsDouble: float64(0)}},
		"SumAsDouble/test":       {Sum: &DDSketchDataPoint_SumAsDouble{SumAsDouble: float64(3.1415926)}},
		"SumAsInt/default":       {Sum: &DDSketchDataPoint_SumAsInt{SumAsInt: int64(0)}},
		"SumAsInt/test":          {Sum: &DDSketchDataPoint_SumAsInt{SumAsInt: int64(13)}},
		"MinAsDouble/default":    {Min: &DDSketchDataPoint_MinAsDouble{MinAsDouble: float64(0)}},
		"MinAsDouble/test":       {Min: &DDSketchDataPoint_MinAsDouble{MinAsDouble: float64(3.1415926)}},
		"MinAsInt/default":       {Min: &DDSketchDataPoint_MinAsInt{MinAsInt: int64(0)}},
		"MinAsInt/test":          {Min: &DDSketchDataPoint_MinAsInt{MinAsInt: int64(13)}},
		"MaxAsDouble/default":    {Max: &DDSketchDataPoint_MaxAsDouble{MaxAsDouble: float64(0)}},
		"MaxAsDouble/test":       {Max: &DDSketchDataPoint_MaxAsDouble{MaxAsDouble: float64(3.1415926)}},
		"MaxAsInt/default":       {Max: &DDSketchDataPoint_MaxAsInt{MaxAsInt: int64(0)}},
		"MaxAsInt/test":          {Max: &DDSketchDataPoint_MaxAsInt{MaxAsInt: int64(13)}},
		"Sketch/test":            {Sketch: []byte{1, 2, 3}},
		"Encoding/test":          {Encoding: DDSketchEncoding(13)},
		"Exemplars/test":         {Exemplars: []Exemplar{{}, *GenTestExemplar()}},
		"Flags/test":             {Flags: uint32(13)},
	}
}
