// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"encoding/binary"
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// CountMinSketchDataPoint is a single data point that encodes frequency estimations using Count-Min Sketch.
type CountMinSketchDataPoint struct {
	Attributes        []KeyValue
	SeriesID          uint64
	StartTimeUnixNano uint64
	TimeUnixNano      uint64
	SampleCount       uint64
	Sketch            []byte
	Encoding          CountMinSketchEncoding
	Rows              int32
	Cols              int32
	Flags             uint32
}

var (
	protoPoolCountMinSketchDataPoint = sync.Pool{
		New: func() any {
			return &CountMinSketchDataPoint{}
		},
	}
)

func NewCountMinSketchDataPoint() *CountMinSketchDataPoint {
	if !UseProtoPooling.IsEnabled() {
		return &CountMinSketchDataPoint{}
	}
	return protoPoolCountMinSketchDataPoint.Get().(*CountMinSketchDataPoint)
}

func DeleteCountMinSketchDataPoint(orig *CountMinSketchDataPoint, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.Attributes {
		DeleteKeyValue(&orig.Attributes[i], false)
	}

	orig.Reset()
	if nullable {
		protoPoolCountMinSketchDataPoint.Put(orig)
	}
}

func CopyCountMinSketchDataPoint(dest, src *CountMinSketchDataPoint) *CountMinSketchDataPoint {
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewCountMinSketchDataPoint()
	}
	dest.Attributes = CopyKeyValueSlice(dest.Attributes, src.Attributes)
	dest.SeriesID = src.SeriesID
	dest.StartTimeUnixNano = src.StartTimeUnixNano
	dest.TimeUnixNano = src.TimeUnixNano
	dest.SampleCount = src.SampleCount
	dest.Sketch = src.Sketch
	dest.Encoding = src.Encoding
	dest.Rows = src.Rows
	dest.Cols = src.Cols
	dest.Flags = src.Flags

	return dest
}

func CopyCountMinSketchDataPointSlice(dest, src []CountMinSketchDataPoint) []CountMinSketchDataPoint {
	var newDest []CountMinSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]CountMinSketchDataPoint, len(src))
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteCountMinSketchDataPoint(&dest[i], false)
		}
	}
	for i := range src {
		CopyCountMinSketchDataPoint(&newDest[i], &src[i])
	}
	return newDest
}

func CopyCountMinSketchDataPointPtrSlice(dest, src []*CountMinSketchDataPoint) []*CountMinSketchDataPoint {
	var newDest []*CountMinSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]*CountMinSketchDataPoint, len(src))
		copy(newDest, dest)
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewCountMinSketchDataPoint()
		}
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteCountMinSketchDataPoint(dest[i], true)
			dest[i] = nil
		}
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewCountMinSketchDataPoint()
		}
	}
	for i := range src {
		CopyCountMinSketchDataPoint(newDest[i], src[i])
	}
	return newDest
}

func (orig *CountMinSketchDataPoint) Reset() {
	*orig = CountMinSketchDataPoint{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *CountMinSketchDataPoint) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.Attributes) > 0 {
		dest.WriteObjectField("attributes")
		dest.WriteArrayStart()
		orig.Attributes[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Attributes); i++ {
			dest.WriteMore()
			orig.Attributes[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.SeriesID != uint64(0) {
		dest.WriteObjectField("seriesID")
		dest.WriteUint64(orig.SeriesID)
	}
	if orig.StartTimeUnixNano != uint64(0) {
		dest.WriteObjectField("startTimeUnixNano")
		dest.WriteUint64(orig.StartTimeUnixNano)
	}
	if orig.TimeUnixNano != uint64(0) {
		dest.WriteObjectField("timeUnixNano")
		dest.WriteUint64(orig.TimeUnixNano)
	}
	if orig.SampleCount != uint64(0) {
		dest.WriteObjectField("sampleCount")
		dest.WriteUint64(orig.SampleCount)
	}
	if len(orig.Sketch) > 0 {
		dest.WriteObjectField("sketch")
		dest.WriteBytes(orig.Sketch)
	}
	if int32(orig.Encoding) != 0 {
		dest.WriteObjectField("encoding")
		dest.WriteInt32(int32(orig.Encoding))
	}
	if orig.Rows != int32(0) {
		dest.WriteObjectField("rows")
		dest.WriteInt32(orig.Rows)
	}
	if orig.Cols != int32(0) {
		dest.WriteObjectField("cols")
		dest.WriteInt32(orig.Cols)
	}
	if orig.Flags != uint32(0) {
		dest.WriteObjectField("flags")
		dest.WriteUint32(orig.Flags)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *CountMinSketchDataPoint) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "attributes":
			for iter.ReadArray() {
				orig.Attributes = append(orig.Attributes, KeyValue{})
				orig.Attributes[len(orig.Attributes)-1].UnmarshalJSON(iter)
			}
		case "seriesID", "series_id":
			orig.SeriesID = iter.ReadUint64()
		case "startTimeUnixNano", "start_time_unix_nano":
			orig.StartTimeUnixNano = iter.ReadUint64()
		case "timeUnixNano", "time_unix_nano":
			orig.TimeUnixNano = iter.ReadUint64()
		case "sampleCount", "sample_count":
			orig.SampleCount = iter.ReadUint64()
		case "sketch":
			orig.Sketch = iter.ReadBytes()
		case "encoding":
			orig.Encoding = CountMinSketchEncoding(iter.ReadEnumValue(CountMinSketchEncoding_value))
		case "rows":
			orig.Rows = iter.ReadInt32()
		case "cols":
			orig.Cols = iter.ReadInt32()
		case "flags":
			orig.Flags = iter.ReadUint32()
		default:
			iter.Skip()
		}
	}
}

func (orig *CountMinSketchDataPoint) SizeProto() int {
	// Field layout:
	//  1=attributes (wire 2)
	//  2=start_time_unix_nano (wire 1, I64)
	//  3=time_unix_nano (wire 1, I64)
	//  4=sample_count (wire 0)
	//  5=sketch (wire 2)
	//  6=encoding (wire 0)
	//  7=rows (wire 0)
	//  8=cols (wire 0)
	//  9=flags (wire 0)
	// 10=series_id (wire 0)
	var n int
	var l int
	_ = l
	for i := range orig.Attributes {
		l = orig.Attributes[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.StartTimeUnixNano != 0 {
		n += 9
	}
	if orig.TimeUnixNano != 0 {
		n += 9
	}
	if orig.SampleCount != 0 {
		n += 1 + proto.Sov(uint64(orig.SampleCount))
	}
	l = len(orig.Sketch)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Encoding != 0 {
		n += 1 + proto.Sov(uint64(orig.Encoding))
	}
	if orig.Rows != 0 {
		n += 1 + proto.Sov(uint64(orig.Rows))
	}
	if orig.Cols != 0 {
		n += 1 + proto.Sov(uint64(orig.Cols))
	}
	if orig.Flags != 0 {
		n += 1 + proto.Sov(uint64(orig.Flags))
	}
	if orig.SeriesID != 0 {
		n += 1 + proto.Sov(uint64(orig.SeriesID))
	}
	return n
}

func (orig *CountMinSketchDataPoint) MarshalProto(buf []byte) int {
	// Wire tag bytes:
	//  1=attributes: 0x0a
	//  2=start_time_unix_nano: 0x11
	//  3=time_unix_nano: 0x19
	//  4=sample_count: 0x20
	//  5=sketch: 0x2a
	//  6=encoding: 0x30
	//  7=rows: 0x38
	//  8=cols: 0x40
	//  9=flags: 0x48
	// 10=series_id: 0x50
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.Attributes) - 1; i >= 0; i-- {
		l = orig.Attributes[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x0a
	}
	if orig.SeriesID != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.SeriesID))
		pos--
		buf[pos] = 0x50
	}
	if orig.StartTimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.StartTimeUnixNano))
		pos--
		buf[pos] = 0x11
	}
	if orig.TimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.TimeUnixNano))
		pos--
		buf[pos] = 0x19
	}
	if orig.SampleCount != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.SampleCount))
		pos--
		buf[pos] = 0x20
	}
	l = len(orig.Sketch)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Sketch)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x2a
	}
	if orig.Encoding != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Encoding))
		pos--
		buf[pos] = 0x30
	}
	if orig.Rows != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Rows))
		pos--
		buf[pos] = 0x38
	}
	if orig.Cols != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Cols))
		pos--
		buf[pos] = 0x40
	}
	if orig.Flags != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Flags))
		pos--
		buf[pos] = 0x48
	}
	return len(buf) - pos
}

func (orig *CountMinSketchDataPoint) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Attributes = append(orig.Attributes, KeyValue{})
			err = orig.Attributes[len(orig.Attributes)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.StartTimeUnixNano = uint64(num)

		case 3:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.TimeUnixNano = uint64(num)

		case 4:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field SampleCount", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.SampleCount = uint64(num)

		case 5:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sketch", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.Sketch = make([]byte, length)
				copy(orig.Sketch, buf[startPos:pos])
			}

		case 6:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Encoding = CountMinSketchEncoding(num)

		case 7:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Rows = int32(num)

		case 8:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Cols", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Cols = int32(num)

		case 9:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Flags = uint32(num)

		case 10:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field SeriesID", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.SeriesID = uint64(num)

		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestCountMinSketchDataPoint() *CountMinSketchDataPoint {
	orig := NewCountMinSketchDataPoint()
	orig.Attributes = []KeyValue{{}, *GenTestKeyValue()}
	orig.SeriesID = uint64(13)
	orig.StartTimeUnixNano = uint64(13)
	orig.TimeUnixNano = uint64(13)
	orig.SampleCount = uint64(100)
	orig.Sketch = []byte{1, 2, 3}
	orig.Encoding = CountMinSketchEncoding(1)
	orig.Rows = int32(5)
	orig.Cols = int32(2048)
	orig.Flags = uint32(13)
	return orig
}

func GenTestCountMinSketchDataPointPtrSlice() []*CountMinSketchDataPoint {
	orig := make([]*CountMinSketchDataPoint, 5)
	orig[0] = NewCountMinSketchDataPoint()
	orig[1] = GenTestCountMinSketchDataPoint()
	orig[2] = NewCountMinSketchDataPoint()
	orig[3] = GenTestCountMinSketchDataPoint()
	orig[4] = NewCountMinSketchDataPoint()
	return orig
}

func GenTestCountMinSketchDataPointSlice() []CountMinSketchDataPoint {
	orig := make([]CountMinSketchDataPoint, 5)
	orig[1] = *GenTestCountMinSketchDataPoint()
	orig[3] = *GenTestCountMinSketchDataPoint()
	return orig
}
