// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"encoding/binary"
	"fmt"
	"math"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// CountSketchDataPoint is a single data point that encodes frequency estimations using CountSketch.
type CountSketchDataPoint struct {
	Attributes        []KeyValue
	SeriesID          uint64
	StartTimeUnixNano uint64
	TimeUnixNano      uint64
	Sketch            []byte
	Encoding          CountSketchEncoding
	Dimension         string
	Epsilon           float64
	Delta             float64
	Flags             uint32
}

var (
	protoPoolCountSketchDataPoint = sync.Pool{
		New: func() any {
			return &CountSketchDataPoint{}
		},
	}
)

func NewCountSketchDataPoint() *CountSketchDataPoint {
	if !UseProtoPooling.IsEnabled() {
		return &CountSketchDataPoint{}
	}
	return protoPoolCountSketchDataPoint.Get().(*CountSketchDataPoint)
}

func DeleteCountSketchDataPoint(orig *CountSketchDataPoint, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.Attributes {
		DeleteKeyValue(&orig.Attributes[i], false)
	}

	orig.Reset()
	if nullable {
		protoPoolCountSketchDataPoint.Put(orig)
	}
}

func CopyCountSketchDataPoint(dest, src *CountSketchDataPoint) *CountSketchDataPoint {
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewCountSketchDataPoint()
	}
	dest.Attributes = CopyKeyValueSlice(dest.Attributes, src.Attributes)
	dest.SeriesID = src.SeriesID
	dest.StartTimeUnixNano = src.StartTimeUnixNano
	dest.TimeUnixNano = src.TimeUnixNano
	dest.Sketch = src.Sketch
	dest.Encoding = src.Encoding
	dest.Dimension = src.Dimension
	dest.Epsilon = src.Epsilon
	dest.Delta = src.Delta
	dest.Flags = src.Flags

	return dest
}

func CopyCountSketchDataPointSlice(dest, src []CountSketchDataPoint) []CountSketchDataPoint {
	var newDest []CountSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]CountSketchDataPoint, len(src))
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteCountSketchDataPoint(&dest[i], false)
		}
	}
	for i := range src {
		CopyCountSketchDataPoint(&newDest[i], &src[i])
	}
	return newDest
}

func CopyCountSketchDataPointPtrSlice(dest, src []*CountSketchDataPoint) []*CountSketchDataPoint {
	var newDest []*CountSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]*CountSketchDataPoint, len(src))
		copy(newDest, dest)
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewCountSketchDataPoint()
		}
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteCountSketchDataPoint(dest[i], true)
			dest[i] = nil
		}
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewCountSketchDataPoint()
		}
	}
	for i := range src {
		CopyCountSketchDataPoint(newDest[i], src[i])
	}
	return newDest
}

func (orig *CountSketchDataPoint) Reset() {
	*orig = CountSketchDataPoint{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *CountSketchDataPoint) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.Attributes) > 0 {
		dest.WriteObjectField("attributes")
		dest.WriteArrayStart()
		orig.Attributes[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Attributes); i++ {
			dest.WriteMore()
			orig.Attributes[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.SeriesID != uint64(0) {
		dest.WriteObjectField("seriesID")
		dest.WriteUint64(orig.SeriesID)
	}
	if orig.StartTimeUnixNano != uint64(0) {
		dest.WriteObjectField("startTimeUnixNano")
		dest.WriteUint64(orig.StartTimeUnixNano)
	}
	if orig.TimeUnixNano != uint64(0) {
		dest.WriteObjectField("timeUnixNano")
		dest.WriteUint64(orig.TimeUnixNano)
	}
	if len(orig.Sketch) > 0 {
		dest.WriteObjectField("sketch")
		dest.WriteBytes(orig.Sketch)
	}
	if int32(orig.Encoding) != 0 {
		dest.WriteObjectField("encoding")
		dest.WriteInt32(int32(orig.Encoding))
	}
	if orig.Dimension != "" {
		dest.WriteObjectField("dimension")
		dest.WriteString(orig.Dimension)
	}
	if orig.Epsilon != float64(0) {
		dest.WriteObjectField("epsilon")
		dest.WriteFloat64(orig.Epsilon)
	}
	if orig.Delta != float64(0) {
		dest.WriteObjectField("delta")
		dest.WriteFloat64(orig.Delta)
	}
	if orig.Flags != uint32(0) {
		dest.WriteObjectField("flags")
		dest.WriteUint32(orig.Flags)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *CountSketchDataPoint) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "attributes":
			for iter.ReadArray() {
				orig.Attributes = append(orig.Attributes, KeyValue{})
				orig.Attributes[len(orig.Attributes)-1].UnmarshalJSON(iter)
			}
		case "seriesID", "series_id":
			orig.SeriesID = iter.ReadUint64()
		case "startTimeUnixNano", "start_time_unix_nano":
			orig.StartTimeUnixNano = iter.ReadUint64()
		case "timeUnixNano", "time_unix_nano":
			orig.TimeUnixNano = iter.ReadUint64()
		case "sketch":
			orig.Sketch = iter.ReadBytes()
		case "encoding":
			orig.Encoding = CountSketchEncoding(iter.ReadEnumValue(CountSketchEncoding_value))
		case "dimension":
			orig.Dimension = iter.ReadString()
		case "epsilon":
			orig.Epsilon = iter.ReadFloat64()
		case "delta":
			orig.Delta = iter.ReadFloat64()
		case "flags":
			orig.Flags = iter.ReadUint32()
		default:
			iter.Skip()
		}
	}
}

func (orig *CountSketchDataPoint) SizeProto() int {
	// Field layout:
	//  1=attributes (wire 2)
	//  2=start_time_unix_nano (wire 1, I64)
	//  3=time_unix_nano (wire 1, I64)
	//  4=sketch (wire 2)
	//  5=encoding (wire 0)
	//  6=dimension (wire 2)
	//  7=epsilon (wire 1, I64)
	//  8=delta (wire 1, I64)
	//  9=flags (wire 0)
	// 10=series_id (wire 0)
	var n int
	var l int
	_ = l
	for i := range orig.Attributes {
		l = orig.Attributes[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.StartTimeUnixNano != 0 {
		n += 9
	}
	if orig.TimeUnixNano != 0 {
		n += 9
	}
	l = len(orig.Sketch)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Encoding != 0 {
		n += 1 + proto.Sov(uint64(orig.Encoding))
	}
	l = len(orig.Dimension)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Epsilon != 0 {
		n += 9
	}
	if orig.Delta != 0 {
		n += 9
	}
	if orig.Flags != 0 {
		n += 1 + proto.Sov(uint64(orig.Flags))
	}
	if orig.SeriesID != 0 {
		n += 1 + proto.Sov(uint64(orig.SeriesID))
	}
	return n
}

func (orig *CountSketchDataPoint) MarshalProto(buf []byte) int {
	// Wire tag bytes:
	//  1=attributes: 0x0a
	//  2=start_time_unix_nano: 0x11
	//  3=time_unix_nano: 0x19
	//  4=sketch: 0x22
	//  5=encoding: 0x28
	//  6=dimension: 0x32
	//  7=epsilon: 0x39
	//  8=delta: 0x41
	//  9=flags: 0x48
	// 10=series_id: 0x50
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.Attributes) - 1; i >= 0; i-- {
		l = orig.Attributes[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x0a
	}
	if orig.SeriesID != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.SeriesID))
		pos--
		buf[pos] = 0x50
	}
	if orig.StartTimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.StartTimeUnixNano))
		pos--
		buf[pos] = 0x11
	}
	if orig.TimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.TimeUnixNano))
		pos--
		buf[pos] = 0x19
	}
	l = len(orig.Sketch)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Sketch)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x22
	}
	if orig.Encoding != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Encoding))
		pos--
		buf[pos] = 0x28
	}
	l = len(orig.Dimension)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Dimension)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x32
	}
	if orig.Epsilon != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.Epsilon))
		pos--
		buf[pos] = 0x39
	}
	if orig.Delta != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.Delta))
		pos--
		buf[pos] = 0x41
	}
	if orig.Flags != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Flags))
		pos--
		buf[pos] = 0x48
	}
	return len(buf) - pos
}

func (orig *CountSketchDataPoint) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Attributes = append(orig.Attributes, KeyValue{})
			err = orig.Attributes[len(orig.Attributes)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.StartTimeUnixNano = uint64(num)

		case 3:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.TimeUnixNano = uint64(num)

		case 4:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sketch", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.Sketch = make([]byte, length)
				copy(orig.Sketch, buf[startPos:pos])
			}

		case 5:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Encoding = CountSketchEncoding(num)

		case 6:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Dimension", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Dimension = string(buf[startPos:pos])

		case 7:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epsilon", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.Epsilon = math.Float64frombits(num)

		case 8:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delta", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.Delta = math.Float64frombits(num)

		case 9:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Flags = uint32(num)

		case 10:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field SeriesID", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.SeriesID = uint64(num)

		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestCountSketchDataPoint() *CountSketchDataPoint {
	orig := NewCountSketchDataPoint()
	orig.Attributes = []KeyValue{{}, *GenTestKeyValue()}
	orig.SeriesID = uint64(13)
	orig.StartTimeUnixNano = uint64(13)
	orig.TimeUnixNano = uint64(13)
	orig.Sketch = []byte{1, 2, 3}
	orig.Encoding = CountSketchEncoding(1)
	orig.Dimension = "row"
	orig.Epsilon = float64(0.001)
	orig.Delta = float64(0.01)
	orig.Flags = uint32(13)
	return orig
}

func GenTestCountSketchDataPointPtrSlice() []*CountSketchDataPoint {
	orig := make([]*CountSketchDataPoint, 5)
	orig[0] = NewCountSketchDataPoint()
	orig[1] = GenTestCountSketchDataPoint()
	orig[2] = NewCountSketchDataPoint()
	orig[3] = GenTestCountSketchDataPoint()
	orig[4] = NewCountSketchDataPoint()
	return orig
}

func GenTestCountSketchDataPointSlice() []CountSketchDataPoint {
	orig := make([]CountSketchDataPoint, 5)
	orig[1] = *GenTestCountSketchDataPoint()
	orig[3] = *GenTestCountSketchDataPoint()
	return orig
}
