// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyCountMinSketch(t *testing.T) {
	for name, src := range genTestEncodingValuesCountMinSketch() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewCountMinSketch()
				CopyCountMinSketch(dest, src)
				assert.Equal(t, src, dest)
				CopyCountMinSketch(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyCountMinSketchSlice(t *testing.T) {
	src := []CountMinSketch{}
	dest := []CountMinSketch{}
	// Test CopyTo empty
	dest = CopyCountMinSketchSlice(dest, src)
	assert.Equal(t, []CountMinSketch{}, dest)

	// Test CopyTo larger slice
	src = GenTestCountMinSketchSlice()
	dest = CopyCountMinSketchSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyCountMinSketchSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyCountMinSketchSlice(dest, []CountMinSketch{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyCountMinSketchSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchSlice(), dest)
}

func TestCopyCountMinSketchPtrSlice(t *testing.T) {
	src := []*CountMinSketch{}
	dest := []*CountMinSketch{}
	// Test CopyTo empty
	dest = CopyCountMinSketchPtrSlice(dest, src)
	assert.Equal(t, []*CountMinSketch{}, dest)

	// Test CopyTo larger slice
	src = GenTestCountMinSketchPtrSlice()
	dest = CopyCountMinSketchPtrSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyCountMinSketchPtrSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyCountMinSketchPtrSlice(dest, []*CountMinSketch{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyCountMinSketchPtrSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONCountMinSketchUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewCountMinSketch()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewCountMinSketch(), dest)
}

func TestMarshalAndUnmarshalJSONCountMinSketch(t *testing.T) {
	for name, src := range genTestEncodingValuesCountMinSketch() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewCountMinSketch()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteCountMinSketch(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoCountMinSketchFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesCountMinSketch() {
		t.Run(name, func(t *testing.T) {
			dest := NewCountMinSketch()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoCountMinSketchUnknown(t *testing.T) {
	dest := NewCountMinSketch()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewCountMinSketch(), dest)
}

func TestMarshalAndUnmarshalProtoCountMinSketch(t *testing.T) {
	for name, src := range genTestEncodingValuesCountMinSketch() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewCountMinSketch()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteCountMinSketch(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufCountMinSketch(t *testing.T) {
	for name, src := range genTestEncodingValuesCountMinSketch() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.CountMinSketch{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewCountMinSketch()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesCountMinSketch() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                          {0x02},
		"DataPoints/wrong_wire_type":             {0xc},
		"DataPoints/missing_value":               {0xa},
		"AggregationTemporality/wrong_wire_type": {0x14},
		"AggregationTemporality/missing_value":   {0x10},
		"Rows/wrong_wire_type":                   {0x1c},
		"Rows/missing_value":                     {0x18},
		"Cols/wrong_wire_type":                   {0x24},
		"Cols/missing_value":                     {0x20},
	}
}

func genTestEncodingValuesCountMinSketch() map[string]*CountMinSketch {
	return map[string]*CountMinSketch{
		"empty":                       NewCountMinSketch(),
		"DataPoints/test":             {DataPoints: []*CountMinSketchDataPoint{{}, GenTestCountMinSketchDataPoint()}},
		"AggregationTemporality/test": {AggregationTemporality: AggregationTemporality(13)},
		"Rows/test":                   {Rows: int32(13)},
		"Cols/test":                   {Cols: int32(13)},
	}
}
