// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpcollectormetrics "go.opentelemetry.io/proto/slim/otlp/collector/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopySeriesAssignment(t *testing.T) {
	for name, src := range genTestEncodingValuesSeriesAssignment() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewSeriesAssignment()
				CopySeriesAssignment(dest, src)
				assert.Equal(t, src, dest)
				CopySeriesAssignment(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopySeriesAssignmentSlice(t *testing.T) {
	src := []SeriesAssignment{}
	dest := []SeriesAssignment{}
	// Test CopyTo empty
	dest = CopySeriesAssignmentSlice(dest, src)
	assert.Equal(t, []SeriesAssignment{}, dest)

	// Test CopyTo larger slice
	src = GenTestSeriesAssignmentSlice()
	dest = CopySeriesAssignmentSlice(dest, src)
	assert.Equal(t, GenTestSeriesAssignmentSlice(), dest)

	// Test CopyTo same size slice
	dest = CopySeriesAssignmentSlice(dest, src)
	assert.Equal(t, GenTestSeriesAssignmentSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopySeriesAssignmentSlice(dest, []SeriesAssignment{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopySeriesAssignmentSlice(dest, src)
	assert.Equal(t, GenTestSeriesAssignmentSlice(), dest)
}

func TestCopySeriesAssignmentPtrSlice(t *testing.T) {
	src := []*SeriesAssignment{}
	dest := []*SeriesAssignment{}
	// Test CopyTo empty
	dest = CopySeriesAssignmentPtrSlice(dest, src)
	assert.Equal(t, []*SeriesAssignment{}, dest)

	// Test CopyTo larger slice
	src = GenTestSeriesAssignmentPtrSlice()
	dest = CopySeriesAssignmentPtrSlice(dest, src)
	assert.Equal(t, GenTestSeriesAssignmentPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopySeriesAssignmentPtrSlice(dest, src)
	assert.Equal(t, GenTestSeriesAssignmentPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopySeriesAssignmentPtrSlice(dest, []*SeriesAssignment{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopySeriesAssignmentPtrSlice(dest, src)
	assert.Equal(t, GenTestSeriesAssignmentPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONSeriesAssignmentUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewSeriesAssignment()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewSeriesAssignment(), dest)
}

func TestMarshalAndUnmarshalJSONSeriesAssignment(t *testing.T) {
	for name, src := range genTestEncodingValuesSeriesAssignment() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewSeriesAssignment()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteSeriesAssignment(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoSeriesAssignmentFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesSeriesAssignment() {
		t.Run(name, func(t *testing.T) {
			dest := NewSeriesAssignment()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoSeriesAssignmentUnknown(t *testing.T) {
	dest := NewSeriesAssignment()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewSeriesAssignment(), dest)
}

func TestMarshalAndUnmarshalProtoSeriesAssignment(t *testing.T) {
	for name, src := range genTestEncodingValuesSeriesAssignment() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewSeriesAssignment()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteSeriesAssignment(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufSeriesAssignment(t *testing.T) {
	for name, src := range genTestEncodingValuesSeriesAssignment() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpcollectormetrics.SeriesAssignment{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewSeriesAssignment()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesSeriesAssignment() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                         {0x02},
		"ResourceKey/wrong_wire_type":           {0xc},
		"ResourceKey/missing_value":             {0xa},
		"ScopeKey/wrong_wire_type":              {0x14},
		"ScopeKey/missing_value":                {0x12},
		"MetricName/wrong_wire_type":            {0x1c},
		"MetricName/missing_value":              {0x1a},
		"MetricType/wrong_wire_type":            {0x24},
		"MetricType/missing_value":              {0x22},
		"AttributesFingerprint/wrong_wire_type": {0x2c},
		"AttributesFingerprint/missing_value":   {0x2a},
		"SeriesID/wrong_wire_type":              {0x34},
		"SeriesID/missing_value":                {0x30},
	}
}

func genTestEncodingValuesSeriesAssignment() map[string]*SeriesAssignment {
	return map[string]*SeriesAssignment{
		"empty":                      NewSeriesAssignment(),
		"ResourceKey/test":           {ResourceKey: "test_resourcekey"},
		"ScopeKey/test":              {ScopeKey: "test_scopekey"},
		"MetricName/test":            {MetricName: "test_metricname"},
		"MetricType/test":            {MetricType: "test_metrictype"},
		"AttributesFingerprint/test": {AttributesFingerprint: []byte{1, 2, 3}},
		"SeriesID/test":              {SeriesID: uint64(13)},
	}
}
