// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// SumAgg represents a first-class scalar Sum aggregate (AggregationKind = Sum), carried as a portable {sum,count} envelope in the Sketch bytes. It is NOT a sketch; it rides the modified-OTLP metric data oneof alongside the sketch families so the backend can decode it via the same envelope path (into the ExactAgg(Sum) accumulator).
type SumAgg struct {
	DataPoints             []*SumAggDataPoint
	AggregationTemporality AggregationTemporality
}

var (
	protoPoolSumAgg = sync.Pool{
		New: func() any {
			return &SumAgg{}
		},
	}
)

func NewSumAgg() *SumAgg {
	if !UseProtoPooling.IsEnabled() {
		return &SumAgg{}
	}
	return protoPoolSumAgg.Get().(*SumAgg)
}

func DeleteSumAgg(orig *SumAgg, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.DataPoints {
		DeleteSumAggDataPoint(orig.DataPoints[i], true)
	}

	orig.Reset()
	if nullable {
		protoPoolSumAgg.Put(orig)
	}
}

func CopySumAgg(dest, src *SumAgg) *SumAgg {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewSumAgg()
	}
	dest.DataPoints = CopySumAggDataPointPtrSlice(dest.DataPoints, src.DataPoints)

	dest.AggregationTemporality = src.AggregationTemporality

	return dest
}

func CopySumAggSlice(dest, src []SumAgg) []SumAgg {
	var newDest []SumAgg
	if cap(dest) < len(src) {
		newDest = make([]SumAgg, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteSumAgg(&dest[i], false)
		}
	}
	for i := range src {
		CopySumAgg(&newDest[i], &src[i])
	}
	return newDest
}

func CopySumAggPtrSlice(dest, src []*SumAgg) []*SumAgg {
	var newDest []*SumAgg
	if cap(dest) < len(src) {
		newDest = make([]*SumAgg, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewSumAgg()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteSumAgg(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewSumAgg()
		}
	}
	for i := range src {
		CopySumAgg(newDest[i], src[i])
	}
	return newDest
}

func (orig *SumAgg) Reset() {
	*orig = SumAgg{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *SumAgg) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.DataPoints) > 0 {
		dest.WriteObjectField("dataPoints")
		dest.WriteArrayStart()
		orig.DataPoints[0].MarshalJSON(dest)
		for i := 1; i < len(orig.DataPoints); i++ {
			dest.WriteMore()
			orig.DataPoints[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}

	if int32(orig.AggregationTemporality) != 0 {
		dest.WriteObjectField("aggregationTemporality")
		dest.WriteInt32(int32(orig.AggregationTemporality))
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *SumAgg) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "dataPoints", "data_points":
			for iter.ReadArray() {
				orig.DataPoints = append(orig.DataPoints, NewSumAggDataPoint())
				orig.DataPoints[len(orig.DataPoints)-1].UnmarshalJSON(iter)
			}

		case "aggregationTemporality", "aggregation_temporality":
			orig.AggregationTemporality = AggregationTemporality(iter.ReadEnumValue(AggregationTemporality_value))
		default:
			iter.Skip()
		}
	}
}

func (orig *SumAgg) SizeProto() int {
	var n int
	var l int
	_ = l
	for i := range orig.DataPoints {
		l = orig.DataPoints[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.AggregationTemporality != 0 {
		n += 1 + proto.Sov(uint64(orig.AggregationTemporality))
	}
	return n
}

func (orig *SumAgg) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.DataPoints) - 1; i >= 0; i-- {
		l = orig.DataPoints[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	if orig.AggregationTemporality != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.AggregationTemporality))
		pos--
		buf[pos] = 0x10
	}
	return len(buf) - pos
}

func (orig *SumAgg) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		// If in a group parsing, move to the next tag.
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPoints", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.DataPoints = append(orig.DataPoints, NewSumAggDataPoint())
			err = orig.DataPoints[len(orig.DataPoints)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationTemporality", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.AggregationTemporality = AggregationTemporality(num)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestSumAgg() *SumAgg {
	orig := NewSumAgg()
	orig.DataPoints = []*SumAggDataPoint{{}, GenTestSumAggDataPoint()}
	orig.AggregationTemporality = AggregationTemporality(13)
	return orig
}

func GenTestSumAggPtrSlice() []*SumAgg {
	orig := make([]*SumAgg, 5)
	orig[0] = NewSumAgg()
	orig[1] = GenTestSumAgg()
	orig[2] = NewSumAgg()
	orig[3] = GenTestSumAgg()
	orig[4] = NewSumAgg()
	return orig
}

func GenTestSumAggSlice() []SumAgg {
	orig := make([]SumAgg, 5)
	orig[1] = *GenTestSumAgg()
	orig[3] = *GenTestSumAgg()
	return orig
}
