// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyHLLSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesHLLSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewHLLSketchDataPoint()
				CopyHLLSketchDataPoint(dest, src)
				assert.Equal(t, src, dest)
				CopyHLLSketchDataPoint(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyHLLSketchDataPointSlice(t *testing.T) {
	src := []HLLSketchDataPoint{}
	dest := []HLLSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyHLLSketchDataPointSlice(dest, src)
	assert.Equal(t, []HLLSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestHLLSketchDataPointSlice()
	dest = CopyHLLSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestHLLSketchDataPointSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyHLLSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestHLLSketchDataPointSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyHLLSketchDataPointSlice(dest, []HLLSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyHLLSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestHLLSketchDataPointSlice(), dest)
}

func TestCopyHLLSketchDataPointPtrSlice(t *testing.T) {
	src := []*HLLSketchDataPoint{}
	dest := []*HLLSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyHLLSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, []*HLLSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestHLLSketchDataPointPtrSlice()
	dest = CopyHLLSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestHLLSketchDataPointPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyHLLSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestHLLSketchDataPointPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyHLLSketchDataPointPtrSlice(dest, []*HLLSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyHLLSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestHLLSketchDataPointPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONHLLSketchDataPointUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewHLLSketchDataPoint()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewHLLSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalJSONHLLSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesHLLSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewHLLSketchDataPoint()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteHLLSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoHLLSketchDataPointFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesHLLSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			dest := NewHLLSketchDataPoint()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoHLLSketchDataPointUnknown(t *testing.T) {
	dest := NewHLLSketchDataPoint()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewHLLSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalProtoHLLSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesHLLSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewHLLSketchDataPoint()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteHLLSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufHLLSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesHLLSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.HLLSketchDataPoint{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewHLLSketchDataPoint()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesHLLSketchDataPoint() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                     {0x02},
		"Attributes/wrong_wire_type":        {0xc},
		"Attributes/missing_value":          {0xa},
		"StartTimeUnixNano/wrong_wire_type": {0x14},
		"StartTimeUnixNano/missing_value":   {0x11},
		"TimeUnixNano/wrong_wire_type":      {0x1c},
		"TimeUnixNano/missing_value":        {0x19},
		"Sketch/wrong_wire_type":            {0x34},
		"Sketch/missing_value":              {0x32},
		"Encoding/wrong_wire_type":          {0x3c},
		"Encoding/missing_value":            {0x38},
		"Flags/wrong_wire_type":             {0x4c},
		"Flags/missing_value":               {0x48},
		"SeriesID/wrong_wire_type":          {0x54},
		"SeriesID/missing_value":            {0x50},
	}
}

func genTestEncodingValuesHLLSketchDataPoint() map[string]*HLLSketchDataPoint {
	return map[string]*HLLSketchDataPoint{
		"empty":                  NewHLLSketchDataPoint(),
		"Attributes/test":        {Attributes: []KeyValue{{}, *GenTestKeyValue()}},
		"StartTimeUnixNano/test": {StartTimeUnixNano: uint64(13)},
		"TimeUnixNano/test":      {TimeUnixNano: uint64(13)},
		"Sketch/test":            {Sketch: []byte{1, 2, 3}},
		"Encoding/test":          {Encoding: HLLSketchEncoding(13)},
		"Flags/test":             {Flags: uint32(13)},
		"SeriesID/test":          {SeriesID: uint64(13)},
	}
}
