// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// KLLSketch represents the type of a metric encoded using the KLL quantile sketch algorithm.
type KLLSketch struct {
	DataPoints             []*KLLSketchDataPoint
	AggregationTemporality AggregationTemporality
}

var (
	protoPoolKLLSketch = sync.Pool{
		New: func() any {
			return &KLLSketch{}
		},
	}
)

func NewKLLSketch() *KLLSketch {
	if !UseProtoPooling.IsEnabled() {
		return &KLLSketch{}
	}
	return protoPoolKLLSketch.Get().(*KLLSketch)
}

func DeleteKLLSketch(orig *KLLSketch, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.DataPoints {
		DeleteKLLSketchDataPoint(orig.DataPoints[i], true)
	}

	orig.Reset()
	if nullable {
		protoPoolKLLSketch.Put(orig)
	}
}

func CopyKLLSketch(dest, src *KLLSketch) *KLLSketch {
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewKLLSketch()
	}
	dest.DataPoints = CopyKLLSketchDataPointPtrSlice(dest.DataPoints, src.DataPoints)

	dest.AggregationTemporality = src.AggregationTemporality

	return dest
}

func CopyKLLSketchSlice(dest, src []KLLSketch) []KLLSketch {
	var newDest []KLLSketch
	if cap(dest) < len(src) {
		newDest = make([]KLLSketch, len(src))
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteKLLSketch(&dest[i], false)
		}
	}
	for i := range src {
		CopyKLLSketch(&newDest[i], &src[i])
	}
	return newDest
}

func CopyKLLSketchPtrSlice(dest, src []*KLLSketch) []*KLLSketch {
	var newDest []*KLLSketch
	if cap(dest) < len(src) {
		newDest = make([]*KLLSketch, len(src))
		copy(newDest, dest)
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewKLLSketch()
		}
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteKLLSketch(dest[i], true)
			dest[i] = nil
		}
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewKLLSketch()
		}
	}
	for i := range src {
		CopyKLLSketch(newDest[i], src[i])
	}
	return newDest
}

func (orig *KLLSketch) Reset() {
	*orig = KLLSketch{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *KLLSketch) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.DataPoints) > 0 {
		dest.WriteObjectField("dataPoints")
		dest.WriteArrayStart()
		orig.DataPoints[0].MarshalJSON(dest)
		for i := 1; i < len(orig.DataPoints); i++ {
			dest.WriteMore()
			orig.DataPoints[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}

	if int32(orig.AggregationTemporality) != 0 {
		dest.WriteObjectField("aggregationTemporality")
		dest.WriteInt32(int32(orig.AggregationTemporality))
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *KLLSketch) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "dataPoints", "data_points":
			for iter.ReadArray() {
				orig.DataPoints = append(orig.DataPoints, NewKLLSketchDataPoint())
				orig.DataPoints[len(orig.DataPoints)-1].UnmarshalJSON(iter)
			}

		case "aggregationTemporality", "aggregation_temporality":
			orig.AggregationTemporality = AggregationTemporality(iter.ReadEnumValue(AggregationTemporality_value))
		default:
			iter.Skip()
		}
	}
}

func (orig *KLLSketch) SizeProto() int {
	var n int
	var l int
	_ = l
	for i := range orig.DataPoints {
		l = orig.DataPoints[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.AggregationTemporality != 0 {
		n += 1 + proto.Sov(uint64(orig.AggregationTemporality))
	}
	return n
}

func (orig *KLLSketch) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.DataPoints) - 1; i >= 0; i-- {
		l = orig.DataPoints[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	if orig.AggregationTemporality != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.AggregationTemporality))
		pos--
		buf[pos] = 0x10
	}
	return len(buf) - pos
}

func (orig *KLLSketch) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPoints", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.DataPoints = append(orig.DataPoints, NewKLLSketchDataPoint())
			err = orig.DataPoints[len(orig.DataPoints)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationTemporality", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.AggregationTemporality = AggregationTemporality(num)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestKLLSketch() *KLLSketch {
	orig := NewKLLSketch()
	orig.DataPoints = []*KLLSketchDataPoint{{}, GenTestKLLSketchDataPoint()}
	orig.AggregationTemporality = AggregationTemporality(13)
	return orig
}

func GenTestKLLSketchPtrSlice() []*KLLSketch {
	orig := make([]*KLLSketch, 5)
	orig[0] = NewKLLSketch()
	orig[1] = GenTestKLLSketch()
	orig[2] = NewKLLSketch()
	orig[3] = GenTestKLLSketch()
	orig[4] = NewKLLSketch()
	return orig
}

func GenTestKLLSketchSlice() []KLLSketch {
	orig := make([]KLLSketch, 5)
	orig[1] = *GenTestKLLSketch()
	orig[3] = *GenTestKLLSketch()
	return orig
}
