// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyKLLSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesKLLSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewKLLSketchDataPoint()
				CopyKLLSketchDataPoint(dest, src)
				assert.Equal(t, src, dest)
				CopyKLLSketchDataPoint(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyKLLSketchDataPointSlice(t *testing.T) {
	src := []KLLSketchDataPoint{}
	dest := []KLLSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyKLLSketchDataPointSlice(dest, src)
	assert.Equal(t, []KLLSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestKLLSketchDataPointSlice()
	dest = CopyKLLSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestKLLSketchDataPointSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyKLLSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestKLLSketchDataPointSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyKLLSketchDataPointSlice(dest, []KLLSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyKLLSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestKLLSketchDataPointSlice(), dest)
}

func TestCopyKLLSketchDataPointPtrSlice(t *testing.T) {
	src := []*KLLSketchDataPoint{}
	dest := []*KLLSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyKLLSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, []*KLLSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestKLLSketchDataPointPtrSlice()
	dest = CopyKLLSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestKLLSketchDataPointPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyKLLSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestKLLSketchDataPointPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyKLLSketchDataPointPtrSlice(dest, []*KLLSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyKLLSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestKLLSketchDataPointPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONKLLSketchDataPointUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewKLLSketchDataPoint()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewKLLSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalJSONKLLSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesKLLSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewKLLSketchDataPoint()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteKLLSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoKLLSketchDataPointFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesKLLSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			dest := NewKLLSketchDataPoint()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoKLLSketchDataPointUnknown(t *testing.T) {
	dest := NewKLLSketchDataPoint()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewKLLSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalProtoKLLSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesKLLSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewKLLSketchDataPoint()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteKLLSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufKLLSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesKLLSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.KLLSketchDataPoint{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewKLLSketchDataPoint()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesKLLSketchDataPoint() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                     {0x02},
		"Attributes/wrong_wire_type":        {0xc},
		"Attributes/missing_value":          {0xa},
		"StartTimeUnixNano/wrong_wire_type": {0x14},
		"StartTimeUnixNano/missing_value":   {0x11},
		"TimeUnixNano/wrong_wire_type":      {0x1c},
		"TimeUnixNano/missing_value":        {0x19},
		"Sketch/wrong_wire_type":            {0x44},
		"Sketch/missing_value":              {0x42},
		"Encoding/wrong_wire_type":          {0x4c},
		"Encoding/missing_value":            {0x48},
		"Flags/wrong_wire_type":             {0x54},
		"Flags/missing_value":               {0x50},
		"SeriesID/wrong_wire_type":          {0x5c},
		"SeriesID/missing_value":            {0x58},
	}
}

func genTestEncodingValuesKLLSketchDataPoint() map[string]*KLLSketchDataPoint {
	return map[string]*KLLSketchDataPoint{
		"empty":                  NewKLLSketchDataPoint(),
		"Attributes/test":        {Attributes: []KeyValue{{}, *GenTestKeyValue()}},
		"StartTimeUnixNano/test": {StartTimeUnixNano: uint64(13)},
		"TimeUnixNano/test":      {TimeUnixNano: uint64(13)},
		"Sketch/test":            {Sketch: []byte{1, 2, 3}},
		"Encoding/test":          {Encoding: KLLSketchEncoding(13)},
		"Flags/test":             {Flags: uint32(13)},
		"SeriesID/test":          {SeriesID: uint64(13)},
	}
}
