// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"encoding/binary"
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// SumAggDataPoint is a single data point carrying a scalar Sum aggregate as a portable {sum,count} envelope in the Sketch bytes.
type SumAggDataPoint struct {
	Attributes        []KeyValue
	SeriesID          uint64
	StartTimeUnixNano uint64
	TimeUnixNano      uint64
	Sketch            []byte
	Encoding          SumAggEncoding
	Exemplars         []Exemplar
	Flags             uint32
}

var (
	protoPoolSumAggDataPoint = sync.Pool{
		New: func() any {
			return &SumAggDataPoint{}
		},
	}
)

func NewSumAggDataPoint() *SumAggDataPoint {
	if !UseProtoPooling.IsEnabled() {
		return &SumAggDataPoint{}
	}
	return protoPoolSumAggDataPoint.Get().(*SumAggDataPoint)
}

func DeleteSumAggDataPoint(orig *SumAggDataPoint, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.Attributes {
		DeleteKeyValue(&orig.Attributes[i], false)
	}
	for i := range orig.Exemplars {
		DeleteExemplar(&orig.Exemplars[i], false)
	}

	orig.Reset()
	if nullable {
		protoPoolSumAggDataPoint.Put(orig)
	}
}

func CopySumAggDataPoint(dest, src *SumAggDataPoint) *SumAggDataPoint {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewSumAggDataPoint()
	}
	dest.Attributes = CopyKeyValueSlice(dest.Attributes, src.Attributes)

	dest.SeriesID = src.SeriesID

	dest.StartTimeUnixNano = src.StartTimeUnixNano

	dest.TimeUnixNano = src.TimeUnixNano

	dest.Sketch = src.Sketch

	dest.Encoding = src.Encoding

	dest.Exemplars = CopyExemplarSlice(dest.Exemplars, src.Exemplars)

	dest.Flags = src.Flags

	return dest
}

func CopySumAggDataPointSlice(dest, src []SumAggDataPoint) []SumAggDataPoint {
	var newDest []SumAggDataPoint
	if cap(dest) < len(src) {
		newDest = make([]SumAggDataPoint, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteSumAggDataPoint(&dest[i], false)
		}
	}
	for i := range src {
		CopySumAggDataPoint(&newDest[i], &src[i])
	}
	return newDest
}

func CopySumAggDataPointPtrSlice(dest, src []*SumAggDataPoint) []*SumAggDataPoint {
	var newDest []*SumAggDataPoint
	if cap(dest) < len(src) {
		newDest = make([]*SumAggDataPoint, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewSumAggDataPoint()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteSumAggDataPoint(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewSumAggDataPoint()
		}
	}
	for i := range src {
		CopySumAggDataPoint(newDest[i], src[i])
	}
	return newDest
}

func (orig *SumAggDataPoint) Reset() {
	*orig = SumAggDataPoint{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *SumAggDataPoint) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.Attributes) > 0 {
		dest.WriteObjectField("attributes")
		dest.WriteArrayStart()
		orig.Attributes[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Attributes); i++ {
			dest.WriteMore()
			orig.Attributes[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.SeriesID != uint64(0) {
		dest.WriteObjectField("seriesID")
		dest.WriteUint64(orig.SeriesID)
	}
	if orig.StartTimeUnixNano != uint64(0) {
		dest.WriteObjectField("startTimeUnixNano")
		dest.WriteUint64(orig.StartTimeUnixNano)
	}
	if orig.TimeUnixNano != uint64(0) {
		dest.WriteObjectField("timeUnixNano")
		dest.WriteUint64(orig.TimeUnixNano)
	}

	if len(orig.Sketch) > 0 {
		dest.WriteObjectField("sketch")
		dest.WriteBytes(orig.Sketch)
	}

	if int32(orig.Encoding) != 0 {
		dest.WriteObjectField("encoding")
		dest.WriteInt32(int32(orig.Encoding))
	}
	if len(orig.Exemplars) > 0 {
		dest.WriteObjectField("exemplars")
		dest.WriteArrayStart()
		orig.Exemplars[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Exemplars); i++ {
			dest.WriteMore()
			orig.Exemplars[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.Flags != uint32(0) {
		dest.WriteObjectField("flags")
		dest.WriteUint32(orig.Flags)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *SumAggDataPoint) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "attributes":
			for iter.ReadArray() {
				orig.Attributes = append(orig.Attributes, KeyValue{})
				orig.Attributes[len(orig.Attributes)-1].UnmarshalJSON(iter)
			}

		case "seriesID", "series_id":
			orig.SeriesID = iter.ReadUint64()
		case "startTimeUnixNano", "start_time_unix_nano":
			orig.StartTimeUnixNano = iter.ReadUint64()
		case "timeUnixNano", "time_unix_nano":
			orig.TimeUnixNano = iter.ReadUint64()
		case "sketch":
			orig.Sketch = iter.ReadBytes()
		case "encoding":
			orig.Encoding = SumAggEncoding(iter.ReadEnumValue(SumAggEncoding_value))
		case "exemplars":
			for iter.ReadArray() {
				orig.Exemplars = append(orig.Exemplars, Exemplar{})
				orig.Exemplars[len(orig.Exemplars)-1].UnmarshalJSON(iter)
			}

		case "flags":
			orig.Flags = iter.ReadUint32()
		default:
			iter.Skip()
		}
	}
}

func (orig *SumAggDataPoint) SizeProto() int {
	var n int
	var l int
	_ = l
	for i := range orig.Attributes {
		l = orig.Attributes[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.SeriesID != 0 {
		n += 2 + proto.Sov(uint64(orig.SeriesID))
	}
	if orig.StartTimeUnixNano != 0 {
		n += 9
	}
	if orig.TimeUnixNano != 0 {
		n += 9
	}
	l = len(orig.Sketch)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Encoding != 0 {
		n += 1 + proto.Sov(uint64(orig.Encoding))
	}
	for i := range orig.Exemplars {
		l = orig.Exemplars[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Flags != 0 {
		n += 1 + proto.Sov(uint64(orig.Flags))
	}
	return n
}

func (orig *SumAggDataPoint) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.Attributes) - 1; i >= 0; i-- {
		l = orig.Attributes[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x4a
	}
	if orig.SeriesID != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.SeriesID))
		pos--
		buf[pos] = 0x1
		pos--
		buf[pos] = 0x80
	}
	if orig.StartTimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.StartTimeUnixNano))
		pos--
		buf[pos] = 0x11
	}
	if orig.TimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.TimeUnixNano))
		pos--
		buf[pos] = 0x19
	}
	l = len(orig.Sketch)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Sketch)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x42
	}
	if orig.Encoding != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Encoding))
		pos--
		buf[pos] = 0x50
	}
	for i := len(orig.Exemplars) - 1; i >= 0; i-- {
		l = orig.Exemplars[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x5a
	}
	if orig.Flags != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Flags))
		pos--
		buf[pos] = 0x78
	}
	return len(buf) - pos
}

func (orig *SumAggDataPoint) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		// If in a group parsing, move to the next tag.
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 9:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Attributes = append(orig.Attributes, KeyValue{})
			err = orig.Attributes[len(orig.Attributes)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 16:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field SeriesID", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.SeriesID = uint64(num)

		case 2:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}

			orig.StartTimeUnixNano = uint64(num)

		case 3:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}

			orig.TimeUnixNano = uint64(num)

		case 8:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sketch", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.Sketch = make([]byte, length)
				copy(orig.Sketch, buf[startPos:pos])
			}

		case 10:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.Encoding = SumAggEncoding(num)

		case 11:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Exemplars", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Exemplars = append(orig.Exemplars, Exemplar{})
			err = orig.Exemplars[len(orig.Exemplars)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 15:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.Flags = uint32(num)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestSumAggDataPoint() *SumAggDataPoint {
	orig := NewSumAggDataPoint()
	orig.Attributes = []KeyValue{{}, *GenTestKeyValue()}
	orig.SeriesID = uint64(13)
	orig.StartTimeUnixNano = uint64(13)
	orig.TimeUnixNano = uint64(13)
	orig.Sketch = []byte{1, 2, 3}
	orig.Encoding = SumAggEncoding(13)
	orig.Exemplars = []Exemplar{{}, *GenTestExemplar()}
	orig.Flags = uint32(13)
	return orig
}

func GenTestSumAggDataPointPtrSlice() []*SumAggDataPoint {
	orig := make([]*SumAggDataPoint, 5)
	orig[0] = NewSumAggDataPoint()
	orig[1] = GenTestSumAggDataPoint()
	orig[2] = NewSumAggDataPoint()
	orig[3] = GenTestSumAggDataPoint()
	orig[4] = NewSumAggDataPoint()
	return orig
}

func GenTestSumAggDataPointSlice() []SumAggDataPoint {
	orig := make([]SumAggDataPoint, 5)
	orig[1] = *GenTestSumAggDataPoint()
	orig[3] = *GenTestSumAggDataPoint()
	return orig
}
