// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// CountMinSketch represents the type of a metric encoded using the Count-Min Sketch frequency estimation algorithm.
type CountMinSketch struct {
	DataPoints             []*CountMinSketchDataPoint
	AggregationTemporality AggregationTemporality
	Rows                   int32
	Cols                   int32
}

var (
	protoPoolCountMinSketch = sync.Pool{
		New: func() any {
			return &CountMinSketch{}
		},
	}
)

func NewCountMinSketch() *CountMinSketch {
	if !UseProtoPooling.IsEnabled() {
		return &CountMinSketch{}
	}
	return protoPoolCountMinSketch.Get().(*CountMinSketch)
}

func DeleteCountMinSketch(orig *CountMinSketch, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.DataPoints {
		DeleteCountMinSketchDataPoint(orig.DataPoints[i], true)
	}

	orig.Reset()
	if nullable {
		protoPoolCountMinSketch.Put(orig)
	}
}

func CopyCountMinSketch(dest, src *CountMinSketch) *CountMinSketch {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewCountMinSketch()
	}
	dest.DataPoints = CopyCountMinSketchDataPointPtrSlice(dest.DataPoints, src.DataPoints)

	dest.AggregationTemporality = src.AggregationTemporality

	dest.Rows = src.Rows

	dest.Cols = src.Cols

	return dest
}

func CopyCountMinSketchSlice(dest, src []CountMinSketch) []CountMinSketch {
	var newDest []CountMinSketch
	if cap(dest) < len(src) {
		newDest = make([]CountMinSketch, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteCountMinSketch(&dest[i], false)
		}
	}
	for i := range src {
		CopyCountMinSketch(&newDest[i], &src[i])
	}
	return newDest
}

func CopyCountMinSketchPtrSlice(dest, src []*CountMinSketch) []*CountMinSketch {
	var newDest []*CountMinSketch
	if cap(dest) < len(src) {
		newDest = make([]*CountMinSketch, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewCountMinSketch()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteCountMinSketch(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewCountMinSketch()
		}
	}
	for i := range src {
		CopyCountMinSketch(newDest[i], src[i])
	}
	return newDest
}

func (orig *CountMinSketch) Reset() {
	*orig = CountMinSketch{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *CountMinSketch) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.DataPoints) > 0 {
		dest.WriteObjectField("dataPoints")
		dest.WriteArrayStart()
		orig.DataPoints[0].MarshalJSON(dest)
		for i := 1; i < len(orig.DataPoints); i++ {
			dest.WriteMore()
			orig.DataPoints[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}

	if int32(orig.AggregationTemporality) != 0 {
		dest.WriteObjectField("aggregationTemporality")
		dest.WriteInt32(int32(orig.AggregationTemporality))
	}
	if orig.Rows != int32(0) {
		dest.WriteObjectField("rows")
		dest.WriteInt32(orig.Rows)
	}
	if orig.Cols != int32(0) {
		dest.WriteObjectField("cols")
		dest.WriteInt32(orig.Cols)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *CountMinSketch) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "dataPoints", "data_points":
			for iter.ReadArray() {
				orig.DataPoints = append(orig.DataPoints, NewCountMinSketchDataPoint())
				orig.DataPoints[len(orig.DataPoints)-1].UnmarshalJSON(iter)
			}

		case "aggregationTemporality", "aggregation_temporality":
			orig.AggregationTemporality = AggregationTemporality(iter.ReadEnumValue(AggregationTemporality_value))
		case "rows":
			orig.Rows = iter.ReadInt32()
		case "cols":
			orig.Cols = iter.ReadInt32()
		default:
			iter.Skip()
		}
	}
}

func (orig *CountMinSketch) SizeProto() int {
	var n int
	var l int
	_ = l
	for i := range orig.DataPoints {
		l = orig.DataPoints[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.AggregationTemporality != 0 {
		n += 1 + proto.Sov(uint64(orig.AggregationTemporality))
	}
	if orig.Rows != 0 {
		n += 1 + proto.Sov(uint64(orig.Rows))
	}
	if orig.Cols != 0 {
		n += 1 + proto.Sov(uint64(orig.Cols))
	}
	return n
}

func (orig *CountMinSketch) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.DataPoints) - 1; i >= 0; i-- {
		l = orig.DataPoints[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	if orig.AggregationTemporality != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.AggregationTemporality))
		pos--
		buf[pos] = 0x10
	}
	if orig.Rows != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Rows))
		pos--
		buf[pos] = 0x18
	}
	if orig.Cols != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Cols))
		pos--
		buf[pos] = 0x20
	}
	return len(buf) - pos
}

func (orig *CountMinSketch) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		// If in a group parsing, move to the next tag.
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPoints", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.DataPoints = append(orig.DataPoints, NewCountMinSketchDataPoint())
			err = orig.DataPoints[len(orig.DataPoints)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationTemporality", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.AggregationTemporality = AggregationTemporality(num)

		case 3:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.Rows = int32(num)

		case 4:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Cols", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.Cols = int32(num)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestCountMinSketch() *CountMinSketch {
	orig := NewCountMinSketch()
	orig.DataPoints = []*CountMinSketchDataPoint{{}, GenTestCountMinSketchDataPoint()}
	orig.AggregationTemporality = AggregationTemporality(13)
	orig.Rows = int32(13)
	orig.Cols = int32(13)
	return orig
}

func GenTestCountMinSketchPtrSlice() []*CountMinSketch {
	orig := make([]*CountMinSketch, 5)
	orig[0] = NewCountMinSketch()
	orig[1] = GenTestCountMinSketch()
	orig[2] = NewCountMinSketch()
	orig[3] = GenTestCountMinSketch()
	orig[4] = NewCountMinSketch()
	return orig
}

func GenTestCountMinSketchSlice() []CountMinSketch {
	orig := make([]CountMinSketch, 5)
	orig[1] = *GenTestCountMinSketch()
	orig[3] = *GenTestCountMinSketch()
	return orig
}
