// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"encoding/binary"
	"fmt"
	"math"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

func (m *DDSketchDataPoint) GetSum() any {
	if m != nil {
		return m.Sum
	}
	return nil
}

type DDSketchDataPoint_SumAsDouble struct {
	SumAsDouble float64
}

func (m *DDSketchDataPoint) GetSumAsDouble() float64 {
	if v, ok := m.GetSum().(*DDSketchDataPoint_SumAsDouble); ok {
		return v.SumAsDouble
	}
	return float64(0)
}

type DDSketchDataPoint_SumAsInt struct {
	SumAsInt int64
}

func (m *DDSketchDataPoint) GetSumAsInt() int64 {
	if v, ok := m.GetSum().(*DDSketchDataPoint_SumAsInt); ok {
		return v.SumAsInt
	}
	return int64(0)
}

func (m *DDSketchDataPoint) GetMin() any {
	if m != nil {
		return m.Min
	}
	return nil
}

type DDSketchDataPoint_MinAsDouble struct {
	MinAsDouble float64
}

func (m *DDSketchDataPoint) GetMinAsDouble() float64 {
	if v, ok := m.GetMin().(*DDSketchDataPoint_MinAsDouble); ok {
		return v.MinAsDouble
	}
	return float64(0)
}

type DDSketchDataPoint_MinAsInt struct {
	MinAsInt int64
}

func (m *DDSketchDataPoint) GetMinAsInt() int64 {
	if v, ok := m.GetMin().(*DDSketchDataPoint_MinAsInt); ok {
		return v.MinAsInt
	}
	return int64(0)
}

func (m *DDSketchDataPoint) GetMax() any {
	if m != nil {
		return m.Max
	}
	return nil
}

type DDSketchDataPoint_MaxAsDouble struct {
	MaxAsDouble float64
}

func (m *DDSketchDataPoint) GetMaxAsDouble() float64 {
	if v, ok := m.GetMax().(*DDSketchDataPoint_MaxAsDouble); ok {
		return v.MaxAsDouble
	}
	return float64(0)
}

type DDSketchDataPoint_MaxAsInt struct {
	MaxAsInt int64
}

func (m *DDSketchDataPoint) GetMaxAsInt() int64 {
	if v, ok := m.GetMax().(*DDSketchDataPoint_MaxAsInt); ok {
		return v.MaxAsInt
	}
	return int64(0)
}

// DDSketchDataPoint is a single data point that encodes a distribution using the DDSketch format.
type DDSketchDataPoint struct {
	Attributes        []KeyValue
	StartTimeUnixNano uint64
	TimeUnixNano      uint64
	Count             uint64
	Sum               any
	Min               any
	Max               any
	Sketch            []byte
	Encoding          DDSketchEncoding
	Exemplars         []Exemplar
	Flags             uint32
}

var (
	protoPoolDDSketchDataPoint = sync.Pool{
		New: func() any {
			return &DDSketchDataPoint{}
		},
	}

	ProtoPoolDDSketchDataPoint_SumAsDouble = sync.Pool{
		New: func() any {
			return &DDSketchDataPoint_SumAsDouble{}
		},
	}

	ProtoPoolDDSketchDataPoint_SumAsInt = sync.Pool{
		New: func() any {
			return &DDSketchDataPoint_SumAsInt{}
		},
	}

	ProtoPoolDDSketchDataPoint_MinAsDouble = sync.Pool{
		New: func() any {
			return &DDSketchDataPoint_MinAsDouble{}
		},
	}

	ProtoPoolDDSketchDataPoint_MinAsInt = sync.Pool{
		New: func() any {
			return &DDSketchDataPoint_MinAsInt{}
		},
	}

	ProtoPoolDDSketchDataPoint_MaxAsDouble = sync.Pool{
		New: func() any {
			return &DDSketchDataPoint_MaxAsDouble{}
		},
	}

	ProtoPoolDDSketchDataPoint_MaxAsInt = sync.Pool{
		New: func() any {
			return &DDSketchDataPoint_MaxAsInt{}
		},
	}
)

func NewDDSketchDataPoint() *DDSketchDataPoint {
	if !UseProtoPooling.IsEnabled() {
		return &DDSketchDataPoint{}
	}
	return protoPoolDDSketchDataPoint.Get().(*DDSketchDataPoint)
}

func DeleteDDSketchDataPoint(orig *DDSketchDataPoint, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.Attributes {
		DeleteKeyValue(&orig.Attributes[i], false)
	}
	switch ov := orig.Sum.(type) {
	case *DDSketchDataPoint_SumAsDouble:
		if UseProtoPooling.IsEnabled() {
			ov.SumAsDouble = float64(0)
			ProtoPoolDDSketchDataPoint_SumAsDouble.Put(ov)
		}
	case *DDSketchDataPoint_SumAsInt:
		if UseProtoPooling.IsEnabled() {
			ov.SumAsInt = int64(0)
			ProtoPoolDDSketchDataPoint_SumAsInt.Put(ov)
		}

	}
	switch ov := orig.Min.(type) {
	case *DDSketchDataPoint_MinAsDouble:
		if UseProtoPooling.IsEnabled() {
			ov.MinAsDouble = float64(0)
			ProtoPoolDDSketchDataPoint_MinAsDouble.Put(ov)
		}
	case *DDSketchDataPoint_MinAsInt:
		if UseProtoPooling.IsEnabled() {
			ov.MinAsInt = int64(0)
			ProtoPoolDDSketchDataPoint_MinAsInt.Put(ov)
		}

	}
	switch ov := orig.Max.(type) {
	case *DDSketchDataPoint_MaxAsDouble:
		if UseProtoPooling.IsEnabled() {
			ov.MaxAsDouble = float64(0)
			ProtoPoolDDSketchDataPoint_MaxAsDouble.Put(ov)
		}
	case *DDSketchDataPoint_MaxAsInt:
		if UseProtoPooling.IsEnabled() {
			ov.MaxAsInt = int64(0)
			ProtoPoolDDSketchDataPoint_MaxAsInt.Put(ov)
		}

	}
	for i := range orig.Exemplars {
		DeleteExemplar(&orig.Exemplars[i], false)
	}

	orig.Reset()
	if nullable {
		protoPoolDDSketchDataPoint.Put(orig)
	}
}

func CopyDDSketchDataPoint(dest, src *DDSketchDataPoint) *DDSketchDataPoint {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewDDSketchDataPoint()
	}
	dest.Attributes = CopyKeyValueSlice(dest.Attributes, src.Attributes)

	dest.StartTimeUnixNano = src.StartTimeUnixNano

	dest.TimeUnixNano = src.TimeUnixNano

	dest.Count = src.Count

	switch t := src.Sum.(type) {
	case *DDSketchDataPoint_SumAsDouble:
		var ov *DDSketchDataPoint_SumAsDouble
		if !UseProtoPooling.IsEnabled() {
			ov = &DDSketchDataPoint_SumAsDouble{}
		} else {
			ov = ProtoPoolDDSketchDataPoint_SumAsDouble.Get().(*DDSketchDataPoint_SumAsDouble)
		}
		ov.SumAsDouble = t.SumAsDouble
		dest.Sum = ov
	case *DDSketchDataPoint_SumAsInt:
		var ov *DDSketchDataPoint_SumAsInt
		if !UseProtoPooling.IsEnabled() {
			ov = &DDSketchDataPoint_SumAsInt{}
		} else {
			ov = ProtoPoolDDSketchDataPoint_SumAsInt.Get().(*DDSketchDataPoint_SumAsInt)
		}
		ov.SumAsInt = t.SumAsInt
		dest.Sum = ov
	default:
		dest.Sum = nil
	}
	switch t := src.Min.(type) {
	case *DDSketchDataPoint_MinAsDouble:
		var ov *DDSketchDataPoint_MinAsDouble
		if !UseProtoPooling.IsEnabled() {
			ov = &DDSketchDataPoint_MinAsDouble{}
		} else {
			ov = ProtoPoolDDSketchDataPoint_MinAsDouble.Get().(*DDSketchDataPoint_MinAsDouble)
		}
		ov.MinAsDouble = t.MinAsDouble
		dest.Min = ov
	case *DDSketchDataPoint_MinAsInt:
		var ov *DDSketchDataPoint_MinAsInt
		if !UseProtoPooling.IsEnabled() {
			ov = &DDSketchDataPoint_MinAsInt{}
		} else {
			ov = ProtoPoolDDSketchDataPoint_MinAsInt.Get().(*DDSketchDataPoint_MinAsInt)
		}
		ov.MinAsInt = t.MinAsInt
		dest.Min = ov
	default:
		dest.Min = nil
	}
	switch t := src.Max.(type) {
	case *DDSketchDataPoint_MaxAsDouble:
		var ov *DDSketchDataPoint_MaxAsDouble
		if !UseProtoPooling.IsEnabled() {
			ov = &DDSketchDataPoint_MaxAsDouble{}
		} else {
			ov = ProtoPoolDDSketchDataPoint_MaxAsDouble.Get().(*DDSketchDataPoint_MaxAsDouble)
		}
		ov.MaxAsDouble = t.MaxAsDouble
		dest.Max = ov
	case *DDSketchDataPoint_MaxAsInt:
		var ov *DDSketchDataPoint_MaxAsInt
		if !UseProtoPooling.IsEnabled() {
			ov = &DDSketchDataPoint_MaxAsInt{}
		} else {
			ov = ProtoPoolDDSketchDataPoint_MaxAsInt.Get().(*DDSketchDataPoint_MaxAsInt)
		}
		ov.MaxAsInt = t.MaxAsInt
		dest.Max = ov
	default:
		dest.Max = nil
	}
	dest.Sketch = src.Sketch

	dest.Encoding = src.Encoding

	dest.Exemplars = CopyExemplarSlice(dest.Exemplars, src.Exemplars)

	dest.Flags = src.Flags

	return dest
}

func CopyDDSketchDataPointSlice(dest, src []DDSketchDataPoint) []DDSketchDataPoint {
	var newDest []DDSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]DDSketchDataPoint, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteDDSketchDataPoint(&dest[i], false)
		}
	}
	for i := range src {
		CopyDDSketchDataPoint(&newDest[i], &src[i])
	}
	return newDest
}

func CopyDDSketchDataPointPtrSlice(dest, src []*DDSketchDataPoint) []*DDSketchDataPoint {
	var newDest []*DDSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]*DDSketchDataPoint, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewDDSketchDataPoint()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteDDSketchDataPoint(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewDDSketchDataPoint()
		}
	}
	for i := range src {
		CopyDDSketchDataPoint(newDest[i], src[i])
	}
	return newDest
}

func (orig *DDSketchDataPoint) Reset() {
	*orig = DDSketchDataPoint{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *DDSketchDataPoint) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.Attributes) > 0 {
		dest.WriteObjectField("attributes")
		dest.WriteArrayStart()
		orig.Attributes[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Attributes); i++ {
			dest.WriteMore()
			orig.Attributes[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.StartTimeUnixNano != uint64(0) {
		dest.WriteObjectField("startTimeUnixNano")
		dest.WriteUint64(orig.StartTimeUnixNano)
	}
	if orig.TimeUnixNano != uint64(0) {
		dest.WriteObjectField("timeUnixNano")
		dest.WriteUint64(orig.TimeUnixNano)
	}
	if orig.Count != uint64(0) {
		dest.WriteObjectField("count")
		dest.WriteUint64(orig.Count)
	}
	switch orig := orig.Sum.(type) {
	case *DDSketchDataPoint_SumAsDouble:
		dest.WriteObjectField("sumAsDouble")
		dest.WriteFloat64(orig.SumAsDouble)
	case *DDSketchDataPoint_SumAsInt:
		dest.WriteObjectField("sumAsInt")
		dest.WriteInt64(orig.SumAsInt)
	}
	switch orig := orig.Min.(type) {
	case *DDSketchDataPoint_MinAsDouble:
		dest.WriteObjectField("minAsDouble")
		dest.WriteFloat64(orig.MinAsDouble)
	case *DDSketchDataPoint_MinAsInt:
		dest.WriteObjectField("minAsInt")
		dest.WriteInt64(orig.MinAsInt)
	}
	switch orig := orig.Max.(type) {
	case *DDSketchDataPoint_MaxAsDouble:
		dest.WriteObjectField("maxAsDouble")
		dest.WriteFloat64(orig.MaxAsDouble)
	case *DDSketchDataPoint_MaxAsInt:
		dest.WriteObjectField("maxAsInt")
		dest.WriteInt64(orig.MaxAsInt)
	}

	if len(orig.Sketch) > 0 {
		dest.WriteObjectField("sketch")
		dest.WriteBytes(orig.Sketch)
	}

	if int32(orig.Encoding) != 0 {
		dest.WriteObjectField("encoding")
		dest.WriteInt32(int32(orig.Encoding))
	}
	if len(orig.Exemplars) > 0 {
		dest.WriteObjectField("exemplars")
		dest.WriteArrayStart()
		orig.Exemplars[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Exemplars); i++ {
			dest.WriteMore()
			orig.Exemplars[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.Flags != uint32(0) {
		dest.WriteObjectField("flags")
		dest.WriteUint32(orig.Flags)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *DDSketchDataPoint) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "attributes":
			for iter.ReadArray() {
				orig.Attributes = append(orig.Attributes, KeyValue{})
				orig.Attributes[len(orig.Attributes)-1].UnmarshalJSON(iter)
			}

		case "startTimeUnixNano", "start_time_unix_nano":
			orig.StartTimeUnixNano = iter.ReadUint64()
		case "timeUnixNano", "time_unix_nano":
			orig.TimeUnixNano = iter.ReadUint64()
		case "count":
			orig.Count = iter.ReadUint64()

		case "sumAsDouble", "sum_as_double":
			{
				var ov *DDSketchDataPoint_SumAsDouble
				if !UseProtoPooling.IsEnabled() {
					ov = &DDSketchDataPoint_SumAsDouble{}
				} else {
					ov = ProtoPoolDDSketchDataPoint_SumAsDouble.Get().(*DDSketchDataPoint_SumAsDouble)
				}
				ov.SumAsDouble = iter.ReadFloat64()
				orig.Sum = ov
			}

		case "sumAsInt", "sum_as_int":
			{
				var ov *DDSketchDataPoint_SumAsInt
				if !UseProtoPooling.IsEnabled() {
					ov = &DDSketchDataPoint_SumAsInt{}
				} else {
					ov = ProtoPoolDDSketchDataPoint_SumAsInt.Get().(*DDSketchDataPoint_SumAsInt)
				}
				ov.SumAsInt = iter.ReadInt64()
				orig.Sum = ov
			}

		case "minAsDouble", "min_as_double":
			{
				var ov *DDSketchDataPoint_MinAsDouble
				if !UseProtoPooling.IsEnabled() {
					ov = &DDSketchDataPoint_MinAsDouble{}
				} else {
					ov = ProtoPoolDDSketchDataPoint_MinAsDouble.Get().(*DDSketchDataPoint_MinAsDouble)
				}
				ov.MinAsDouble = iter.ReadFloat64()
				orig.Min = ov
			}

		case "minAsInt", "min_as_int":
			{
				var ov *DDSketchDataPoint_MinAsInt
				if !UseProtoPooling.IsEnabled() {
					ov = &DDSketchDataPoint_MinAsInt{}
				} else {
					ov = ProtoPoolDDSketchDataPoint_MinAsInt.Get().(*DDSketchDataPoint_MinAsInt)
				}
				ov.MinAsInt = iter.ReadInt64()
				orig.Min = ov
			}

		case "maxAsDouble", "max_as_double":
			{
				var ov *DDSketchDataPoint_MaxAsDouble
				if !UseProtoPooling.IsEnabled() {
					ov = &DDSketchDataPoint_MaxAsDouble{}
				} else {
					ov = ProtoPoolDDSketchDataPoint_MaxAsDouble.Get().(*DDSketchDataPoint_MaxAsDouble)
				}
				ov.MaxAsDouble = iter.ReadFloat64()
				orig.Max = ov
			}

		case "maxAsInt", "max_as_int":
			{
				var ov *DDSketchDataPoint_MaxAsInt
				if !UseProtoPooling.IsEnabled() {
					ov = &DDSketchDataPoint_MaxAsInt{}
				} else {
					ov = ProtoPoolDDSketchDataPoint_MaxAsInt.Get().(*DDSketchDataPoint_MaxAsInt)
				}
				ov.MaxAsInt = iter.ReadInt64()
				orig.Max = ov
			}

		case "sketch":
			orig.Sketch = iter.ReadBytes()
		case "encoding":
			orig.Encoding = DDSketchEncoding(iter.ReadEnumValue(DDSketchEncoding_value))
		case "exemplars":
			for iter.ReadArray() {
				orig.Exemplars = append(orig.Exemplars, Exemplar{})
				orig.Exemplars[len(orig.Exemplars)-1].UnmarshalJSON(iter)
			}

		case "flags":
			orig.Flags = iter.ReadUint32()
		default:
			iter.Skip()
		}
	}
}

func (orig *DDSketchDataPoint) SizeProto() int {
	var n int
	var l int
	_ = l
	for i := range orig.Attributes {
		l = orig.Attributes[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.StartTimeUnixNano != 0 {
		n += 9
	}
	if orig.TimeUnixNano != 0 {
		n += 9
	}
	if orig.Count != 0 {
		n += 9
	}
	switch orig := orig.Sum.(type) {
	case nil:
		_ = orig
		break
	case *DDSketchDataPoint_SumAsDouble:
		n += 9
	case *DDSketchDataPoint_SumAsInt:
		n += 9
	}
	switch orig := orig.Min.(type) {
	case nil:
		_ = orig
		break
	case *DDSketchDataPoint_MinAsDouble:
		n += 9
	case *DDSketchDataPoint_MinAsInt:
		n += 9
	}
	switch orig := orig.Max.(type) {
	case nil:
		_ = orig
		break
	case *DDSketchDataPoint_MaxAsDouble:
		n += 9
	case *DDSketchDataPoint_MaxAsInt:
		n += 9
	}
	l = len(orig.Sketch)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Encoding != 0 {
		n += 1 + proto.Sov(uint64(orig.Encoding))
	}
	for i := range orig.Exemplars {
		l = orig.Exemplars[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Flags != 0 {
		n += 1 + proto.Sov(uint64(orig.Flags))
	}
	return n
}

func (orig *DDSketchDataPoint) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.Attributes) - 1; i >= 0; i-- {
		l = orig.Attributes[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x4a
	}
	if orig.StartTimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.StartTimeUnixNano))
		pos--
		buf[pos] = 0x11
	}
	if orig.TimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.TimeUnixNano))
		pos--
		buf[pos] = 0x19
	}
	if orig.Count != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.Count))
		pos--
		buf[pos] = 0x21
	}
	switch orig := orig.Sum.(type) {
	case *DDSketchDataPoint_SumAsDouble:
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.SumAsDouble))
		pos--
		buf[pos] = 0x29

	case *DDSketchDataPoint_SumAsInt:
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.SumAsInt))
		pos--
		buf[pos] = 0x61

	}
	switch orig := orig.Min.(type) {
	case *DDSketchDataPoint_MinAsDouble:
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.MinAsDouble))
		pos--
		buf[pos] = 0x31

	case *DDSketchDataPoint_MinAsInt:
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.MinAsInt))
		pos--
		buf[pos] = 0x69

	}
	switch orig := orig.Max.(type) {
	case *DDSketchDataPoint_MaxAsDouble:
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.MaxAsDouble))
		pos--
		buf[pos] = 0x39

	case *DDSketchDataPoint_MaxAsInt:
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.MaxAsInt))
		pos--
		buf[pos] = 0x71

	}
	l = len(orig.Sketch)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Sketch)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x42
	}
	if orig.Encoding != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Encoding))
		pos--
		buf[pos] = 0x50
	}
	for i := len(orig.Exemplars) - 1; i >= 0; i-- {
		l = orig.Exemplars[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x5a
	}
	if orig.Flags != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Flags))
		pos--
		buf[pos] = 0x78
	}
	return len(buf) - pos
}

func (orig *DDSketchDataPoint) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		// If in a group parsing, move to the next tag.
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 9:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Attributes = append(orig.Attributes, KeyValue{})
			err = orig.Attributes[len(orig.Attributes)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}

			orig.StartTimeUnixNano = uint64(num)

		case 3:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}

			orig.TimeUnixNano = uint64(num)

		case 4:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}

			orig.Count = uint64(num)

		case 5:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field SumAsDouble", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			var ov *DDSketchDataPoint_SumAsDouble
			if !UseProtoPooling.IsEnabled() {
				ov = &DDSketchDataPoint_SumAsDouble{}
			} else {
				ov = ProtoPoolDDSketchDataPoint_SumAsDouble.Get().(*DDSketchDataPoint_SumAsDouble)
			}
			ov.SumAsDouble = math.Float64frombits(num)
			orig.Sum = ov

		case 12:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field SumAsInt", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			var ov *DDSketchDataPoint_SumAsInt
			if !UseProtoPooling.IsEnabled() {
				ov = &DDSketchDataPoint_SumAsInt{}
			} else {
				ov = ProtoPoolDDSketchDataPoint_SumAsInt.Get().(*DDSketchDataPoint_SumAsInt)
			}
			ov.SumAsInt = int64(num)
			orig.Sum = ov

		case 6:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAsDouble", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			var ov *DDSketchDataPoint_MinAsDouble
			if !UseProtoPooling.IsEnabled() {
				ov = &DDSketchDataPoint_MinAsDouble{}
			} else {
				ov = ProtoPoolDDSketchDataPoint_MinAsDouble.Get().(*DDSketchDataPoint_MinAsDouble)
			}
			ov.MinAsDouble = math.Float64frombits(num)
			orig.Min = ov

		case 13:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAsInt", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			var ov *DDSketchDataPoint_MinAsInt
			if !UseProtoPooling.IsEnabled() {
				ov = &DDSketchDataPoint_MinAsInt{}
			} else {
				ov = ProtoPoolDDSketchDataPoint_MinAsInt.Get().(*DDSketchDataPoint_MinAsInt)
			}
			ov.MinAsInt = int64(num)
			orig.Min = ov

		case 7:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAsDouble", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			var ov *DDSketchDataPoint_MaxAsDouble
			if !UseProtoPooling.IsEnabled() {
				ov = &DDSketchDataPoint_MaxAsDouble{}
			} else {
				ov = ProtoPoolDDSketchDataPoint_MaxAsDouble.Get().(*DDSketchDataPoint_MaxAsDouble)
			}
			ov.MaxAsDouble = math.Float64frombits(num)
			orig.Max = ov

		case 14:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAsInt", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			var ov *DDSketchDataPoint_MaxAsInt
			if !UseProtoPooling.IsEnabled() {
				ov = &DDSketchDataPoint_MaxAsInt{}
			} else {
				ov = ProtoPoolDDSketchDataPoint_MaxAsInt.Get().(*DDSketchDataPoint_MaxAsInt)
			}
			ov.MaxAsInt = int64(num)
			orig.Max = ov

		case 8:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sketch", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.Sketch = make([]byte, length)
				copy(orig.Sketch, buf[startPos:pos])
			}

		case 10:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.Encoding = DDSketchEncoding(num)

		case 11:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Exemplars", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Exemplars = append(orig.Exemplars, Exemplar{})
			err = orig.Exemplars[len(orig.Exemplars)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 15:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.Flags = uint32(num)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestDDSketchDataPoint() *DDSketchDataPoint {
	orig := NewDDSketchDataPoint()
	orig.Attributes = []KeyValue{{}, *GenTestKeyValue()}
	orig.StartTimeUnixNano = uint64(13)
	orig.TimeUnixNano = uint64(13)
	orig.Count = uint64(13)
	orig.Sum = &DDSketchDataPoint_SumAsDouble{SumAsDouble: float64(3.1415926)}
	orig.Min = &DDSketchDataPoint_MinAsDouble{MinAsDouble: float64(3.1415926)}
	orig.Max = &DDSketchDataPoint_MaxAsDouble{MaxAsDouble: float64(3.1415926)}
	orig.Sketch = []byte{1, 2, 3}
	orig.Encoding = DDSketchEncoding(13)
	orig.Exemplars = []Exemplar{{}, *GenTestExemplar()}
	orig.Flags = uint32(13)
	return orig
}

func GenTestDDSketchDataPointPtrSlice() []*DDSketchDataPoint {
	orig := make([]*DDSketchDataPoint, 5)
	orig[0] = NewDDSketchDataPoint()
	orig[1] = GenTestDDSketchDataPoint()
	orig[2] = NewDDSketchDataPoint()
	orig[3] = GenTestDDSketchDataPoint()
	orig[4] = NewDDSketchDataPoint()
	return orig
}

func GenTestDDSketchDataPointSlice() []DDSketchDataPoint {
	orig := make([]DDSketchDataPoint, 5)
	orig[1] = *GenTestDDSketchDataPoint()
	orig[3] = *GenTestDDSketchDataPoint()
	return orig
}
