// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

const (
	SumAggEncoding_SUM_AGG_ENCODING_UNSPECIFIED   = SumAggEncoding(0)
	SumAggEncoding_SUM_AGG_ENCODING_PROTO         = SumAggEncoding(1)
	SumAggEncoding_SUM_AGG_ENCODING_PROTO_DELTA   = SumAggEncoding(2)
	SumAggEncoding_SUM_AGG_ENCODING_MSGPACK       = SumAggEncoding(3)
	SumAggEncoding_SUM_AGG_ENCODING_MSGPACK_DELTA = SumAggEncoding(4)
)

// SumAggEncoding identifies how the SumAgg payload bytes are encoded.
type SumAggEncoding int32

var SumAggEncoding_name = map[int32]string{
	0: "SUM_AGG_ENCODING_UNSPECIFIED",
	1: "SUM_AGG_ENCODING_PROTO",
	2: "SUM_AGG_ENCODING_PROTO_DELTA",
	3: "SUM_AGG_ENCODING_MSGPACK",
	4: "SUM_AGG_ENCODING_MSGPACK_DELTA",
}

var SumAggEncoding_value = map[string]int32{
	"SUM_AGG_ENCODING_UNSPECIFIED":   0,
	"SUM_AGG_ENCODING_PROTO":         1,
	"SUM_AGG_ENCODING_PROTO_DELTA":   2,
	"SUM_AGG_ENCODING_MSGPACK":       3,
	"SUM_AGG_ENCODING_MSGPACK_DELTA": 4,
}
