// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

const (
	KLLSketchEncoding_KLL_SKETCH_ENCODING_UNSPECIFIED = KLLSketchEncoding(0)
	KLLSketchEncoding_KLL_SKETCH_ENCODING_PROTO       = KLLSketchEncoding(1)
)

// KLLSketchEncoding identifies how the KLL sketch payload bytes are encoded.
type KLLSketchEncoding int32

var KLLSketchEncoding_name = map[int32]string{
	0: "KLL_SKETCH_ENCODING_UNSPECIFIED",
	1: "KLL_SKETCH_ENCODING_PROTO",
}

var KLLSketchEncoding_value = map[string]int32{
	"KLL_SKETCH_ENCODING_UNSPECIFIED": 0,
	"KLL_SKETCH_ENCODING_PROTO":       1,
}
