// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyDDSketch(t *testing.T) {
	for name, src := range genTestEncodingValuesDDSketch() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewDDSketch()
				CopyDDSketch(dest, src)
				assert.Equal(t, src, dest)
				CopyDDSketch(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyDDSketchSlice(t *testing.T) {
	src := []DDSketch{}
	dest := []DDSketch{}
	// Test CopyTo empty
	dest = CopyDDSketchSlice(dest, src)
	assert.Equal(t, []DDSketch{}, dest)

	// Test CopyTo larger slice
	src = GenTestDDSketchSlice()
	dest = CopyDDSketchSlice(dest, src)
	assert.Equal(t, GenTestDDSketchSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyDDSketchSlice(dest, src)
	assert.Equal(t, GenTestDDSketchSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyDDSketchSlice(dest, []DDSketch{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyDDSketchSlice(dest, src)
	assert.Equal(t, GenTestDDSketchSlice(), dest)
}

func TestCopyDDSketchPtrSlice(t *testing.T) {
	src := []*DDSketch{}
	dest := []*DDSketch{}
	// Test CopyTo empty
	dest = CopyDDSketchPtrSlice(dest, src)
	assert.Equal(t, []*DDSketch{}, dest)

	// Test CopyTo larger slice
	src = GenTestDDSketchPtrSlice()
	dest = CopyDDSketchPtrSlice(dest, src)
	assert.Equal(t, GenTestDDSketchPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyDDSketchPtrSlice(dest, src)
	assert.Equal(t, GenTestDDSketchPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyDDSketchPtrSlice(dest, []*DDSketch{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyDDSketchPtrSlice(dest, src)
	assert.Equal(t, GenTestDDSketchPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONDDSketchUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewDDSketch()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewDDSketch(), dest)
}

func TestMarshalAndUnmarshalJSONDDSketch(t *testing.T) {
	for name, src := range genTestEncodingValuesDDSketch() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewDDSketch()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteDDSketch(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoDDSketchFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesDDSketch() {
		t.Run(name, func(t *testing.T) {
			dest := NewDDSketch()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoDDSketchUnknown(t *testing.T) {
	dest := NewDDSketch()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewDDSketch(), dest)
}

func TestMarshalAndUnmarshalProtoDDSketch(t *testing.T) {
	for name, src := range genTestEncodingValuesDDSketch() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewDDSketch()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteDDSketch(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufDDSketch(t *testing.T) {
	for name, src := range genTestEncodingValuesDDSketch() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.DDSketch{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewDDSketch()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesDDSketch() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                          {0x02},
		"DataPoints/wrong_wire_type":             {0xc},
		"DataPoints/missing_value":               {0xa},
		"AggregationTemporality/wrong_wire_type": {0x14},
		"AggregationTemporality/missing_value":   {0x10},
	}
}

func genTestEncodingValuesDDSketch() map[string]*DDSketch {
	return map[string]*DDSketch{
		"empty":                       NewDDSketch(),
		"DataPoints/test":             {DataPoints: []*DDSketchDataPoint{{}, GenTestDDSketchDataPoint()}},
		"AggregationTemporality/test": {AggregationTemporality: AggregationTemporality(13)},
	}
}
