// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// SeriesAssignment communicates collector-assigned series IDs.
type SeriesAssignment struct {
	ResourceKey           string
	ScopeKey              string
	MetricName            string
	MetricType            string
	AttributesFingerprint []byte
	SeriesID              uint64
}

var (
	protoPoolSeriesAssignment = sync.Pool{
		New: func() any {
			return &SeriesAssignment{}
		},
	}
)

func NewSeriesAssignment() *SeriesAssignment {
	if !UseProtoPooling.IsEnabled() {
		return &SeriesAssignment{}
	}
	return protoPoolSeriesAssignment.Get().(*SeriesAssignment)
}

func DeleteSeriesAssignment(orig *SeriesAssignment, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	orig.Reset()
	if nullable {
		protoPoolSeriesAssignment.Put(orig)
	}
}

func CopySeriesAssignment(dest, src *SeriesAssignment) *SeriesAssignment {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewSeriesAssignment()
	}
	dest.ResourceKey = src.ResourceKey

	dest.ScopeKey = src.ScopeKey

	dest.MetricName = src.MetricName

	dest.MetricType = src.MetricType

	dest.AttributesFingerprint = src.AttributesFingerprint

	dest.SeriesID = src.SeriesID

	return dest
}

func CopySeriesAssignmentSlice(dest, src []SeriesAssignment) []SeriesAssignment {
	var newDest []SeriesAssignment
	if cap(dest) < len(src) {
		newDest = make([]SeriesAssignment, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteSeriesAssignment(&dest[i], false)
		}
	}
	for i := range src {
		CopySeriesAssignment(&newDest[i], &src[i])
	}
	return newDest
}

func CopySeriesAssignmentPtrSlice(dest, src []*SeriesAssignment) []*SeriesAssignment {
	var newDest []*SeriesAssignment
	if cap(dest) < len(src) {
		newDest = make([]*SeriesAssignment, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewSeriesAssignment()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteSeriesAssignment(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewSeriesAssignment()
		}
	}
	for i := range src {
		CopySeriesAssignment(newDest[i], src[i])
	}
	return newDest
}

func (orig *SeriesAssignment) Reset() {
	*orig = SeriesAssignment{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *SeriesAssignment) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if orig.ResourceKey != "" {
		dest.WriteObjectField("resourceKey")
		dest.WriteString(orig.ResourceKey)
	}
	if orig.ScopeKey != "" {
		dest.WriteObjectField("scopeKey")
		dest.WriteString(orig.ScopeKey)
	}
	if orig.MetricName != "" {
		dest.WriteObjectField("metricName")
		dest.WriteString(orig.MetricName)
	}
	if orig.MetricType != "" {
		dest.WriteObjectField("metricType")
		dest.WriteString(orig.MetricType)
	}

	if len(orig.AttributesFingerprint) > 0 {
		dest.WriteObjectField("attributesFingerprint")
		dest.WriteBytes(orig.AttributesFingerprint)
	}
	if orig.SeriesID != uint64(0) {
		dest.WriteObjectField("seriesID")
		dest.WriteUint64(orig.SeriesID)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *SeriesAssignment) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "resourceKey", "resource_key":
			orig.ResourceKey = iter.ReadString()
		case "scopeKey", "scope_key":
			orig.ScopeKey = iter.ReadString()
		case "metricName", "metric_name":
			orig.MetricName = iter.ReadString()
		case "metricType", "metric_type":
			orig.MetricType = iter.ReadString()
		case "attributesFingerprint", "attributes_fingerprint":
			orig.AttributesFingerprint = iter.ReadBytes()
		case "seriesID", "series_id":
			orig.SeriesID = iter.ReadUint64()
		default:
			iter.Skip()
		}
	}
}

func (orig *SeriesAssignment) SizeProto() int {
	var n int
	var l int
	_ = l
	l = len(orig.ResourceKey)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	l = len(orig.ScopeKey)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	l = len(orig.MetricName)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	l = len(orig.MetricType)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	l = len(orig.AttributesFingerprint)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.SeriesID != 0 {
		n += 1 + proto.Sov(uint64(orig.SeriesID))
	}
	return n
}

func (orig *SeriesAssignment) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	l = len(orig.ResourceKey)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.ResourceKey)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	l = len(orig.ScopeKey)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.ScopeKey)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x12
	}
	l = len(orig.MetricName)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.MetricName)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x1a
	}
	l = len(orig.MetricType)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.MetricType)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x22
	}
	l = len(orig.AttributesFingerprint)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.AttributesFingerprint)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x2a
	}
	if orig.SeriesID != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.SeriesID))
		pos--
		buf[pos] = 0x30
	}
	return len(buf) - pos
}

func (orig *SeriesAssignment) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		// If in a group parsing, move to the next tag.
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceKey", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.ResourceKey = string(buf[startPos:pos])

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopeKey", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.ScopeKey = string(buf[startPos:pos])

		case 3:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field MetricName", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.MetricName = string(buf[startPos:pos])

		case 4:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field MetricType", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.MetricType = string(buf[startPos:pos])

		case 5:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field AttributesFingerprint", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.AttributesFingerprint = make([]byte, length)
				copy(orig.AttributesFingerprint, buf[startPos:pos])
			}

		case 6:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field SeriesID", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.SeriesID = uint64(num)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestSeriesAssignment() *SeriesAssignment {
	orig := NewSeriesAssignment()
	orig.ResourceKey = "test_resourcekey"
	orig.ScopeKey = "test_scopekey"
	orig.MetricName = "test_metricname"
	orig.MetricType = "test_metrictype"
	orig.AttributesFingerprint = []byte{1, 2, 3}
	orig.SeriesID = uint64(13)
	return orig
}

func GenTestSeriesAssignmentPtrSlice() []*SeriesAssignment {
	orig := make([]*SeriesAssignment, 5)
	orig[0] = NewSeriesAssignment()
	orig[1] = GenTestSeriesAssignment()
	orig[2] = NewSeriesAssignment()
	orig[3] = GenTestSeriesAssignment()
	orig[4] = NewSeriesAssignment()
	return orig
}

func GenTestSeriesAssignmentSlice() []SeriesAssignment {
	orig := make([]SeriesAssignment, 5)
	orig[1] = *GenTestSeriesAssignment()
	orig[3] = *GenTestSeriesAssignment()
	return orig
}
