// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopySumAggDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesSumAggDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewSumAggDataPoint()
				CopySumAggDataPoint(dest, src)
				assert.Equal(t, src, dest)
				CopySumAggDataPoint(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopySumAggDataPointSlice(t *testing.T) {
	src := []SumAggDataPoint{}
	dest := []SumAggDataPoint{}
	// Test CopyTo empty
	dest = CopySumAggDataPointSlice(dest, src)
	assert.Equal(t, []SumAggDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestSumAggDataPointSlice()
	dest = CopySumAggDataPointSlice(dest, src)
	assert.Equal(t, GenTestSumAggDataPointSlice(), dest)

	// Test CopyTo same size slice
	dest = CopySumAggDataPointSlice(dest, src)
	assert.Equal(t, GenTestSumAggDataPointSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopySumAggDataPointSlice(dest, []SumAggDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopySumAggDataPointSlice(dest, src)
	assert.Equal(t, GenTestSumAggDataPointSlice(), dest)
}

func TestCopySumAggDataPointPtrSlice(t *testing.T) {
	src := []*SumAggDataPoint{}
	dest := []*SumAggDataPoint{}
	// Test CopyTo empty
	dest = CopySumAggDataPointPtrSlice(dest, src)
	assert.Equal(t, []*SumAggDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestSumAggDataPointPtrSlice()
	dest = CopySumAggDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestSumAggDataPointPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopySumAggDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestSumAggDataPointPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopySumAggDataPointPtrSlice(dest, []*SumAggDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopySumAggDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestSumAggDataPointPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONSumAggDataPointUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewSumAggDataPoint()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewSumAggDataPoint(), dest)
}

func TestMarshalAndUnmarshalJSONSumAggDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesSumAggDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewSumAggDataPoint()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteSumAggDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoSumAggDataPointFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesSumAggDataPoint() {
		t.Run(name, func(t *testing.T) {
			dest := NewSumAggDataPoint()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoSumAggDataPointUnknown(t *testing.T) {
	dest := NewSumAggDataPoint()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewSumAggDataPoint(), dest)
}

func TestMarshalAndUnmarshalProtoSumAggDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesSumAggDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewSumAggDataPoint()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteSumAggDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufSumAggDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesSumAggDataPoint() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.SumAggDataPoint{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewSumAggDataPoint()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesSumAggDataPoint() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                     {0x02},
		"Attributes/wrong_wire_type":        {0x4c},
		"Attributes/missing_value":          {0x4a},
		"SeriesID/wrong_wire_type":          {0x84, 0x1},
		"SeriesID/missing_value":            {0x80, 0x1},
		"StartTimeUnixNano/wrong_wire_type": {0x14},
		"StartTimeUnixNano/missing_value":   {0x11},
		"TimeUnixNano/wrong_wire_type":      {0x1c},
		"TimeUnixNano/missing_value":        {0x19},
		"Sketch/wrong_wire_type":            {0x44},
		"Sketch/missing_value":              {0x42},
		"Encoding/wrong_wire_type":          {0x54},
		"Encoding/missing_value":            {0x50},
		"Exemplars/wrong_wire_type":         {0x5c},
		"Exemplars/missing_value":           {0x5a},
		"Flags/wrong_wire_type":             {0x7c},
		"Flags/missing_value":               {0x78},
	}
}

func genTestEncodingValuesSumAggDataPoint() map[string]*SumAggDataPoint {
	return map[string]*SumAggDataPoint{
		"empty":                  NewSumAggDataPoint(),
		"Attributes/test":        {Attributes: []KeyValue{{}, *GenTestKeyValue()}},
		"SeriesID/test":          {SeriesID: uint64(13)},
		"StartTimeUnixNano/test": {StartTimeUnixNano: uint64(13)},
		"TimeUnixNano/test":      {TimeUnixNano: uint64(13)},
		"Sketch/test":            {Sketch: []byte{1, 2, 3}},
		"Encoding/test":          {Encoding: SumAggEncoding(13)},
		"Exemplars/test":         {Exemplars: []Exemplar{{}, *GenTestExemplar()}},
		"Flags/test":             {Flags: uint32(13)},
	}
}
