// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

const (
	HLLSketchEncoding_HLL_SKETCH_ENCODING_UNSPECIFIED = HLLSketchEncoding(0)
	HLLSketchEncoding_HLL_SKETCH_ENCODING_BINARY      = HLLSketchEncoding(1)
)

// HLLSketchEncoding identifies how the HLL sketch payload bytes are encoded.
type HLLSketchEncoding int32

var HLLSketchEncoding_name = map[int32]string{
	0: "HLL_SKETCH_ENCODING_UNSPECIFIED",
	1: "HLL_SKETCH_ENCODING_BINARY",
}

var HLLSketchEncoding_value = map[string]int32{
	"HLL_SKETCH_ENCODING_UNSPECIFIED": 0,
	"HLL_SKETCH_ENCODING_BINARY":      1,
}
