// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

const (
	CountSketchEncoding_COUNT_SKETCH_ENCODING_UNSPECIFIED = CountSketchEncoding(0)
	CountSketchEncoding_COUNT_SKETCH_ENCODING_GOB         = CountSketchEncoding(1)
)

// CountSketchEncoding identifies how the CountSketch payload bytes are encoded.
type CountSketchEncoding int32

var CountSketchEncoding_name = map[int32]string{
	0: "COUNT_SKETCH_ENCODING_UNSPECIFIED",
	1: "COUNT_SKETCH_ENCODING_GOB",
}

var CountSketchEncoding_value = map[string]int32{
	"COUNT_SKETCH_ENCODING_UNSPECIFIED": 0,
	"COUNT_SKETCH_ENCODING_GOB":         1,
}
