// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// HLLSketch represents the type of a metric encoded using HyperLogLog cardinality estimation.
type HLLSketch struct {
	DataPoints             []*HLLSketchDataPoint
	AggregationTemporality AggregationTemporality
}

var (
	protoPoolHLLSketch = sync.Pool{
		New: func() any {
			return &HLLSketch{}
		},
	}
)

func NewHLLSketch() *HLLSketch {
	if !UseProtoPooling.IsEnabled() {
		return &HLLSketch{}
	}
	return protoPoolHLLSketch.Get().(*HLLSketch)
}

func DeleteHLLSketch(orig *HLLSketch, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.DataPoints {
		DeleteHLLSketchDataPoint(orig.DataPoints[i], true)
	}

	orig.Reset()
	if nullable {
		protoPoolHLLSketch.Put(orig)
	}
}

func CopyHLLSketch(dest, src *HLLSketch) *HLLSketch {
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewHLLSketch()
	}
	dest.DataPoints = CopyHLLSketchDataPointPtrSlice(dest.DataPoints, src.DataPoints)

	dest.AggregationTemporality = src.AggregationTemporality

	return dest
}

func CopyHLLSketchSlice(dest, src []HLLSketch) []HLLSketch {
	var newDest []HLLSketch
	if cap(dest) < len(src) {
		newDest = make([]HLLSketch, len(src))
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteHLLSketch(&dest[i], false)
		}
	}
	for i := range src {
		CopyHLLSketch(&newDest[i], &src[i])
	}
	return newDest
}

func CopyHLLSketchPtrSlice(dest, src []*HLLSketch) []*HLLSketch {
	var newDest []*HLLSketch
	if cap(dest) < len(src) {
		newDest = make([]*HLLSketch, len(src))
		copy(newDest, dest)
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewHLLSketch()
		}
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteHLLSketch(dest[i], true)
			dest[i] = nil
		}
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewHLLSketch()
		}
	}
	for i := range src {
		CopyHLLSketch(newDest[i], src[i])
	}
	return newDest
}

func (orig *HLLSketch) Reset() {
	*orig = HLLSketch{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *HLLSketch) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.DataPoints) > 0 {
		dest.WriteObjectField("dataPoints")
		dest.WriteArrayStart()
		orig.DataPoints[0].MarshalJSON(dest)
		for i := 1; i < len(orig.DataPoints); i++ {
			dest.WriteMore()
			orig.DataPoints[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}

	if int32(orig.AggregationTemporality) != 0 {
		dest.WriteObjectField("aggregationTemporality")
		dest.WriteInt32(int32(orig.AggregationTemporality))
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *HLLSketch) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "dataPoints", "data_points":
			for iter.ReadArray() {
				orig.DataPoints = append(orig.DataPoints, NewHLLSketchDataPoint())
				orig.DataPoints[len(orig.DataPoints)-1].UnmarshalJSON(iter)
			}

		case "aggregationTemporality", "aggregation_temporality":
			orig.AggregationTemporality = AggregationTemporality(iter.ReadEnumValue(AggregationTemporality_value))
		default:
			iter.Skip()
		}
	}
}

func (orig *HLLSketch) SizeProto() int {
	var n int
	var l int
	_ = l
	for i := range orig.DataPoints {
		l = orig.DataPoints[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.AggregationTemporality != 0 {
		n += 1 + proto.Sov(uint64(orig.AggregationTemporality))
	}
	return n
}

func (orig *HLLSketch) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.DataPoints) - 1; i >= 0; i-- {
		l = orig.DataPoints[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	if orig.AggregationTemporality != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.AggregationTemporality))
		pos--
		buf[pos] = 0x10
	}
	return len(buf) - pos
}

func (orig *HLLSketch) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPoints", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.DataPoints = append(orig.DataPoints, NewHLLSketchDataPoint())
			err = orig.DataPoints[len(orig.DataPoints)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregationTemporality", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}

			orig.AggregationTemporality = AggregationTemporality(num)
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestHLLSketch() *HLLSketch {
	orig := NewHLLSketch()
	orig.DataPoints = []*HLLSketchDataPoint{{}, GenTestHLLSketchDataPoint()}
	orig.AggregationTemporality = AggregationTemporality(13)
	return orig
}

func GenTestHLLSketchPtrSlice() []*HLLSketch {
	orig := make([]*HLLSketch, 5)
	orig[0] = NewHLLSketch()
	orig[1] = GenTestHLLSketch()
	orig[2] = NewHLLSketch()
	orig[3] = GenTestHLLSketch()
	orig[4] = NewHLLSketch()
	return orig
}

func GenTestHLLSketchSlice() []HLLSketch {
	orig := make([]HLLSketch, 5)
	orig[1] = *GenTestHLLSketch()
	orig[3] = *GenTestHLLSketch()
	return orig
}
