// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyCountMinSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesCountMinSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewCountMinSketchDataPoint()
				CopyCountMinSketchDataPoint(dest, src)
				assert.Equal(t, src, dest)
				CopyCountMinSketchDataPoint(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyCountMinSketchDataPointSlice(t *testing.T) {
	src := []CountMinSketchDataPoint{}
	dest := []CountMinSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyCountMinSketchDataPointSlice(dest, src)
	assert.Equal(t, []CountMinSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestCountMinSketchDataPointSlice()
	dest = CopyCountMinSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchDataPointSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyCountMinSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchDataPointSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyCountMinSketchDataPointSlice(dest, []CountMinSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyCountMinSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchDataPointSlice(), dest)
}

func TestCopyCountMinSketchDataPointPtrSlice(t *testing.T) {
	src := []*CountMinSketchDataPoint{}
	dest := []*CountMinSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyCountMinSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, []*CountMinSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestCountMinSketchDataPointPtrSlice()
	dest = CopyCountMinSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchDataPointPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyCountMinSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchDataPointPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyCountMinSketchDataPointPtrSlice(dest, []*CountMinSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyCountMinSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestCountMinSketchDataPointPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONCountMinSketchDataPointUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewCountMinSketchDataPoint()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewCountMinSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalJSONCountMinSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesCountMinSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewCountMinSketchDataPoint()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteCountMinSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoCountMinSketchDataPointFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesCountMinSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			dest := NewCountMinSketchDataPoint()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoCountMinSketchDataPointUnknown(t *testing.T) {
	dest := NewCountMinSketchDataPoint()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewCountMinSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalProtoCountMinSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesCountMinSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewCountMinSketchDataPoint()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteCountMinSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufCountMinSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesCountMinSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.CountMinSketchDataPoint{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewCountMinSketchDataPoint()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesCountMinSketchDataPoint() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                     {0x02},
		"Attributes/wrong_wire_type":        {0xc},
		"Attributes/missing_value":          {0xa},
		"StartTimeUnixNano/wrong_wire_type": {0x14},
		"StartTimeUnixNano/missing_value":   {0x11},
		"TimeUnixNano/wrong_wire_type":      {0x1c},
		"TimeUnixNano/missing_value":        {0x19},
		"Sketch/wrong_wire_type":            {0x2c},
		"Sketch/missing_value":              {0x2a},
		"Encoding/wrong_wire_type":          {0x34},
		"Encoding/missing_value":            {0x30},
		"Flags/wrong_wire_type":             {0x4c},
		"Flags/missing_value":               {0x48},
		"SeriesID/wrong_wire_type":          {0x54},
		"SeriesID/missing_value":            {0x50},
	}
}

func genTestEncodingValuesCountMinSketchDataPoint() map[string]*CountMinSketchDataPoint {
	return map[string]*CountMinSketchDataPoint{
		"empty":                  NewCountMinSketchDataPoint(),
		"Attributes/test":        {Attributes: []KeyValue{{}, *GenTestKeyValue()}},
		"StartTimeUnixNano/test": {StartTimeUnixNano: uint64(13)},
		"TimeUnixNano/test":      {TimeUnixNano: uint64(13)},
		"Sketch/test":            {Sketch: []byte{1, 2, 3}},
		"Encoding/test":          {Encoding: CountMinSketchEncoding(13)},
		"Flags/test":             {Flags: uint32(13)},
		"SeriesID/test":          {SeriesID: uint64(13)},
	}
}
