// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"encoding/binary"
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// HLLSketchDataPoint is a single data point that encodes cardinality estimations using HyperLogLog.
type HLLSketchDataPoint struct {
	Attributes        []KeyValue
	SeriesID          uint64
	StartTimeUnixNano uint64
	TimeUnixNano      uint64
	Count             uint64
	Cardinality       uint64
	Sketch            []byte
	Encoding          HLLSketchEncoding
	Precision         uint32
	Flags             uint32
}

var (
	protoPoolHLLSketchDataPoint = sync.Pool{
		New: func() any {
			return &HLLSketchDataPoint{}
		},
	}
)

func NewHLLSketchDataPoint() *HLLSketchDataPoint {
	if !UseProtoPooling.IsEnabled() {
		return &HLLSketchDataPoint{}
	}
	return protoPoolHLLSketchDataPoint.Get().(*HLLSketchDataPoint)
}

func DeleteHLLSketchDataPoint(orig *HLLSketchDataPoint, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.Attributes {
		DeleteKeyValue(&orig.Attributes[i], false)
	}

	orig.Reset()
	if nullable {
		protoPoolHLLSketchDataPoint.Put(orig)
	}
}

func CopyHLLSketchDataPoint(dest, src *HLLSketchDataPoint) *HLLSketchDataPoint {
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewHLLSketchDataPoint()
	}
	dest.Attributes = CopyKeyValueSlice(dest.Attributes, src.Attributes)
	dest.SeriesID = src.SeriesID
	dest.StartTimeUnixNano = src.StartTimeUnixNano
	dest.TimeUnixNano = src.TimeUnixNano
	dest.Count = src.Count
	dest.Cardinality = src.Cardinality
	dest.Sketch = src.Sketch
	dest.Encoding = src.Encoding
	dest.Precision = src.Precision
	dest.Flags = src.Flags

	return dest
}

func CopyHLLSketchDataPointSlice(dest, src []HLLSketchDataPoint) []HLLSketchDataPoint {
	var newDest []HLLSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]HLLSketchDataPoint, len(src))
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteHLLSketchDataPoint(&dest[i], false)
		}
	}
	for i := range src {
		CopyHLLSketchDataPoint(&newDest[i], &src[i])
	}
	return newDest
}

func CopyHLLSketchDataPointPtrSlice(dest, src []*HLLSketchDataPoint) []*HLLSketchDataPoint {
	var newDest []*HLLSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]*HLLSketchDataPoint, len(src))
		copy(newDest, dest)
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewHLLSketchDataPoint()
		}
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteHLLSketchDataPoint(dest[i], true)
			dest[i] = nil
		}
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewHLLSketchDataPoint()
		}
	}
	for i := range src {
		CopyHLLSketchDataPoint(newDest[i], src[i])
	}
	return newDest
}

func (orig *HLLSketchDataPoint) Reset() {
	*orig = HLLSketchDataPoint{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *HLLSketchDataPoint) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.Attributes) > 0 {
		dest.WriteObjectField("attributes")
		dest.WriteArrayStart()
		orig.Attributes[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Attributes); i++ {
			dest.WriteMore()
			orig.Attributes[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.SeriesID != uint64(0) {
		dest.WriteObjectField("seriesID")
		dest.WriteUint64(orig.SeriesID)
	}
	if orig.StartTimeUnixNano != uint64(0) {
		dest.WriteObjectField("startTimeUnixNano")
		dest.WriteUint64(orig.StartTimeUnixNano)
	}
	if orig.TimeUnixNano != uint64(0) {
		dest.WriteObjectField("timeUnixNano")
		dest.WriteUint64(orig.TimeUnixNano)
	}
	if orig.Count != uint64(0) {
		dest.WriteObjectField("count")
		dest.WriteUint64(orig.Count)
	}
	if orig.Cardinality != uint64(0) {
		dest.WriteObjectField("cardinality")
		dest.WriteUint64(orig.Cardinality)
	}
	if len(orig.Sketch) > 0 {
		dest.WriteObjectField("sketch")
		dest.WriteBytes(orig.Sketch)
	}
	if int32(orig.Encoding) != 0 {
		dest.WriteObjectField("encoding")
		dest.WriteInt32(int32(orig.Encoding))
	}
	if orig.Precision != uint32(0) {
		dest.WriteObjectField("precision")
		dest.WriteUint32(orig.Precision)
	}
	if orig.Flags != uint32(0) {
		dest.WriteObjectField("flags")
		dest.WriteUint32(orig.Flags)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *HLLSketchDataPoint) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "attributes":
			for iter.ReadArray() {
				orig.Attributes = append(orig.Attributes, KeyValue{})
				orig.Attributes[len(orig.Attributes)-1].UnmarshalJSON(iter)
			}
		case "seriesID", "series_id":
			orig.SeriesID = iter.ReadUint64()
		case "startTimeUnixNano", "start_time_unix_nano":
			orig.StartTimeUnixNano = iter.ReadUint64()
		case "timeUnixNano", "time_unix_nano":
			orig.TimeUnixNano = iter.ReadUint64()
		case "count":
			orig.Count = iter.ReadUint64()
		case "cardinality":
			orig.Cardinality = iter.ReadUint64()
		case "sketch":
			orig.Sketch = iter.ReadBytes()
		case "encoding":
			orig.Encoding = HLLSketchEncoding(iter.ReadEnumValue(HLLSketchEncoding_value))
		case "precision":
			orig.Precision = iter.ReadUint32()
		case "flags":
			orig.Flags = iter.ReadUint32()
		default:
			iter.Skip()
		}
	}
}

func (orig *HLLSketchDataPoint) SizeProto() int {
	// Field layout:
	//  1=attributes (wire 2)
	//  2=start_time_unix_nano (wire 1, I64)
	//  3=time_unix_nano (wire 1, I64)
	//  4=count (wire 0)
	//  5=cardinality (wire 0)
	//  6=sketch (wire 2)
	//  7=encoding (wire 0)
	//  8=precision (wire 0)
	//  9=flags (wire 0)
	// 10=series_id (wire 0)
	var n int
	var l int
	_ = l
	for i := range orig.Attributes {
		l = orig.Attributes[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.StartTimeUnixNano != 0 {
		n += 9
	}
	if orig.TimeUnixNano != 0 {
		n += 9
	}
	if orig.Count != 0 {
		n += 1 + proto.Sov(uint64(orig.Count))
	}
	if orig.Cardinality != 0 {
		n += 1 + proto.Sov(uint64(orig.Cardinality))
	}
	l = len(orig.Sketch)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Encoding != 0 {
		n += 1 + proto.Sov(uint64(orig.Encoding))
	}
	if orig.Precision != 0 {
		n += 1 + proto.Sov(uint64(orig.Precision))
	}
	if orig.Flags != 0 {
		n += 1 + proto.Sov(uint64(orig.Flags))
	}
	if orig.SeriesID != 0 {
		n += 1 + proto.Sov(uint64(orig.SeriesID))
	}
	return n
}

func (orig *HLLSketchDataPoint) MarshalProto(buf []byte) int {
	// Wire tag bytes:
	//  1=attributes: 0x0a
	//  2=start_time_unix_nano: 0x11
	//  3=time_unix_nano: 0x19
	//  4=count: 0x20
	//  5=cardinality: 0x28
	//  6=sketch: 0x32
	//  7=encoding: 0x38
	//  8=precision: 0x40
	//  9=flags: 0x48
	// 10=series_id: 0x50
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.Attributes) - 1; i >= 0; i-- {
		l = orig.Attributes[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x0a
	}
	if orig.SeriesID != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.SeriesID))
		pos--
		buf[pos] = 0x50
	}
	if orig.StartTimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.StartTimeUnixNano))
		pos--
		buf[pos] = 0x11
	}
	if orig.TimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.TimeUnixNano))
		pos--
		buf[pos] = 0x19
	}
	if orig.Count != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Count))
		pos--
		buf[pos] = 0x20
	}
	if orig.Cardinality != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Cardinality))
		pos--
		buf[pos] = 0x28
	}
	l = len(orig.Sketch)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Sketch)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x32
	}
	if orig.Encoding != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Encoding))
		pos--
		buf[pos] = 0x38
	}
	if orig.Precision != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Precision))
		pos--
		buf[pos] = 0x40
	}
	if orig.Flags != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Flags))
		pos--
		buf[pos] = 0x48
	}
	return len(buf) - pos
}

func (orig *HLLSketchDataPoint) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Attributes = append(orig.Attributes, KeyValue{})
			err = orig.Attributes[len(orig.Attributes)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.StartTimeUnixNano = uint64(num)

		case 3:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.TimeUnixNano = uint64(num)

		case 4:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Count = uint64(num)

		case 5:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Cardinality", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Cardinality = uint64(num)

		case 6:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sketch", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.Sketch = make([]byte, length)
				copy(orig.Sketch, buf[startPos:pos])
			}

		case 7:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Encoding = HLLSketchEncoding(num)

		case 8:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Precision", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Precision = uint32(num)

		case 9:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Flags = uint32(num)

		case 10:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field SeriesID", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.SeriesID = uint64(num)

		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestHLLSketchDataPoint() *HLLSketchDataPoint {
	orig := NewHLLSketchDataPoint()
	orig.Attributes = []KeyValue{{}, *GenTestKeyValue()}
	orig.SeriesID = uint64(13)
	orig.StartTimeUnixNano = uint64(13)
	orig.TimeUnixNano = uint64(13)
	orig.Count = uint64(1000)
	orig.Cardinality = uint64(500)
	orig.Sketch = []byte{1, 2, 3}
	orig.Encoding = HLLSketchEncoding(1)
	orig.Precision = uint32(14)
	orig.Flags = uint32(13)
	return orig
}

func GenTestHLLSketchDataPointPtrSlice() []*HLLSketchDataPoint {
	orig := make([]*HLLSketchDataPoint, 5)
	orig[0] = NewHLLSketchDataPoint()
	orig[1] = GenTestHLLSketchDataPoint()
	orig[2] = NewHLLSketchDataPoint()
	orig[3] = GenTestHLLSketchDataPoint()
	orig[4] = NewHLLSketchDataPoint()
	return orig
}

func GenTestHLLSketchDataPointSlice() []HLLSketchDataPoint {
	orig := make([]HLLSketchDataPoint, 5)
	orig[1] = *GenTestHLLSketchDataPoint()
	orig[3] = *GenTestHLLSketchDataPoint()
	return orig
}
