// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyCountSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesCountSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewCountSketchDataPoint()
				CopyCountSketchDataPoint(dest, src)
				assert.Equal(t, src, dest)
				CopyCountSketchDataPoint(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyCountSketchDataPointSlice(t *testing.T) {
	src := []CountSketchDataPoint{}
	dest := []CountSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyCountSketchDataPointSlice(dest, src)
	assert.Equal(t, []CountSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestCountSketchDataPointSlice()
	dest = CopyCountSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestCountSketchDataPointSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyCountSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestCountSketchDataPointSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyCountSketchDataPointSlice(dest, []CountSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyCountSketchDataPointSlice(dest, src)
	assert.Equal(t, GenTestCountSketchDataPointSlice(), dest)
}

func TestCopyCountSketchDataPointPtrSlice(t *testing.T) {
	src := []*CountSketchDataPoint{}
	dest := []*CountSketchDataPoint{}
	// Test CopyTo empty
	dest = CopyCountSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, []*CountSketchDataPoint{}, dest)

	// Test CopyTo larger slice
	src = GenTestCountSketchDataPointPtrSlice()
	dest = CopyCountSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestCountSketchDataPointPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyCountSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestCountSketchDataPointPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyCountSketchDataPointPtrSlice(dest, []*CountSketchDataPoint{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyCountSketchDataPointPtrSlice(dest, src)
	assert.Equal(t, GenTestCountSketchDataPointPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONCountSketchDataPointUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewCountSketchDataPoint()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewCountSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalJSONCountSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesCountSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewCountSketchDataPoint()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteCountSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoCountSketchDataPointFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesCountSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			dest := NewCountSketchDataPoint()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoCountSketchDataPointUnknown(t *testing.T) {
	dest := NewCountSketchDataPoint()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewCountSketchDataPoint(), dest)
}

func TestMarshalAndUnmarshalProtoCountSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesCountSketchDataPoint() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewCountSketchDataPoint()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteCountSketchDataPoint(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufCountSketchDataPoint(t *testing.T) {
	for name, src := range genTestEncodingValuesCountSketchDataPoint() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.CountSketchDataPoint{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewCountSketchDataPoint()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesCountSketchDataPoint() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                     {0x02},
		"Attributes/wrong_wire_type":        {0xc},
		"Attributes/missing_value":          {0xa},
		"StartTimeUnixNano/wrong_wire_type": {0x14},
		"StartTimeUnixNano/missing_value":   {0x11},
		"TimeUnixNano/wrong_wire_type":      {0x1c},
		"TimeUnixNano/missing_value":        {0x19},
		"Sketch/wrong_wire_type":            {0x24},
		"Sketch/missing_value":              {0x22},
		"Encoding/wrong_wire_type":          {0x2c},
		"Encoding/missing_value":            {0x28},
		"Flags/wrong_wire_type":             {0x4c},
		"Flags/missing_value":               {0x48},
		"SeriesID/wrong_wire_type":          {0x54},
		"SeriesID/missing_value":            {0x50},
	}
}

func genTestEncodingValuesCountSketchDataPoint() map[string]*CountSketchDataPoint {
	return map[string]*CountSketchDataPoint{
		"empty":                  NewCountSketchDataPoint(),
		"Attributes/test":        {Attributes: []KeyValue{{}, *GenTestKeyValue()}},
		"StartTimeUnixNano/test": {StartTimeUnixNano: uint64(13)},
		"TimeUnixNano/test":      {TimeUnixNano: uint64(13)},
		"Sketch/test":            {Sketch: []byte{1, 2, 3}},
		"Encoding/test":          {Encoding: CountSketchEncoding(13)},
		"Flags/test":             {Flags: uint32(13)},
		"SeriesID/test":          {SeriesID: uint64(13)},
	}
}
