// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"encoding/binary"
	"fmt"
	"math"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// KLLSketchDataPoint is a single data point that encodes a distribution using the KLL sketch format.
type KLLSketchDataPoint struct {
	Attributes        []KeyValue
	SeriesID          uint64
	StartTimeUnixNano uint64
	TimeUnixNano      uint64
	Count             uint64
	Sum               float64
	Min               float64
	Max               float64
	Sketch            []byte
	Encoding          KLLSketchEncoding
	Flags             uint32
}

var (
	protoPoolKLLSketchDataPoint = sync.Pool{
		New: func() any {
			return &KLLSketchDataPoint{}
		},
	}
)

func NewKLLSketchDataPoint() *KLLSketchDataPoint {
	if !UseProtoPooling.IsEnabled() {
		return &KLLSketchDataPoint{}
	}
	return protoPoolKLLSketchDataPoint.Get().(*KLLSketchDataPoint)
}

func DeleteKLLSketchDataPoint(orig *KLLSketchDataPoint, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	for i := range orig.Attributes {
		DeleteKeyValue(&orig.Attributes[i], false)
	}

	orig.Reset()
	if nullable {
		protoPoolKLLSketchDataPoint.Put(orig)
	}
}

func CopyKLLSketchDataPoint(dest, src *KLLSketchDataPoint) *KLLSketchDataPoint {
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewKLLSketchDataPoint()
	}
	dest.Attributes = CopyKeyValueSlice(dest.Attributes, src.Attributes)

	dest.SeriesID = src.SeriesID

	dest.StartTimeUnixNano = src.StartTimeUnixNano

	dest.TimeUnixNano = src.TimeUnixNano

	dest.Count = src.Count

	dest.Sum = src.Sum

	dest.Min = src.Min

	dest.Max = src.Max

	dest.Sketch = src.Sketch

	dest.Encoding = src.Encoding

	dest.Flags = src.Flags

	return dest
}

func CopyKLLSketchDataPointSlice(dest, src []KLLSketchDataPoint) []KLLSketchDataPoint {
	var newDest []KLLSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]KLLSketchDataPoint, len(src))
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteKLLSketchDataPoint(&dest[i], false)
		}
	}
	for i := range src {
		CopyKLLSketchDataPoint(&newDest[i], &src[i])
	}
	return newDest
}

func CopyKLLSketchDataPointPtrSlice(dest, src []*KLLSketchDataPoint) []*KLLSketchDataPoint {
	var newDest []*KLLSketchDataPoint
	if cap(dest) < len(src) {
		newDest = make([]*KLLSketchDataPoint, len(src))
		copy(newDest, dest)
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewKLLSketchDataPoint()
		}
	} else {
		newDest = dest[:len(src)]
		for i := len(src); i < len(dest); i++ {
			DeleteKLLSketchDataPoint(dest[i], true)
			dest[i] = nil
		}
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewKLLSketchDataPoint()
		}
	}
	for i := range src {
		CopyKLLSketchDataPoint(newDest[i], src[i])
	}
	return newDest
}

func (orig *KLLSketchDataPoint) Reset() {
	*orig = KLLSketchDataPoint{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *KLLSketchDataPoint) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.Attributes) > 0 {
		dest.WriteObjectField("attributes")
		dest.WriteArrayStart()
		orig.Attributes[0].MarshalJSON(dest)
		for i := 1; i < len(orig.Attributes); i++ {
			dest.WriteMore()
			orig.Attributes[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	if orig.SeriesID != uint64(0) {
		dest.WriteObjectField("seriesID")
		dest.WriteUint64(orig.SeriesID)
	}
	if orig.StartTimeUnixNano != uint64(0) {
		dest.WriteObjectField("startTimeUnixNano")
		dest.WriteUint64(orig.StartTimeUnixNano)
	}
	if orig.TimeUnixNano != uint64(0) {
		dest.WriteObjectField("timeUnixNano")
		dest.WriteUint64(orig.TimeUnixNano)
	}
	if orig.Count != uint64(0) {
		dest.WriteObjectField("count")
		dest.WriteUint64(orig.Count)
	}
	if orig.Sum != float64(0) {
		dest.WriteObjectField("sum")
		dest.WriteFloat64(orig.Sum)
	}
	if orig.Min != float64(0) {
		dest.WriteObjectField("min")
		dest.WriteFloat64(orig.Min)
	}
	if orig.Max != float64(0) {
		dest.WriteObjectField("max")
		dest.WriteFloat64(orig.Max)
	}
	if len(orig.Sketch) > 0 {
		dest.WriteObjectField("sketch")
		dest.WriteBytes(orig.Sketch)
	}
	if int32(orig.Encoding) != 0 {
		dest.WriteObjectField("encoding")
		dest.WriteInt32(int32(orig.Encoding))
	}
	if orig.Flags != uint32(0) {
		dest.WriteObjectField("flags")
		dest.WriteUint32(orig.Flags)
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *KLLSketchDataPoint) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "attributes":
			for iter.ReadArray() {
				orig.Attributes = append(orig.Attributes, KeyValue{})
				orig.Attributes[len(orig.Attributes)-1].UnmarshalJSON(iter)
			}

		case "seriesID", "series_id":
			orig.SeriesID = iter.ReadUint64()
		case "startTimeUnixNano", "start_time_unix_nano":
			orig.StartTimeUnixNano = iter.ReadUint64()
		case "timeUnixNano", "time_unix_nano":
			orig.TimeUnixNano = iter.ReadUint64()
		case "count":
			orig.Count = iter.ReadUint64()
		case "sum":
			orig.Sum = iter.ReadFloat64()
		case "min":
			orig.Min = iter.ReadFloat64()
		case "max":
			orig.Max = iter.ReadFloat64()
		case "sketch":
			orig.Sketch = iter.ReadBytes()
		case "encoding":
			orig.Encoding = KLLSketchEncoding(iter.ReadEnumValue(KLLSketchEncoding_value))
		case "flags":
			orig.Flags = iter.ReadUint32()
		default:
			iter.Skip()
		}
	}
}

func (orig *KLLSketchDataPoint) SizeProto() int {
	var n int
	var l int
	_ = l
	for i := range orig.Attributes {
		l = orig.Attributes[i].SizeProto()
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.StartTimeUnixNano != 0 {
		n += 9
	}
	if orig.TimeUnixNano != 0 {
		n += 9
	}
	if orig.Count != 0 {
		n += 9
	}
	if orig.Sum != 0 {
		n += 9
	}
	if orig.Min != 0 {
		n += 9
	}
	if orig.Max != 0 {
		n += 9
	}
	l = len(orig.Sketch)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	if orig.Encoding != 0 {
		n += 1 + proto.Sov(uint64(orig.Encoding))
	}
	if orig.Flags != 0 {
		n += 1 + proto.Sov(uint64(orig.Flags))
	}
	if orig.SeriesID != 0 {
		n += 1 + proto.Sov(uint64(orig.SeriesID))
	}
	return n
}

func (orig *KLLSketchDataPoint) MarshalProto(buf []byte) int {
	// Field numbers:
	//  1=attributes (wire 2, tag=0x0a)
	//  2=start_time_unix_nano (wire 1, tag=0x11)
	//  3=time_unix_nano (wire 1, tag=0x19)
	//  4=count (wire 1, tag=0x21)
	//  5=sum (wire 1, tag=0x29)
	//  6=min (wire 1, tag=0x31)
	//  7=max (wire 1, tag=0x39)
	//  8=sketch (wire 2, tag=0x42)
	//  9=encoding (wire 0, tag=0x48)
	// 10=flags (wire 0, tag=0x50)
	// 11=series_id (wire 0, tag=0x58)
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.Attributes) - 1; i >= 0; i-- {
		l = orig.Attributes[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x0a
	}
	if orig.SeriesID != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.SeriesID))
		pos--
		buf[pos] = 0x58
	}
	if orig.StartTimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.StartTimeUnixNano))
		pos--
		buf[pos] = 0x11
	}
	if orig.TimeUnixNano != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.TimeUnixNano))
		pos--
		buf[pos] = 0x19
	}
	if orig.Count != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], uint64(orig.Count))
		pos--
		buf[pos] = 0x21
	}
	if orig.Sum != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.Sum))
		pos--
		buf[pos] = 0x29
	}
	if orig.Min != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.Min))
		pos--
		buf[pos] = 0x31
	}
	if orig.Max != 0 {
		pos -= 8
		binary.LittleEndian.PutUint64(buf[pos:], math.Float64bits(orig.Max))
		pos--
		buf[pos] = 0x39
	}
	l = len(orig.Sketch)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.Sketch)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x42
	}
	if orig.Encoding != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Encoding))
		pos--
		buf[pos] = 0x48
	}
	if orig.Flags != 0 {
		pos = proto.EncodeVarint(buf, pos, uint64(orig.Flags))
		pos--
		buf[pos] = 0x50
	}
	return len(buf) - pos
}

func (orig *KLLSketchDataPoint) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.Attributes = append(orig.Attributes, KeyValue{})
			err = orig.Attributes[len(orig.Attributes)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.StartTimeUnixNano = uint64(num)

		case 3:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnixNano", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.TimeUnixNano = uint64(num)

		case 4:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.Count = uint64(num)

		case 5:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.Sum = math.Float64frombits(num)

		case 6:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Min", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.Min = math.Float64frombits(num)

		case 7:
			if wireType != proto.WireTypeI64 {
				return fmt.Errorf("proto: wrong wireType = %d for field Max", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeI64(buf, pos)
			if err != nil {
				return err
			}
			orig.Max = math.Float64frombits(num)

		case 8:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Sketch", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.Sketch = make([]byte, length)
				copy(orig.Sketch, buf[startPos:pos])
			}

		case 9:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Encoding = KLLSketchEncoding(num)

		case 10:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.Flags = uint32(num)

		case 11:
			if wireType != proto.WireTypeVarint {
				return fmt.Errorf("proto: wrong wireType = %d for field SeriesID", wireType)
			}
			var num uint64
			num, pos, err = proto.ConsumeVarint(buf, pos)
			if err != nil {
				return err
			}
			orig.SeriesID = uint64(num)

		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestKLLSketchDataPoint() *KLLSketchDataPoint {
	orig := NewKLLSketchDataPoint()
	orig.Attributes = []KeyValue{{}, *GenTestKeyValue()}
	orig.SeriesID = uint64(13)
	orig.StartTimeUnixNano = uint64(13)
	orig.TimeUnixNano = uint64(13)
	orig.Count = uint64(13)
	orig.Sum = float64(3.1415926)
	orig.Min = float64(1.0)
	orig.Max = float64(13.0)
	orig.Sketch = []byte{1, 2, 3}
	orig.Encoding = KLLSketchEncoding(1)
	orig.Flags = uint32(13)
	return orig
}

func GenTestKLLSketchDataPointPtrSlice() []*KLLSketchDataPoint {
	orig := make([]*KLLSketchDataPoint, 5)
	orig[0] = NewKLLSketchDataPoint()
	orig[1] = GenTestKLLSketchDataPoint()
	orig[2] = NewKLLSketchDataPoint()
	orig[3] = GenTestKLLSketchDataPoint()
	orig[4] = NewKLLSketchDataPoint()
	return orig
}

func GenTestKLLSketchDataPointSlice() []KLLSketchDataPoint {
	orig := make([]KLLSketchDataPoint, 5)
	orig[1] = *GenTestKLLSketchDataPoint()
	orig[3] = *GenTestKLLSketchDataPoint()
	return orig
}
