// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

const (
	CountMinSketchEncoding_COUNT_MIN_SKETCH_ENCODING_UNSPECIFIED = CountMinSketchEncoding(0)
	CountMinSketchEncoding_COUNT_MIN_SKETCH_ENCODING_GOB         = CountMinSketchEncoding(1)
)

// CountMinSketchEncoding identifies how the CountMinSketch payload bytes are encoded.
type CountMinSketchEncoding int32

var CountMinSketchEncoding_name = map[int32]string{
	0: "COUNT_MIN_SKETCH_ENCODING_UNSPECIFIED",
	1: "COUNT_MIN_SKETCH_ENCODING_GOB",
}

var CountMinSketchEncoding_value = map[string]int32{
	"COUNT_MIN_SKETCH_ENCODING_UNSPECIFIED": 0,
	"COUNT_MIN_SKETCH_ENCODING_GOB":         1,
}
