receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 64

processors:
  countsketch:
    transmit_sketch: true
    mode: window
    epsilon: 0.01
    delta: 0.99
    window_duration: 10s
    drop_original: true

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888

  pipelines:
    metrics:
      receivers: [otlp]
      processors: [countsketch]
      exporters: [prometheus]
