receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 64
      http:
        endpoint: 0.0.0.0:4318

processors:
  countsketch:
    mode: batch
    epsilon: 0.02
    delta: 0.99
    transmit_sketch: true
    drop_original: true
    delta_transmission: true
    delta_threshold: 1.0

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [countsketch]
      exporters: [prometheus]
  telemetry:
    metrics:
      level: basic
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
    logs:
      level: info
    resource:
      service.name: countsketchcol-batch-delta
