// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module KLL

go 1.25.4

replace github.com/open-telemetry/opentelemetry-collector-contrib/processor/kllprocessor => ./processor/kllprocessor
