// Code generated by gotmpl. DO NOT MODIFY.
// source: internal/shared/otlp/otlpmetric/transform/metricdata.go.tmpl

// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Package transform provides transformation functionality from the
// sdk/metric/metricdata data-types into OTLP data-types.
package transform // import "go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp/internal/transform"

import (
	"fmt"
	"time"

	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	cpb "go.opentelemetry.io/proto/otlp/common/v1"
	mpb "go.opentelemetry.io/proto/otlp/metrics/v1"
	rpb "go.opentelemetry.io/proto/otlp/resource/v1"
)

// ResourceMetrics returns an OTLP ResourceMetrics generated from rm. If rm
// contains invalid ScopeMetrics, an error will be returned along with an OTLP
// ResourceMetrics that contains partial OTLP ScopeMetrics.
func ResourceMetrics(rm *metricdata.ResourceMetrics) (*mpb.ResourceMetrics, error) {
	sms, err := ScopeMetrics(rm.ScopeMetrics)
	return &mpb.ResourceMetrics{
		Resource: &rpb.Resource{
			Attributes: AttrIter(rm.Resource.Iter()),
		},
		ScopeMetrics: sms,
		SchemaUrl:    rm.Resource.SchemaURL(),
	}, err
}

// ScopeMetrics returns a slice of OTLP ScopeMetrics generated from sms. If
// sms contains invalid metric values, an error will be returned along with a
// slice that contains partial OTLP ScopeMetrics.
func ScopeMetrics(sms []metricdata.ScopeMetrics) ([]*mpb.ScopeMetrics, error) {
	errs := &multiErr{datatype: "ScopeMetrics"}
	out := make([]*mpb.ScopeMetrics, 0, len(sms))
	for _, sm := range sms {
		ms, err := Metrics(sm.Metrics)
		if err != nil {
			errs.append(err)
		}

		out = append(out, &mpb.ScopeMetrics{
			Scope: &cpb.InstrumentationScope{
				Name:       sm.Scope.Name,
				Version:    sm.Scope.Version,
				Attributes: AttrIter(sm.Scope.Attributes.Iter()),
			},
			Metrics:   ms,
			SchemaUrl: sm.Scope.SchemaURL,
		})
	}
	return out, errs.errOrNil()
}

// Metrics returns a slice of OTLP Metric generated from ms. If ms contains
// invalid metric values, an error will be returned along with a slice that
// contains partial OTLP Metrics.
func Metrics(ms []metricdata.Metrics) ([]*mpb.Metric, error) {
	errs := &multiErr{datatype: "Metrics"}
	out := make([]*mpb.Metric, 0, len(ms))
	for _, m := range ms {
		o, err := metric(m)
		if err != nil {
			// Do not include invalid data. Drop the metric, report the error.
			errs.append(errMetric{m: o, err: err})
			continue
		}
		out = append(out, o)
	}
	return out, errs.errOrNil()
}

func metric(m metricdata.Metrics) (*mpb.Metric, error) {
	var err error
	out := &mpb.Metric{
		Name:        m.Name,
		Description: m.Description,
		Unit:        m.Unit,
	}
	switch a := m.Data.(type) {
	case metricdata.Gauge[int64]:
		out.Data = Gauge(a)
	case metricdata.Gauge[float64]:
		out.Data = Gauge(a)
	case metricdata.Sum[int64]:
		out.Data, err = Sum(a)
	case metricdata.Sum[float64]:
		out.Data, err = Sum(a)
	case metricdata.Histogram[int64]:
		out.Data, err = Histogram(a)
	case metricdata.Histogram[float64]:
		out.Data, err = Histogram(a)
	case metricdata.ExponentialHistogram[int64]:
		out.Data, err = ExponentialHistogram(a)
	case metricdata.ExponentialHistogram[float64]:
		out.Data, err = ExponentialHistogram(a)
	case metricdata.DDSketch[int64]:
		out.Data, err = DDSketch(a)
	case metricdata.DDSketch[float64]:
		out.Data, err = DDSketch(a)
	case metricdata.Summary:
		out.Data = Summary(a)
	case metricdata.KLLSketch[int64]:
		out.Data, err = KLLSketch(a)
	case metricdata.KLLSketch[float64]:
		out.Data, err = KLLSketch(a)
	case metricdata.CountSketch[int64]:
		out.Data, err = CountSketch(a)
	case metricdata.CountSketch[float64]:
		out.Data, err = CountSketch(a)
	case metricdata.CountMinSketch[int64]:
		out.Data, err = CountMinSketch(a)
	case metricdata.CountMinSketch[float64]:
		out.Data, err = CountMinSketch(a)
	case metricdata.HLLSketch:
		out.Data, err = HLLSketch(a)
	default:
		return out, fmt.Errorf("%w: %T", errUnknownAggregation, a)
	}
	return out, err
}

// Gauge returns an OTLP Metric_Gauge generated from g.
func Gauge[N int64 | float64](g metricdata.Gauge[N]) *mpb.Metric_Gauge {
	return &mpb.Metric_Gauge{
		Gauge: &mpb.Gauge{
			DataPoints: DataPoints(g.DataPoints),
		},
	}
}

// Sum returns an OTLP Metric_Sum generated from s. An error is returned
// if the temporality of s is unknown.
func Sum[N int64 | float64](s metricdata.Sum[N]) (*mpb.Metric_Sum, error) {
	t, err := Temporality(s.Temporality)
	if err != nil {
		return nil, err
	}
	return &mpb.Metric_Sum{
		Sum: &mpb.Sum{
			AggregationTemporality: t,
			IsMonotonic:            s.IsMonotonic,
			DataPoints:             DataPoints(s.DataPoints),
		},
	}, nil
}

// DataPoints returns a slice of OTLP NumberDataPoint generated from dPts.
func DataPoints[N int64 | float64](dPts []metricdata.DataPoint[N]) []*mpb.NumberDataPoint {
	out := make([]*mpb.NumberDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		ndp := &mpb.NumberDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			Exemplars:         Exemplars(dPt.Exemplars),
		}
		switch v := any(dPt.Value).(type) {
		case int64:
			ndp.Value = &mpb.NumberDataPoint_AsInt{
				AsInt: v,
			}
		case float64:
			ndp.Value = &mpb.NumberDataPoint_AsDouble{
				AsDouble: v,
			}
		}
		out = append(out, ndp)
	}
	return out
}

// Histogram returns an OTLP Metric_Histogram generated from h. An error is
// returned if the temporality of h is unknown.
func Histogram[N int64 | float64](h metricdata.Histogram[N]) (*mpb.Metric_Histogram, error) {
	t, err := Temporality(h.Temporality)
	if err != nil {
		return nil, err
	}
	return &mpb.Metric_Histogram{
		Histogram: &mpb.Histogram{
			AggregationTemporality: t,
			DataPoints:             HistogramDataPoints(h.DataPoints),
		},
	}, nil
}

// HistogramDataPoints returns a slice of OTLP HistogramDataPoint generated
// from dPts.
func HistogramDataPoints[N int64 | float64](dPts []metricdata.HistogramDataPoint[N]) []*mpb.HistogramDataPoint {
	out := make([]*mpb.HistogramDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		sum := float64(dPt.Sum)
		hdp := &mpb.HistogramDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			Count:             dPt.Count,
			Sum:               &sum,
			BucketCounts:      dPt.BucketCounts,
			ExplicitBounds:    dPt.Bounds,
			Exemplars:         Exemplars(dPt.Exemplars),
		}
		if v, ok := dPt.Min.Value(); ok {
			vF64 := float64(v)
			hdp.Min = &vF64
		}
		if v, ok := dPt.Max.Value(); ok {
			vF64 := float64(v)
			hdp.Max = &vF64
		}
		out = append(out, hdp)
	}
	return out
}

// ExponentialHistogram returns an OTLP Metric_ExponentialHistogram generated from h. An error is
// returned if the temporality of h is unknown.
func ExponentialHistogram[N int64 | float64](
	h metricdata.ExponentialHistogram[N],
) (*mpb.Metric_ExponentialHistogram, error) {
	t, err := Temporality(h.Temporality)
	if err != nil {
		return nil, err
	}
	return &mpb.Metric_ExponentialHistogram{
		ExponentialHistogram: &mpb.ExponentialHistogram{
			AggregationTemporality: t,
			DataPoints:             ExponentialHistogramDataPoints(h.DataPoints),
		},
	}, nil
}

// ExponentialHistogramDataPoints returns a slice of OTLP ExponentialHistogramDataPoint generated
// from dPts.
func ExponentialHistogramDataPoints[N int64 | float64](
	dPts []metricdata.ExponentialHistogramDataPoint[N],
) []*mpb.ExponentialHistogramDataPoint {
	out := make([]*mpb.ExponentialHistogramDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		sum := float64(dPt.Sum)
		ehdp := &mpb.ExponentialHistogramDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			Count:             dPt.Count,
			Sum:               &sum,
			Scale:             dPt.Scale,
			ZeroCount:         dPt.ZeroCount,
			Exemplars:         Exemplars(dPt.Exemplars),

			Positive: ExponentialHistogramDataPointBuckets(dPt.PositiveBucket),
			Negative: ExponentialHistogramDataPointBuckets(dPt.NegativeBucket),
		}
		if v, ok := dPt.Min.Value(); ok {
			vF64 := float64(v)
			ehdp.Min = &vF64
		}
		if v, ok := dPt.Max.Value(); ok {
			vF64 := float64(v)
			ehdp.Max = &vF64
		}
		out = append(out, ehdp)
	}
	return out
}

// ExponentialHistogramDataPointBuckets returns an OTLP ExponentialHistogramDataPoint_Buckets generated
// from bucket.
func ExponentialHistogramDataPointBuckets(
	bucket metricdata.ExponentialBucket,
) *mpb.ExponentialHistogramDataPoint_Buckets {
	return &mpb.ExponentialHistogramDataPoint_Buckets{
		Offset:       bucket.Offset,
		BucketCounts: bucket.Counts,
	}
}

// DDSketch returns an OTLP Metric_Ddsketch generated from d. An error is
// returned if the temporality of d is unknown or if any data point uses an
// unsupported encoding.
func DDSketch[N int64 | float64](d metricdata.DDSketch[N]) (*mpb.Metric_Ddsketch, error) {
	t, err := Temporality(d.Temporality)
	if err != nil {
		return nil, err
	}
	dPts, err := DDSketchDataPoints(d.DataPoints)
	if err != nil {
		return nil, err
	}
	return &mpb.Metric_Ddsketch{
		Ddsketch: &mpb.DDSketch{
			AggregationTemporality: t,
			DataPoints:             dPts,
		},
	}, nil
}

// DDSketchDataPoints returns a slice of OTLP DDSketchDataPoint generated
// from dPts.
func DDSketchDataPoints[N int64 | float64](
	dPts []metricdata.DDSketchDataPoint[N],
) ([]*mpb.DDSketchDataPoint, error) {
	out := make([]*mpb.DDSketchDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		encoding, err := DDSketchEncodingValue(dPt.Encoding)
		if err != nil {
			return nil, err
		}

		dp := &mpb.DDSketchDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			Count:             dPt.Count,
			Sketch:            dPt.Sketch,
			Encoding:          encoding,
			Exemplars:         Exemplars(dPt.Exemplars),
		}

		switch v := any(dPt.Sum).(type) {
		case int64:
			dp.Sum = &mpb.DDSketchDataPoint_SumAsInt{
				SumAsInt: v,
			}
		case float64:
			dp.Sum = &mpb.DDSketchDataPoint_SumAsDouble{
				SumAsDouble: v,
			}
		}

		if v, ok := dPt.Min.Value(); ok {
			switch mv := any(v).(type) {
			case int64:
				dp.Min = &mpb.DDSketchDataPoint_MinAsInt{
					MinAsInt: mv,
				}
			case float64:
				dp.Min = &mpb.DDSketchDataPoint_MinAsDouble{
					MinAsDouble: mv,
				}
			}
		}

		if v, ok := dPt.Max.Value(); ok {
			switch mv := any(v).(type) {
			case int64:
				dp.Max = &mpb.DDSketchDataPoint_MaxAsInt{
					MaxAsInt: mv,
				}
			case float64:
				dp.Max = &mpb.DDSketchDataPoint_MaxAsDouble{
					MaxAsDouble: mv,
				}
			}
		}

		out = append(out, dp)
	}
	return out, nil
}

// DDSketchEncodingValue returns an OTLP DDSketchEncoding generated from enc.
func DDSketchEncodingValue(enc metricdata.DDSketchEncoding) (mpb.DDSketchEncoding, error) {
	switch enc {
	case metricdata.DDSketchEncodingProto:
		return mpb.DDSketchEncoding_DDSKETCH_ENCODING_PROTO, nil
	default:
		return mpb.DDSketchEncoding_DDSKETCH_ENCODING_UNSPECIFIED, fmt.Errorf("%w: %s", errUnknownDDSketchEncoding, enc)
	}
}

// Temporality returns an OTLP AggregationTemporality generated from t. If t
// is unknown, an error is returned along with the invalid
// AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED.
func Temporality(t metricdata.Temporality) (mpb.AggregationTemporality, error) {
	switch t {
	case metricdata.DeltaTemporality:
		return mpb.AggregationTemporality_AGGREGATION_TEMPORALITY_DELTA, nil
	case metricdata.CumulativeTemporality:
		return mpb.AggregationTemporality_AGGREGATION_TEMPORALITY_CUMULATIVE, nil
	default:
		err := fmt.Errorf("%w: %s", errUnknownTemporality, t)
		return mpb.AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED, err
	}
}

// timeUnixNano returns t as a Unix time, the number of nanoseconds elapsed
// since January 1, 1970 UTC as uint64.
// The result is undefined if the Unix time
// in nanoseconds cannot be represented by an int64
// (a date before the year 1678 or after 2262).
// timeUnixNano on the zero Time returns 0.
// The result does not depend on the location associated with t.
func timeUnixNano(t time.Time) uint64 {
	return uint64(max(0, t.UnixNano())) // nolint:gosec // Overflow checked.
}

// Exemplars returns a slice of OTLP Exemplars generated from exemplars.
func Exemplars[N int64 | float64](exemplars []metricdata.Exemplar[N]) []*mpb.Exemplar {
	out := make([]*mpb.Exemplar, 0, len(exemplars))
	for _, exemplar := range exemplars {
		e := &mpb.Exemplar{
			FilteredAttributes: KeyValues(exemplar.FilteredAttributes),
			TimeUnixNano:       timeUnixNano(exemplar.Time),
			SpanId:             exemplar.SpanID,
			TraceId:            exemplar.TraceID,
		}
		switch v := any(exemplar.Value).(type) {
		case int64:
			e.Value = &mpb.Exemplar_AsInt{
				AsInt: v,
			}
		case float64:
			e.Value = &mpb.Exemplar_AsDouble{
				AsDouble: v,
			}
		}
		out = append(out, e)
	}
	return out
}

// Summary returns an OTLP Metric_Summary generated from s.
func Summary(s metricdata.Summary) *mpb.Metric_Summary {
	return &mpb.Metric_Summary{
		Summary: &mpb.Summary{
			DataPoints: SummaryDataPoints(s.DataPoints),
		},
	}
}

// SummaryDataPoints returns a slice of OTLP SummaryDataPoint generated from
// dPts.
func SummaryDataPoints(dPts []metricdata.SummaryDataPoint) []*mpb.SummaryDataPoint {
	out := make([]*mpb.SummaryDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		sdp := &mpb.SummaryDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			Count:             dPt.Count,
			Sum:               dPt.Sum,
			QuantileValues:    QuantileValues(dPt.QuantileValues),
		}
		out = append(out, sdp)
	}
	return out
}

// QuantileValues returns a slice of OTLP SummaryDataPoint_ValueAtQuantile
// generated from quantiles.
func QuantileValues(quantiles []metricdata.QuantileValue) []*mpb.SummaryDataPoint_ValueAtQuantile {
	out := make([]*mpb.SummaryDataPoint_ValueAtQuantile, 0, len(quantiles))
	for _, q := range quantiles {
		quantile := &mpb.SummaryDataPoint_ValueAtQuantile{
			Quantile: q.Quantile,
			Value:    q.Value,
		}
		out = append(out, quantile)
	}
	return out
}

// KLLSketch returns an OTLP Metric_Kllsketch generated from k. An error is
// returned if the temporality of k is unknown.
func KLLSketch[N int64 | float64](k metricdata.KLLSketch[N]) (*mpb.Metric_Kllsketch, error) {
	t, err := Temporality(k.Temporality)
	if err != nil {
		return nil, err
	}
	dPts, err := KLLSketchDataPoints(k.DataPoints)
	if err != nil {
		return nil, err
	}
	return &mpb.Metric_Kllsketch{
		Kllsketch: &mpb.KLLSketch{
			AggregationTemporality: t,
			DataPoints:             dPts,
		},
	}, nil
}

// KLLSketchDataPoints returns a slice of OTLP KLLSketchDataPoint generated from dPts.
func KLLSketchDataPoints[N int64 | float64](
	dPts []metricdata.KLLSketchDataPoint[N],
) ([]*mpb.KLLSketchDataPoint, error) {
	out := make([]*mpb.KLLSketchDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		encoding, err := KLLSketchEncodingValue(dPt.Encoding)
		if err != nil {
			return nil, err
		}

		dp := &mpb.KLLSketchDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			Count:             dPt.Count,
			Sum:               dPt.Sum,
			Min:               dPt.Min,
			Max:               dPt.Max,
			Sketch:            dPt.Sketch,
			Encoding:          encoding,
		}
		out = append(out, dp)
	}
	return out, nil
}

// KLLSketchEncodingValue returns an OTLP KLLSketchEncoding generated from enc.
func KLLSketchEncodingValue(enc metricdata.KLLSketchEncoding) (mpb.KLLSketchEncoding, error) {
	switch enc {
	case metricdata.KLLSketchEncodingGob:
		return mpb.KLLSketchEncoding_KLL_SKETCH_ENCODING_GOB, nil
	default:
		return mpb.KLLSketchEncoding_KLL_SKETCH_ENCODING_UNSPECIFIED, fmt.Errorf("%w: %s", errUnknownKLLSketchEncoding, enc)
	}
}

// CountSketch returns an OTLP Metric_Countsketch generated from c. An error is
// returned if the temporality of c is unknown.
func CountSketch[N int64 | float64](c metricdata.CountSketch[N]) (*mpb.Metric_Countsketch, error) {
	t, err := Temporality(c.Temporality)
	if err != nil {
		return nil, err
	}
	dPts, err := CountSketchDataPoints(c.DataPoints)
	if err != nil {
		return nil, err
	}
	return &mpb.Metric_Countsketch{
		Countsketch: &mpb.CountSketch{
			AggregationTemporality: t,
			DataPoints:             dPts,
		},
	}, nil
}

// CountSketchDataPoints returns a slice of OTLP CountSketchDataPoint generated from dPts.
func CountSketchDataPoints[N int64 | float64](
	dPts []metricdata.CountSketchDataPoint[N],
) ([]*mpb.CountSketchDataPoint, error) {
	out := make([]*mpb.CountSketchDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		encoding, err := CountSketchEncodingValue(dPt.Encoding)
		if err != nil {
			return nil, err
		}

		dp := &mpb.CountSketchDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			Sketch:            dPt.Sketch,
			Encoding:          encoding,
			Dimension:         dPt.Dimension,
			Epsilon:           dPt.Epsilon,
			Delta:             dPt.Delta,
		}
		out = append(out, dp)
	}
	return out, nil
}

// CountSketchEncodingValue returns an OTLP CountSketchEncoding generated from enc.
func CountSketchEncodingValue(enc metricdata.CountSketchEncoding) (mpb.CountSketchEncoding, error) {
	switch enc {
	case metricdata.CountSketchEncodingGob:
		return mpb.CountSketchEncoding_COUNT_SKETCH_ENCODING_GOB, nil
	default:
		return mpb.CountSketchEncoding_COUNT_SKETCH_ENCODING_UNSPECIFIED, fmt.Errorf("%w: %s", errUnknownCountSketchEncoding, enc)
	}
}

// CountMinSketch returns an OTLP Metric_Countminsketch generated from c. An error is
// returned if the temporality of c is unknown.
func CountMinSketch[N int64 | float64](c metricdata.CountMinSketch[N]) (*mpb.Metric_Countminsketch, error) {
	t, err := Temporality(c.Temporality)
	if err != nil {
		return nil, err
	}
	dPts, err := CountMinSketchDataPoints(c.DataPoints)
	if err != nil {
		return nil, err
	}
	return &mpb.Metric_Countminsketch{
		Countminsketch: &mpb.CountMinSketch{
			AggregationTemporality: t,
			DataPoints:             dPts,
		},
	}, nil
}

// CountMinSketchDataPoints returns a slice of OTLP CountMinSketchDataPoint generated from dPts.
func CountMinSketchDataPoints[N int64 | float64](
	dPts []metricdata.CountMinSketchDataPoint[N],
) ([]*mpb.CountMinSketchDataPoint, error) {
	out := make([]*mpb.CountMinSketchDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		encoding, err := CountMinSketchEncodingValue(dPt.Encoding)
		if err != nil {
			return nil, err
		}

		dp := &mpb.CountMinSketchDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			SampleCount:       dPt.SampleCount,
			Sketch:            dPt.Sketch,
			Encoding:          encoding,
			Rows:              dPt.Rows,
			Cols:              dPt.Cols,
		}
		out = append(out, dp)
	}
	return out, nil
}

// CountMinSketchEncodingValue returns an OTLP CountMinSketchEncoding generated from enc.
func CountMinSketchEncodingValue(enc metricdata.CountMinSketchEncoding) (mpb.CountMinSketchEncoding, error) {
	switch enc {
	case metricdata.CountMinSketchEncodingGob:
		return mpb.CountMinSketchEncoding_COUNT_MIN_SKETCH_ENCODING_GOB, nil
	default:
		return mpb.CountMinSketchEncoding_COUNT_MIN_SKETCH_ENCODING_UNSPECIFIED, fmt.Errorf("%w: %s", errUnknownCountMinSketchEncoding, enc)
	}
}

// HLLSketch returns an OTLP Metric_Hllsketch generated from h. An error is
// returned if the temporality of h is unknown.
func HLLSketch(h metricdata.HLLSketch) (*mpb.Metric_Hllsketch, error) {
	t, err := Temporality(h.Temporality)
	if err != nil {
		return nil, err
	}
	dPts, err := HLLSketchDataPoints(h.DataPoints)
	if err != nil {
		return nil, err
	}
	return &mpb.Metric_Hllsketch{
		Hllsketch: &mpb.HLLSketch{
			AggregationTemporality: t,
			DataPoints:             dPts,
		},
	}, nil
}

// HLLSketchDataPoints returns a slice of OTLP HLLSketchDataPoint generated from dPts.
func HLLSketchDataPoints(
	dPts []metricdata.HLLSketchDataPoint,
) ([]*mpb.HLLSketchDataPoint, error) {
	out := make([]*mpb.HLLSketchDataPoint, 0, len(dPts))
	for _, dPt := range dPts {
		encoding, err := HLLSketchEncodingValue(dPt.Encoding)
		if err != nil {
			return nil, err
		}

		dp := &mpb.HLLSketchDataPoint{
			Attributes:        AttrIter(dPt.Attributes.Iter()),
			StartTimeUnixNano: timeUnixNano(dPt.StartTime),
			TimeUnixNano:      timeUnixNano(dPt.Time),
			Count:             dPt.Count,
			Cardinality:       dPt.Cardinality,
			Sketch:            dPt.Sketch,
			Encoding:          encoding,
			Precision:         dPt.Precision,
		}
		out = append(out, dp)
	}
	return out, nil
}

// HLLSketchEncodingValue returns an OTLP HLLSketchEncoding generated from enc.
func HLLSketchEncodingValue(enc metricdata.HLLSketchEncoding) (mpb.HLLSketchEncoding, error) {
	switch enc {
	case metricdata.HLLSketchEncodingProto:
		return mpb.HLLSketchEncoding_HLL_SKETCH_ENCODING_PROTO, nil
	case metricdata.HLLSketchEncodingDelta:
		return mpb.HLLSketchEncoding_HLL_SKETCH_ENCODING_DELTA, nil
	default:
		return mpb.HLLSketchEncoding_HLL_SKETCH_ENCODING_UNSPECIFIED, fmt.Errorf("%w: %s", errUnknownHLLSketchEncoding, enc)
	}
}
