aggregations:
- aggregationId: 1
  aggregationType: DatasketchesKLL
  aggregationSubType: ''
  labels:
    grouping: [zone]
    rollup: [rack, node, pod]
    aggregated: []
  metric: http_requests_total_latency_ms_kll
  parameters:
    K: 200
  windowSize: 30
  windowType: tumbling
  spatialFilter: ''
- aggregationId: 2
  aggregationType: DatasketchesKLL
  aggregationSubType: ''
  labels:
    grouping: [zone]
    rollup: [rack, node, pod]
    aggregated: []
  metric: http_requests_total_kll
  parameters:
    K: 200
  windowSize: 30
  windowType: tumbling
  spatialFilter: ''
metrics:
  http_requests_total_latency_ms_kll:
    - zone
    - rack
    - node
    - pod
  http_requests_total_kll:
    - zone
    - rack
    - node
    - pod
