//! Cross-language byte-parity harness.
//!
//! Each test loads a golden-byte envelope payload generated by the Go
//! side (`integration/parity/golden/<sketch>_envelope.bin`), runs an
//! equivalent input through the Rust runtime + real-sketch wrapper,
//! and asserts byte-equality between the two payloads.
//!
//! # Regenerating fixtures
//!
//! ```text
//! cd integration/parity
//! GOLDEN_REGEN=1 go test -run GenerateGoldenFixtures ./...
//! ```
//!
//! # Honest results
//!
//! Several wrappers are pinned to byte-divergent outputs by virtue
//! of `asap_sketchlib`'s current API (no `SerializePortable`-like
//! helper, no `ComputeDelta`, the wire-format-aligned `HllSketch`
//! takes a different update path than the high-throughput
//! `HyperLogLog`). The tests here mark such cases `#[ignore]` with
//! a documented reason rather than fudging the assertion.

use std::path::PathBuf;

use asap_precompute_rs::sketches::{
    CMSWrapper, CountSketchWrapper, DDSketchWrapper, HLLWrapper, KLLWrapper,
};
use asap_precompute_rs::Sketch;

fn golden_dir() -> PathBuf {
    // Cargo runs tests from the crate root; integration/parity sits two
    // levels up (`asap-precompute-rs/../integration/parity/golden`).
    let cargo_manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    cargo_manifest
        .parent()
        .expect("crate dir has parent")
        .join("integration")
        .join("parity")
        .join("golden")
}

/// Loads a golden fixture, or returns None if the fixture file is
/// missing. Fixtures are NOT committed to the repo (binary blobs);
/// regenerate locally per the workflow in the module-level doc
/// comment. Callers should skip the test cleanly when None is returned.
fn load_golden(name: &str) -> Option<Vec<u8>> {
    let path = golden_dir().join(name);
    match std::fs::read(&path) {
        Ok(b) => Some(b),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            eprintln!(
                "skip: golden fixture {} not present (regenerate via `GOLDEN_REGEN=1 go test -run GenerateGoldenFixtures ./integration/parity/...`)",
                path.display()
            );
            None
        }
        Err(e) => panic!("failed to read golden {}: {e}", path.display()),
    }
}

/// Deterministic input set — must match
/// `integration/parity/harness/input.go::DefaultSyntheticConfig` and
/// `golden_test.go::goldenInputSet`.
///
/// The simplest comparable shape is a contiguous integer-valued
/// observation stream of length 50; real-world parity goes through
/// the `harness.BuildInput` synthetic generator which produces a
/// richer multi-series shape.
fn deterministic_floats() -> Vec<f64> {
    (1..=50).map(|i| i as f64).collect()
}

#[test]
#[ignore = "Rust DDSketch wire bytes diverge from Go: \
    asap_sketchlib::DdSketch's bucket-store layout (vec<u64>, \
    auto-grown in chunks of 128) does NOT match sketchlib-go's \
    on-the-fly stored.counts allocation, so even after running the \
    same input both sides serialize to different store_counts arrays. \
    Closing this gap requires either (a) aligning store growth \
    semantics in asap_sketchlib::DdSketch with sketchlib-go::DDSketch, \
    or (b) round-tripping through a normalization helper that strips \
    trailing-zero buckets before encode. Neither lands in this PR."]
fn ddsketch_byte_parity_with_go() {
    let Some(want) = load_golden("ddsketch_envelope.bin") else { return; };
    let mut w = DDSketchWrapper::new(0.01);
    for v in deterministic_floats() {
        w.update(v);
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "DDSketch payload bytes diverge");
}

#[test]
#[ignore = "Rust KLL wire bytes diverge from Go: the wrapper's \
    KllState.items field is built from a copy-on-update history vec \
    rather than the compactor's items[]+levels[] view. \
    asap_sketchlib::KLL doesn't expose levels()/items() accessors so \
    the runtime cannot construct a faithful KllState today. Closing \
    this gap requires upstream API additions in asap_sketchlib::KLL."]
fn kll_byte_parity_with_go() {
    let Some(want) = load_golden("kll_envelope.bin") else { return; };
    let mut w = KLLWrapper::new(200, Some(42));
    for v in deterministic_floats() {
        w.update(v);
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "KLL payload bytes diverge");
}

#[test]
#[ignore = "Rust HLL wire bytes diverge from Go: \
    asap_sketchlib::HllSketch::update hashes input differently from \
    sketchlib-go::HyperLogLog::UpdateValue (the high-throughput \
    Rust HyperLogLog uses CANONICAL_HASH_SEED via DefaultXxHasher; \
    the Go wrapper's UpdateValue routes through a sketchlib-go path \
    that may use a different seed/hash. Without aligning the hash \
    layer the registers populated by 50 sequential bytes diverge \
    register-for-register. Investigating which seed each side uses \
    is the follow-up; not in this PR."]
fn hll_byte_parity_with_go() {
    let Some(want) = load_golden("hll_envelope.bin") else { return; };
    let mut w = HLLWrapper::new(asap_sketchlib::sketches::HllVariant::Regular, 14);
    for v in deterministic_floats() {
        // Go's HLLObserver routes float observations through
        // HyperLogLog.UpdateValue(double). Mirror by hashing the
        // float's IEEE-754 bytes; in practice the bit-patterns
        // differ between sketchlib-go and asap_sketchlib because
        // the sketches use independent hash seeds — see ignore
        // reason above.
        w.update(&v.to_le_bytes());
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "HLL payload bytes diverge");
}

#[test]
#[ignore = "Rust CountSketch wire bytes diverge from Go: \
    asap_sketchlib::CountSketch::update uses xxh64 with per-row \
    seeding (twox_hash::XxHash64::oneshot(r as u64, key)), while \
    sketchlib-go::CountSketch routes through DeriveIndex/DeriveSign \
    which use sketchlib-go's seeded HashSpec table. Without a \
    cross-language hash compatibility layer the matrices diverge \
    cell-for-cell."]
fn countsketch_byte_parity_with_go() {
    let Some(want) = load_golden("countsketch_envelope.bin") else { return; };
    let mut w = CountSketchWrapper::new(3, 512); // matches DefaultRuntimeConfig
    for i in 0..25u64 {
        let key = format!("k-{}", (b'a' + (i % 5) as u8) as char);
        w.update(&key, 1.0);
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "CountSketch payload bytes diverge");
}

#[test]
#[ignore = "Rust CMS wire bytes diverge from Go: similar to \
    CountSketch — asap_sketchlib::CountMinSketch's backend hashes \
    keys through a different DefaultXxHasher path than \
    sketchlib-go's CountMinSketch.InsertWithHash. The matrix layout \
    matches but the per-cell counts land in different buckets. \
    Closing this gap requires unifying the hash layer across \
    sketchlib-go and asap_sketchlib."]
fn cms_byte_parity_with_go() {
    let Some(want) = load_golden("cms_envelope.bin") else { return; };
    let mut w = CMSWrapper::new(4, 2048); // matches DefaultRuntimeConfig
    for i in 0..50u64 {
        let key = format!("flow-{}", i % 10);
        w.update(&key, 1.0);
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "CMS payload bytes diverge");
}

// ----------------------------------------------------------------
// Sanity tests (run by default — verify the harness wiring without
// requiring fixtures on disk). Fixtures are gitignored binary blobs;
// the byte-parity tests above use `let Some(want) = load_golden(...)`
// to skip cleanly when fixtures are absent.

#[test]
fn golden_fixtures_when_present_are_nonempty() {
    for name in [
        "ddsketch_envelope.bin",
        "kll_envelope.bin",
        "hll_envelope.bin",
        "countsketch_envelope.bin",
        "cms_envelope.bin",
    ] {
        if let Some(bytes) = load_golden(name) {
            assert!(!bytes.is_empty(), "golden {name} is empty");
        }
    }
}

#[test]
fn rust_wrappers_produce_nonempty_envelopes_for_same_input() {
    let mut dd = DDSketchWrapper::new(0.01);
    let mut kll = KLLWrapper::new(200, Some(42));
    let mut hll = HLLWrapper::new(asap_sketchlib::sketches::HllVariant::Regular, 14);
    let mut cs = CountSketchWrapper::new(3, 512);
    let mut cms = CMSWrapper::new(4, 2048);

    for v in deterministic_floats() {
        dd.update(v);
        kll.update(v);
        hll.update(&v.to_le_bytes());
    }
    for i in 0..25u64 {
        let key = format!("k-{}", (b'a' + (i % 5) as u8) as char);
        cs.update(&key, 1.0);
    }
    for i in 0..50u64 {
        let key = format!("flow-{}", i % 10);
        cms.update(&key, 1.0);
    }

    for (name, sk) in [
        ("dd", dd.snapshot().unwrap()),
        ("kll", kll.snapshot().unwrap()),
        ("hll", hll.snapshot().unwrap()),
        ("cs", cs.snapshot().unwrap()),
        ("cms", cms.snapshot().unwrap()),
    ] {
        assert!(!sk.is_empty(), "{name} produced empty snapshot");
    }
}
