//! Cross-language byte-parity harness.
//!
//! Each test loads a golden-byte envelope payload generated by the Go
//! side (`integration/parity/golden/<sketch>_envelope.bin`), runs an
//! equivalent input through the Rust runtime + real-sketch wrapper,
//! and asserts byte-equality between the two payloads.
//!
//! # Regenerating fixtures
//!
//! ```text
//! cd integration/parity
//! GOLDEN_REGEN=1 go test -run GenerateGoldenFixtures ./...
//! ```
//!
//! # Honest results
//!
//! Several wrappers are pinned to byte-divergent outputs by virtue
//! of `asap_sketchlib`'s current API (no `SerializePortable`-like
//! helper, no `ComputeDelta`, the wire-format-aligned `HllSketch`
//! takes a different update path than the high-throughput
//! `HyperLogLog`). The tests here mark such cases `#[ignore]` with
//! a documented reason rather than fudging the assertion.

use std::path::PathBuf;

use asap_precompute_rs::sketches::{
    CMSWrapper, CountSketchWrapper, DDSketchWrapper, HLLWrapper, KLLWrapper,
};
use asap_precompute_rs::Sketch;

fn golden_dir() -> PathBuf {
    // Cargo runs tests from the crate root; integration/parity sits two
    // levels up (`asap-precompute-rs/../integration/parity/golden`).
    let cargo_manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    cargo_manifest
        .parent()
        .expect("crate dir has parent")
        .join("integration")
        .join("parity")
        .join("golden")
}

/// Loads a golden fixture, or returns None if the fixture file is
/// missing. Fixtures are NOT committed to the repo (binary blobs);
/// regenerate locally per the workflow in the module-level doc
/// comment. Callers should skip the test cleanly when None is returned.
fn load_golden(name: &str) -> Option<Vec<u8>> {
    let path = golden_dir().join(name);
    match std::fs::read(&path) {
        Ok(b) => Some(b),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            eprintln!(
                "skip: golden fixture {} not present (regenerate via `GOLDEN_REGEN=1 go test -run GenerateGoldenFixtures ./integration/parity/...`)",
                path.display()
            );
            None
        }
        Err(e) => panic!("failed to read golden {}: {e}", path.display()),
    }
}

/// Deterministic input set — must match
/// `integration/parity/harness/input.go::DefaultSyntheticConfig` and
/// `golden_test.go::goldenInputSet`.
///
/// The simplest comparable shape is a contiguous integer-valued
/// observation stream of length 50; real-world parity goes through
/// the `harness.BuildInput` synthetic generator which produces a
/// richer multi-series shape.
fn deterministic_floats() -> Vec<f64> {
    (1..=50).map(|i| i as f64).collect()
}

#[test]
fn ddsketch_byte_parity_with_go() {
    let Some(want) = load_golden("ddsketch_envelope.bin") else { return; };
    let mut w = DDSketchWrapper::new(0.01);
    for v in deterministic_floats() {
        w.update(v);
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "DDSketch payload bytes diverge");
}

#[test]
fn kll_byte_parity_with_go() {
    let Some(want) = load_golden("kll_envelope.bin") else { return; };
    let mut w = KLLWrapper::new(200, Some(42));
    for v in deterministic_floats() {
        w.update(v);
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "KLL payload bytes diverge");
}

#[test]
fn hll_byte_parity_with_go() {
    let Some(want) = load_golden("hll_envelope.bin") else { return; };
    // sketchlib-go::HyperLogLog.SerializePortable emits
    // HLL_VARIANT_DATAFUSION (= proto enum value 2 = `HllVariant::Datafusion`
    // in asap_sketchlib's enum naming). Construct the Rust wrapper with
    // the matching variant so the proto envelope bytes align with Go's.
    // Both producers reach `insert_with_hash` with the same `u64` because
    // `sketchlib-go::common.FromBytes` and `asap_sketchlib::HllSketch::update`
    // both route through `xxh3_64(seed=seedList[CanonicalHashSeed=5], key)`.
    let mut w = HLLWrapper::new(asap_sketchlib::wrapper::HllVariant::Datafusion, 14);
    for v in deterministic_floats() {
        // Go's HLLObserver routes float observations through
        // HyperLogLog.UpdateValue(double). Mirror by hashing the
        // float's IEEE-754 little-endian bytes — golden_test.go's
        // `goldenHllKeys` does the same on the Go side.
        w.update(&v.to_le_bytes());
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "HLL payload bytes diverge");
}

#[test]
fn countsketch_byte_parity_with_go() {
    let Some(want) = load_golden("countsketch_envelope.bin") else { return; };
    let mut w = CountSketchWrapper::new(3, 512); // matches DefaultRuntimeConfig
    for i in 0..25u64 {
        let key = format!("k-{}", (b'a' + (i % 5) as u8) as char);
        w.update(&key, 1.0);
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "CountSketch payload bytes diverge");
}

#[test]
fn cms_byte_parity_with_go() {
    let Some(want) = load_golden("cms_envelope.bin") else { return; };
    let mut w = CMSWrapper::new(4, 2048); // matches DefaultRuntimeConfig
    for i in 0..50u64 {
        let key = format!("flow-{}", i % 10);
        w.update(&key, 1.0);
    }
    let got = w.snapshot().expect("snapshot");
    assert_eq!(got, want, "CMS payload bytes diverge");
}

// ----------------------------------------------------------------
// Sanity tests (run by default — verify the harness wiring without
// requiring fixtures on disk). Fixtures are gitignored binary blobs;
// the byte-parity tests above use `let Some(want) = load_golden(...)`
// to skip cleanly when fixtures are absent.

#[test]
fn golden_fixtures_when_present_are_nonempty() {
    for name in [
        "ddsketch_envelope.bin",
        "kll_envelope.bin",
        "hll_envelope.bin",
        "countsketch_envelope.bin",
        "cms_envelope.bin",
    ] {
        if let Some(bytes) = load_golden(name) {
            assert!(!bytes.is_empty(), "golden {name} is empty");
        }
    }
}

#[test]
fn rust_wrappers_produce_nonempty_envelopes_for_same_input() {
    let mut dd = DDSketchWrapper::new(0.01);
    let mut kll = KLLWrapper::new(200, Some(42));
    let mut hll = HLLWrapper::new(asap_sketchlib::wrapper::HllVariant::Regular, 14);
    let mut cs = CountSketchWrapper::new(3, 512);
    let mut cms = CMSWrapper::new(4, 2048);

    for v in deterministic_floats() {
        dd.update(v);
        kll.update(v);
        hll.update(&v.to_le_bytes());
    }
    for i in 0..25u64 {
        let key = format!("k-{}", (b'a' + (i % 5) as u8) as char);
        cs.update(&key, 1.0);
    }
    for i in 0..50u64 {
        let key = format!("flow-{}", i % 10);
        cms.update(&key, 1.0);
    }

    for (name, sk) in [
        ("dd", dd.snapshot().unwrap()),
        ("kll", kll.snapshot().unwrap()),
        ("hll", hll.snapshot().unwrap()),
        ("cs", cs.snapshot().unwrap()),
        ("cms", cms.snapshot().unwrap()),
    ] {
        assert!(!sk.is_empty(), "{name} produced empty snapshot");
    }
}
