aggregations:
- aggregationId: 1
  aggregationType: CountMinSketch
  aggregationSubType: ''
  labels:
    grouping: [zone]
    rollup: [rack, node, pod]
    aggregated: []
  metric: http_requests_total
  parameters:
    d: 5
    w: 1024
  windowSize: 30
  windowType: tumbling
  spatialFilter: ''
metrics:
  http_requests_total:
    - zone
    - rack
    - node
    - pod
