# OTLP Pathway 2 - Batch mode - Local testing
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:53217
      http:
        endpoint: 0.0.0.0:53218

processors:
  KLL:
    mode: batch
    k: 256
    transmit_sketch: true
    quantiles: [0.5, 0.9, 0.99]
    drop_original: true

exporters:
  otlphttp:
    endpoint: http://localhost:4318
    encoding: proto
    compression: gzip
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [KLL]
      exporters: [otlphttp]
  telemetry:
    metrics:
      level: basic
    logs:
      level: debug
    resource:
      service.name: kllcol-otlp-pathway2-local
