// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestSumAggDataPoint_MoveTo(t *testing.T) {
	ms := generateTestSumAggDataPoint()
	dest := NewSumAggDataPoint()
	ms.MoveTo(dest)
	assert.Equal(t, NewSumAggDataPoint(), ms)
	assert.Equal(t, generateTestSumAggDataPoint(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestSumAggDataPoint(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newSumAggDataPoint(internal.NewSumAggDataPoint(), sharedState)) })
	assert.Panics(t, func() { newSumAggDataPoint(internal.NewSumAggDataPoint(), sharedState).MoveTo(dest) })
}

func TestSumAggDataPoint_CopyTo(t *testing.T) {
	ms := NewSumAggDataPoint()
	orig := NewSumAggDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestSumAggDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newSumAggDataPoint(internal.NewSumAggDataPoint(), sharedState)) })
}

func TestSumAggDataPoint_Attributes(t *testing.T) {
	ms := NewSumAggDataPoint()
	assert.Equal(t, pcommon.NewMap(), ms.Attributes())
	ms.orig.Attributes = internal.GenTestKeyValueSlice()
	assert.Equal(t, pcommon.Map(internal.GenTestMapWrapper()), ms.Attributes())
}

func TestSumAggDataPoint_SeriesID(t *testing.T) {
	ms := NewSumAggDataPoint()
	assert.Equal(t, uint64(0), ms.SeriesID())
	ms.SetSeriesID(uint64(13))
	assert.Equal(t, uint64(13), ms.SeriesID())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newSumAggDataPoint(internal.NewSumAggDataPoint(), sharedState).SetSeriesID(uint64(13)) })
}

func TestSumAggDataPoint_StartTimestamp(t *testing.T) {
	ms := NewSumAggDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.StartTimestamp())
	testValStartTimestamp := pcommon.Timestamp(1234567890)
	ms.SetStartTimestamp(testValStartTimestamp)
	assert.Equal(t, testValStartTimestamp, ms.StartTimestamp())
}

func TestSumAggDataPoint_Timestamp(t *testing.T) {
	ms := NewSumAggDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.Timestamp())
	testValTimestamp := pcommon.Timestamp(1234567890)
	ms.SetTimestamp(testValTimestamp)
	assert.Equal(t, testValTimestamp, ms.Timestamp())
}

func TestSumAggDataPoint_Sketch(t *testing.T) {
	ms := NewSumAggDataPoint()
	assert.Equal(t, nil, ms.Sketch())
	ms.SetSketch([]byte{1, 2, 3})
	assert.Equal(t, []byte{1, 2, 3}, ms.Sketch())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newSumAggDataPoint(internal.NewSumAggDataPoint(), sharedState).SetSketch([]byte{1, 2, 3}) })
}

func TestSumAggDataPoint_Encoding(t *testing.T) {
	ms := NewSumAggDataPoint()
	assert.Equal(t, SumAggEncoding(internal.SumAggEncoding(0)), ms.Encoding())
	testValEncoding := SumAggEncoding(internal.SumAggEncoding(1))
	ms.SetEncoding(testValEncoding)
	assert.Equal(t, testValEncoding, ms.Encoding())
}

func TestSumAggDataPoint_Exemplars(t *testing.T) {
	ms := NewSumAggDataPoint()
	assert.Equal(t, NewExemplarSlice(), ms.Exemplars())
	ms.orig.Exemplars = internal.GenTestExemplarSlice()
	assert.Equal(t, generateTestExemplarSlice(), ms.Exemplars())
}

func TestSumAggDataPoint_Flags(t *testing.T) {
	ms := NewSumAggDataPoint()
	assert.Equal(t, DataPointFlags(0), ms.Flags())
	testValFlags := DataPointFlags(1)
	ms.SetFlags(testValFlags)
	assert.Equal(t, testValFlags, ms.Flags())
}

func generateTestSumAggDataPoint() SumAggDataPoint {
	return newSumAggDataPoint(internal.GenTestSumAggDataPoint(), internal.NewState())
}
