// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// HLLSketch represents the type of a metric encoded with the HyperLogLog sketch data structure.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewHLLSketch function to create new instances.
// Important: zero-initialized instance is not valid for use.
type HLLSketch struct {
	orig  *internal.HLLSketch
	state *internal.State
}

func newHLLSketch(orig *internal.HLLSketch, state *internal.State) HLLSketch {
	return HLLSketch{orig: orig, state: state}
}

// NewHLLSketch creates a new empty HLLSketch.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewHLLSketch() HLLSketch {
	return newHLLSketch(internal.NewHLLSketch(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms HLLSketch) MoveTo(dest HLLSketch) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteHLLSketch(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// DataPoints returns the DataPoints associated with this HLLSketch.
func (ms HLLSketch) DataPoints() HLLSketchDataPointSlice {
	return newHLLSketchDataPointSlice(&ms.orig.DataPoints, ms.state)
}

// AggregationTemporality returns the aggregationtemporality associated with this HLLSketch.
func (ms HLLSketch) AggregationTemporality() AggregationTemporality {
	return AggregationTemporality(ms.orig.AggregationTemporality)
}

// SetAggregationTemporality replaces the aggregationtemporality associated with this HLLSketch.
func (ms HLLSketch) SetAggregationTemporality(v AggregationTemporality) {
	ms.state.AssertMutable()
	ms.orig.AggregationTemporality = internal.AggregationTemporality(v)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms HLLSketch) CopyTo(dest HLLSketch) {
	dest.state.AssertMutable()
	internal.CopyHLLSketch(dest.orig, ms.orig)
}
