// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// CountSketchDataPoint is a single data point that encodes frequency estimations using CountSketch.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewCountSketchDataPoint function to create new instances.
// Important: zero-initialized instance is not valid for use.
type CountSketchDataPoint struct {
	orig  *internal.CountSketchDataPoint
	state *internal.State
}

func newCountSketchDataPoint(orig *internal.CountSketchDataPoint, state *internal.State) CountSketchDataPoint {
	return CountSketchDataPoint{orig: orig, state: state}
}

// NewCountSketchDataPoint creates a new empty CountSketchDataPoint.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewCountSketchDataPoint() CountSketchDataPoint {
	return newCountSketchDataPoint(internal.NewCountSketchDataPoint(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms CountSketchDataPoint) MoveTo(dest CountSketchDataPoint) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteCountSketchDataPoint(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// Attributes returns the Attributes associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) Attributes() pcommon.Map {
	return pcommon.Map(internal.NewMapWrapper(&ms.orig.Attributes, ms.state))
}

// SeriesID returns the seriesid associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SeriesID() uint64 {
	return ms.orig.SeriesID
}

// SetSeriesID replaces the seriesid associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetSeriesID(v uint64) {
	ms.state.AssertMutable()
	ms.orig.SeriesID = v
}

// StartTimestamp returns the starttimestamp associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) StartTimestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.StartTimeUnixNano)
}

// SetStartTimestamp replaces the starttimestamp associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetStartTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.StartTimeUnixNano = uint64(v)
}

// Timestamp returns the timestamp associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) Timestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.TimeUnixNano)
}

// SetTimestamp replaces the timestamp associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.TimeUnixNano = uint64(v)
}

// Sketch returns the sketch associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) Sketch() []byte {
	return ms.orig.Sketch
}

// SetSketch replaces the sketch associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetSketch(v []byte) {
	ms.state.AssertMutable()
	ms.orig.Sketch = v
}

// Encoding returns the encoding associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) Encoding() CountSketchEncoding {
	return CountSketchEncoding(ms.orig.Encoding)
}

// SetEncoding replaces the encoding associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetEncoding(v CountSketchEncoding) {
	ms.state.AssertMutable()
	ms.orig.Encoding = internal.CountSketchEncoding(v)
}

// Dimension returns the dimension associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) Dimension() string {
	return ms.orig.Dimension
}

// SetDimension replaces the dimension associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetDimension(v string) {
	ms.state.AssertMutable()
	ms.orig.Dimension = v
}

// Epsilon returns the epsilon associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) Epsilon() float64 {
	return ms.orig.Epsilon
}

// SetEpsilon replaces the epsilon associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetEpsilon(v float64) {
	ms.state.AssertMutable()
	ms.orig.Epsilon = v
}

// Delta returns the delta associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) Delta() float64 {
	return ms.orig.Delta
}

// SetDelta replaces the delta associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetDelta(v float64) {
	ms.state.AssertMutable()
	ms.orig.Delta = v
}

// Flags returns the flags associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) Flags() DataPointFlags {
	return DataPointFlags(ms.orig.Flags)
}

// SetFlags replaces the flags associated with this CountSketchDataPoint.
func (ms CountSketchDataPoint) SetFlags(v DataPointFlags) {
	ms.state.AssertMutable()
	ms.orig.Flags = uint32(v)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms CountSketchDataPoint) CopyTo(dest CountSketchDataPoint) {
	dest.state.AssertMutable()
	internal.CopyCountSketchDataPoint(dest.orig, ms.orig)
}
