// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestCountMinSketch_MoveTo(t *testing.T) {
	ms := generateTestCountMinSketch()
	dest := NewCountMinSketch()
	ms.MoveTo(dest)
	assert.Equal(t, NewCountMinSketch(), ms)
	assert.Equal(t, generateTestCountMinSketch(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestCountMinSketch(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newCountMinSketch(internal.NewCountMinSketch(), sharedState)) })
	assert.Panics(t, func() { newCountMinSketch(internal.NewCountMinSketch(), sharedState).MoveTo(dest) })
}

func TestCountMinSketch_CopyTo(t *testing.T) {
	ms := NewCountMinSketch()
	orig := NewCountMinSketch()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestCountMinSketch()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newCountMinSketch(internal.NewCountMinSketch(), sharedState)) })
}

func TestCountMinSketch_DataPoints(t *testing.T) {
	ms := NewCountMinSketch()
	assert.Equal(t, NewCountMinSketchDataPointSlice(), ms.DataPoints())
	ms.orig.DataPoints = internal.GenTestCountMinSketchDataPointPtrSlice()
	assert.Equal(t, generateTestCountMinSketchDataPointSlice(), ms.DataPoints())
}

func TestCountMinSketch_AggregationTemporality(t *testing.T) {
	ms := NewCountMinSketch()
	assert.Equal(t, AggregationTemporality(internal.AggregationTemporality(0)), ms.AggregationTemporality())
	testValAggregationTemporality := AggregationTemporality(internal.AggregationTemporality(1))
	ms.SetAggregationTemporality(testValAggregationTemporality)
	assert.Equal(t, testValAggregationTemporality, ms.AggregationTemporality())
}

func TestCountMinSketch_Rows(t *testing.T) {
	ms := NewCountMinSketch()
	assert.Equal(t, int32(0), ms.Rows())
	ms.SetRows(int32(13))
	assert.Equal(t, int32(13), ms.Rows())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newCountMinSketch(internal.NewCountMinSketch(), sharedState).SetRows(int32(13)) })
}

func TestCountMinSketch_Cols(t *testing.T) {
	ms := NewCountMinSketch()
	assert.Equal(t, int32(0), ms.Cols())
	ms.SetCols(int32(13))
	assert.Equal(t, int32(13), ms.Cols())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newCountMinSketch(internal.NewCountMinSketch(), sharedState).SetCols(int32(13)) })
}

func generateTestCountMinSketch() CountMinSketch {
	return newCountMinSketch(internal.GenTestCountMinSketch(), internal.NewState())
}
