// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// SumAgg represents a first-class scalar Sum aggregate (AggregationKind = Sum), carried as a portable {sum,count} envelope in the Sketch bytes. It is NOT a sketch; it rides the modified-OTLP metric data oneof alongside the sketch families so the backend can decode it via the same envelope path (into the ExactAgg(Sum) accumulator).
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewSumAgg function to create new instances.
// Important: zero-initialized instance is not valid for use.
type SumAgg struct {
	orig  *internal.SumAgg
	state *internal.State
}

func newSumAgg(orig *internal.SumAgg, state *internal.State) SumAgg {
	return SumAgg{orig: orig, state: state}
}

// NewSumAgg creates a new empty SumAgg.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewSumAgg() SumAgg {
	return newSumAgg(internal.NewSumAgg(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms SumAgg) MoveTo(dest SumAgg) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteSumAgg(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// DataPoints returns the DataPoints associated with this SumAgg.
func (ms SumAgg) DataPoints() SumAggDataPointSlice {
	return newSumAggDataPointSlice(&ms.orig.DataPoints, ms.state)
}

// AggregationTemporality returns the aggregationtemporality associated with this SumAgg.
func (ms SumAgg) AggregationTemporality() AggregationTemporality {
	return AggregationTemporality(ms.orig.AggregationTemporality)
}

// SetAggregationTemporality replaces the aggregationtemporality associated with this SumAgg.
func (ms SumAgg) SetAggregationTemporality(v AggregationTemporality) {
	ms.state.AssertMutable()
	ms.orig.AggregationTemporality = internal.AggregationTemporality(v)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms SumAgg) CopyTo(dest SumAgg) {
	dest.state.AssertMutable()
	internal.CopySumAgg(dest.orig, ms.orig)
}
