// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// KLLSketchDataPoint is a single data point that encodes a distribution using the KLL sketch format.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewKLLSketchDataPoint function to create new instances.
// Important: zero-initialized instance is not valid for use.
type KLLSketchDataPoint struct {
	orig  *internal.KLLSketchDataPoint
	state *internal.State
}

func newKLLSketchDataPoint(orig *internal.KLLSketchDataPoint, state *internal.State) KLLSketchDataPoint {
	return KLLSketchDataPoint{orig: orig, state: state}
}

// NewKLLSketchDataPoint creates a new empty KLLSketchDataPoint.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewKLLSketchDataPoint() KLLSketchDataPoint {
	return newKLLSketchDataPoint(internal.NewKLLSketchDataPoint(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms KLLSketchDataPoint) MoveTo(dest KLLSketchDataPoint) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteKLLSketchDataPoint(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// Attributes returns the Attributes associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Attributes() pcommon.Map {
	return pcommon.Map(internal.NewMapWrapper(&ms.orig.Attributes, ms.state))
}

// SeriesID returns the seriesid associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SeriesID() uint64 {
	return ms.orig.SeriesID
}

// SetSeriesID replaces the seriesid associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetSeriesID(v uint64) {
	ms.state.AssertMutable()
	ms.orig.SeriesID = v
}

// StartTimestamp returns the starttimestamp associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) StartTimestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.StartTimeUnixNano)
}

// SetStartTimestamp replaces the starttimestamp associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetStartTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.StartTimeUnixNano = uint64(v)
}

// Timestamp returns the timestamp associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Timestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.TimeUnixNano)
}

// SetTimestamp replaces the timestamp associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.TimeUnixNano = uint64(v)
}

// Count returns the count associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Count() uint64 {
	return ms.orig.Count
}

// SetCount replaces the count associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetCount(v uint64) {
	ms.state.AssertMutable()
	ms.orig.Count = v
}

// Sum returns the sum associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Sum() float64 {
	return ms.orig.Sum
}

// SetSum replaces the sum associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetSum(v float64) {
	ms.state.AssertMutable()
	ms.orig.Sum = v
}

// Min returns the min associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Min() float64 {
	return ms.orig.Min
}

// SetMin replaces the min associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetMin(v float64) {
	ms.state.AssertMutable()
	ms.orig.Min = v
}

// Max returns the max associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Max() float64 {
	return ms.orig.Max
}

// SetMax replaces the max associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetMax(v float64) {
	ms.state.AssertMutable()
	ms.orig.Max = v
}

// Sketch returns the sketch associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Sketch() []byte {
	return ms.orig.Sketch
}

// SetSketch replaces the sketch associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetSketch(v []byte) {
	ms.state.AssertMutable()
	ms.orig.Sketch = v
}

// Encoding returns the encoding associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Encoding() KLLSketchEncoding {
	return KLLSketchEncoding(ms.orig.Encoding)
}

// SetEncoding replaces the encoding associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetEncoding(v KLLSketchEncoding) {
	ms.state.AssertMutable()
	ms.orig.Encoding = internal.KLLSketchEncoding(v)
}

// Flags returns the flags associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) Flags() DataPointFlags {
	return DataPointFlags(ms.orig.Flags)
}

// SetFlags replaces the flags associated with this KLLSketchDataPoint.
func (ms KLLSketchDataPoint) SetFlags(v DataPointFlags) {
	ms.state.AssertMutable()
	ms.orig.Flags = uint32(v)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms KLLSketchDataPoint) CopyTo(dest KLLSketchDataPoint) {
	dest.state.AssertMutable()
	internal.CopyKLLSketchDataPoint(dest.orig, ms.orig)
}
