// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestCountSketchDataPoint_MoveTo(t *testing.T) {
	ms := generateTestCountSketchDataPoint()
	dest := NewCountSketchDataPoint()
	ms.MoveTo(dest)
	assert.Equal(t, NewCountSketchDataPoint(), ms)
	assert.Equal(t, generateTestCountSketchDataPoint(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestCountSketchDataPoint(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newCountSketchDataPoint(internal.NewCountSketchDataPoint(), sharedState)) })
	assert.Panics(t, func() { newCountSketchDataPoint(internal.NewCountSketchDataPoint(), sharedState).MoveTo(dest) })
}

func TestCountSketchDataPoint_CopyTo(t *testing.T) {
	ms := NewCountSketchDataPoint()
	orig := NewCountSketchDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestCountSketchDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newCountSketchDataPoint(internal.NewCountSketchDataPoint(), sharedState)) })
}

func TestCountSketchDataPoint_Attributes(t *testing.T) {
	ms := NewCountSketchDataPoint()
	assert.Equal(t, pcommon.NewMap(), ms.Attributes())
	ms.orig.Attributes = internal.GenTestKeyValueSlice()
	assert.Equal(t, pcommon.Map(internal.GenTestMapWrapper()), ms.Attributes())
}

func TestCountSketchDataPoint_StartTimestamp(t *testing.T) {
	ms := NewCountSketchDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.StartTimestamp())
	testValStartTimestamp := pcommon.Timestamp(1234567890)
	ms.SetStartTimestamp(testValStartTimestamp)
	assert.Equal(t, testValStartTimestamp, ms.StartTimestamp())
}

func TestCountSketchDataPoint_Timestamp(t *testing.T) {
	ms := NewCountSketchDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.Timestamp())
	testValTimestamp := pcommon.Timestamp(1234567890)
	ms.SetTimestamp(testValTimestamp)
	assert.Equal(t, testValTimestamp, ms.Timestamp())
}

func TestCountSketchDataPoint_Sketch(t *testing.T) {
	ms := NewCountSketchDataPoint()
	assert.Equal(t, nil, ms.Sketch())
	ms.SetSketch([]byte{1, 2, 3})
	assert.Equal(t, []byte{1, 2, 3}, ms.Sketch())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newCountSketchDataPoint(internal.NewCountSketchDataPoint(), sharedState).SetSketch([]byte{1, 2, 3})
	})
}

func TestCountSketchDataPoint_Encoding(t *testing.T) {
	ms := NewCountSketchDataPoint()
	assert.Equal(t, CountSketchEncoding(internal.CountSketchEncoding(0)), ms.Encoding())
	testValEncoding := CountSketchEncoding(internal.CountSketchEncoding(1))
	ms.SetEncoding(testValEncoding)
	assert.Equal(t, testValEncoding, ms.Encoding())
}

func TestCountSketchDataPoint_Flags(t *testing.T) {
	ms := NewCountSketchDataPoint()
	assert.Equal(t, DataPointFlags(0), ms.Flags())
	testValFlags := DataPointFlags(1)
	ms.SetFlags(testValFlags)
	assert.Equal(t, testValFlags, ms.Flags())
}

func TestCountSketchDataPoint_SeriesID(t *testing.T) {
	ms := NewCountSketchDataPoint()
	assert.Equal(t, uint64(0), ms.SeriesID())
	ms.SetSeriesID(uint64(13))
	assert.Equal(t, uint64(13), ms.SeriesID())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newCountSketchDataPoint(internal.NewCountSketchDataPoint(), sharedState).SetSeriesID(uint64(13))
	})
}

func generateTestCountSketchDataPoint() CountSketchDataPoint {
	return newCountSketchDataPoint(internal.GenTestCountSketchDataPoint(), internal.NewState())
}
