// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestDDSketch_MoveTo(t *testing.T) {
	ms := generateTestDDSketch()
	dest := NewDDSketch()
	ms.MoveTo(dest)
	assert.Equal(t, NewDDSketch(), ms)
	assert.Equal(t, generateTestDDSketch(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestDDSketch(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newDDSketch(internal.NewDDSketch(), sharedState)) })
	assert.Panics(t, func() { newDDSketch(internal.NewDDSketch(), sharedState).MoveTo(dest) })
}

func TestDDSketch_CopyTo(t *testing.T) {
	ms := NewDDSketch()
	orig := NewDDSketch()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestDDSketch()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newDDSketch(internal.NewDDSketch(), sharedState)) })
}

func TestDDSketch_DataPoints(t *testing.T) {
	ms := NewDDSketch()
	assert.Equal(t, NewDDSketchDataPointSlice(), ms.DataPoints())
	ms.orig.DataPoints = internal.GenTestDDSketchDataPointPtrSlice()
	assert.Equal(t, generateTestDDSketchDataPointSlice(), ms.DataPoints())
}

func TestDDSketch_AggregationTemporality(t *testing.T) {
	ms := NewDDSketch()
	assert.Equal(t, AggregationTemporality(internal.AggregationTemporality(0)), ms.AggregationTemporality())
	testValAggregationTemporality := AggregationTemporality(internal.AggregationTemporality(1))
	ms.SetAggregationTemporality(testValAggregationTemporality)
	assert.Equal(t, testValAggregationTemporality, ms.AggregationTemporality())
}

func generateTestDDSketch() DDSketch {
	return newDDSketch(internal.GenTestDDSketch(), internal.NewState())
}
