// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestDDSketchDataPoint_MoveTo(t *testing.T) {
	ms := generateTestDDSketchDataPoint()
	dest := NewDDSketchDataPoint()
	ms.MoveTo(dest)
	assert.Equal(t, NewDDSketchDataPoint(), ms)
	assert.Equal(t, generateTestDDSketchDataPoint(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestDDSketchDataPoint(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState)) })
	assert.Panics(t, func() { newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).MoveTo(dest) })
}

func TestDDSketchDataPoint_CopyTo(t *testing.T) {
	ms := NewDDSketchDataPoint()
	orig := NewDDSketchDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestDDSketchDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState)) })
}

func TestDDSketchDataPoint_Attributes(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, pcommon.NewMap(), ms.Attributes())
	ms.orig.Attributes = internal.GenTestKeyValueSlice()
	assert.Equal(t, pcommon.Map(internal.GenTestMapWrapper()), ms.Attributes())
}

func TestDDSketchDataPoint_StartTimestamp(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.StartTimestamp())
	testValStartTimestamp := pcommon.Timestamp(1234567890)
	ms.SetStartTimestamp(testValStartTimestamp)
	assert.Equal(t, testValStartTimestamp, ms.StartTimestamp())
}

func TestDDSketchDataPoint_Timestamp(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.Timestamp())
	testValTimestamp := pcommon.Timestamp(1234567890)
	ms.SetTimestamp(testValTimestamp)
	assert.Equal(t, testValTimestamp, ms.Timestamp())
}

func TestDDSketchDataPoint_Count(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, uint64(0), ms.Count())
	ms.SetCount(uint64(13))
	assert.Equal(t, uint64(13), ms.Count())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).SetCount(uint64(13)) })
}

func TestDDSketchDataPoint_SumType(t *testing.T) {
	tv := NewDDSketchDataPoint()
	assert.Equal(t, DDSketchDataPointSumTypeEmpty, tv.SumType())
}

func TestDDSketchDataPoint_DoubleSum(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.InDelta(t, float64(0), ms.DoubleSum(), 0.01)
	ms.SetDoubleSum(float64(3.1415926))
	assert.InDelta(t, float64(3.1415926), ms.DoubleSum(), 0.01)
	assert.Equal(t, DDSketchDataPointSumTypeDouble, ms.SumType())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).SetDoubleSum(float64(3.1415926))
	})
}

func TestDDSketchDataPoint_IntSum(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, int64(0), ms.IntSum())
	ms.SetIntSum(int64(13))
	assert.Equal(t, int64(13), ms.IntSum())
	assert.Equal(t, DDSketchDataPointSumTypeInt, ms.SumType())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).SetIntSum(int64(13)) })
}

func TestDDSketchDataPoint_MinType(t *testing.T) {
	tv := NewDDSketchDataPoint()
	assert.Equal(t, DDSketchDataPointMinTypeEmpty, tv.MinType())
}

func TestDDSketchDataPoint_DoubleMin(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.InDelta(t, float64(0), ms.DoubleMin(), 0.01)
	ms.SetDoubleMin(float64(3.1415926))
	assert.InDelta(t, float64(3.1415926), ms.DoubleMin(), 0.01)
	assert.Equal(t, DDSketchDataPointMinTypeDouble, ms.MinType())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).SetDoubleMin(float64(3.1415926))
	})
}

func TestDDSketchDataPoint_IntMin(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, int64(0), ms.IntMin())
	ms.SetIntMin(int64(13))
	assert.Equal(t, int64(13), ms.IntMin())
	assert.Equal(t, DDSketchDataPointMinTypeInt, ms.MinType())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).SetIntMin(int64(13)) })
}

func TestDDSketchDataPoint_MaxType(t *testing.T) {
	tv := NewDDSketchDataPoint()
	assert.Equal(t, DDSketchDataPointMaxTypeEmpty, tv.MaxType())
}

func TestDDSketchDataPoint_DoubleMax(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.InDelta(t, float64(0), ms.DoubleMax(), 0.01)
	ms.SetDoubleMax(float64(3.1415926))
	assert.InDelta(t, float64(3.1415926), ms.DoubleMax(), 0.01)
	assert.Equal(t, DDSketchDataPointMaxTypeDouble, ms.MaxType())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).SetDoubleMax(float64(3.1415926))
	})
}

func TestDDSketchDataPoint_IntMax(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, int64(0), ms.IntMax())
	ms.SetIntMax(int64(13))
	assert.Equal(t, int64(13), ms.IntMax())
	assert.Equal(t, DDSketchDataPointMaxTypeInt, ms.MaxType())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).SetIntMax(int64(13)) })
}

func TestDDSketchDataPoint_Sketch(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, nil, ms.Sketch())
	ms.SetSketch([]byte{1, 2, 3})
	assert.Equal(t, []byte{1, 2, 3}, ms.Sketch())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newDDSketchDataPoint(internal.NewDDSketchDataPoint(), sharedState).SetSketch([]byte{1, 2, 3}) })
}

func TestDDSketchDataPoint_Encoding(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, DDSketchEncoding(internal.DDSketchEncoding(0)), ms.Encoding())
	testValEncoding := DDSketchEncoding(internal.DDSketchEncoding(1))
	ms.SetEncoding(testValEncoding)
	assert.Equal(t, testValEncoding, ms.Encoding())
}

func TestDDSketchDataPoint_Exemplars(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, NewExemplarSlice(), ms.Exemplars())
	ms.orig.Exemplars = internal.GenTestExemplarSlice()
	assert.Equal(t, generateTestExemplarSlice(), ms.Exemplars())
}

func TestDDSketchDataPoint_Flags(t *testing.T) {
	ms := NewDDSketchDataPoint()
	assert.Equal(t, DataPointFlags(0), ms.Flags())
	testValFlags := DataPointFlags(1)
	ms.SetFlags(testValFlags)
	assert.Equal(t, testValFlags, ms.Flags())
}

func generateTestDDSketchDataPoint() DDSketchDataPoint {
	return newDDSketchDataPoint(internal.GenTestDDSketchDataPoint(), internal.NewState())
}
