// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestDDSketchDataPointSlice(t *testing.T) {
	es := NewDDSketchDataPointSlice()
	assert.Equal(t, 0, es.Len())
	es = newDDSketchDataPointSlice(&[]*internal.DDSketchDataPoint{}, internal.NewState())
	assert.Equal(t, 0, es.Len())

	emptyVal := NewDDSketchDataPoint()
	testVal := generateTestDDSketchDataPoint()
	for i := 0; i < 7; i++ {
		es.AppendEmpty()
		assert.Equal(t, emptyVal, es.At(i))
		(*es.orig)[i] = internal.GenTestDDSketchDataPoint()
		assert.Equal(t, testVal, es.At(i))
	}
	assert.Equal(t, 7, es.Len())
}

func TestDDSketchDataPointSliceReadOnly(t *testing.T) {
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	es := newDDSketchDataPointSlice(&[]*internal.DDSketchDataPoint{}, sharedState)
	assert.Equal(t, 0, es.Len())
	assert.Panics(t, func() { es.AppendEmpty() })
	assert.Panics(t, func() { es.EnsureCapacity(2) })
	es2 := NewDDSketchDataPointSlice()
	es.CopyTo(es2)
	assert.Panics(t, func() { es2.CopyTo(es) })
	assert.Panics(t, func() { es.MoveAndAppendTo(es2) })
	assert.Panics(t, func() { es2.MoveAndAppendTo(es) })
}

func TestDDSketchDataPointSlice_CopyTo(t *testing.T) {
	dest := NewDDSketchDataPointSlice()
	src := generateTestDDSketchDataPointSlice()
	src.CopyTo(dest)
	assert.Equal(t, generateTestDDSketchDataPointSlice(), dest)
	dest.CopyTo(dest)
	assert.Equal(t, generateTestDDSketchDataPointSlice(), dest)
}

func TestDDSketchDataPointSlice_EnsureCapacity(t *testing.T) {
	es := generateTestDDSketchDataPointSlice()

	// Test ensure smaller capacity.
	const ensureSmallLen = 4
	es.EnsureCapacity(ensureSmallLen)
	assert.Less(t, ensureSmallLen, es.Len())
	assert.Equal(t, es.Len(), cap(*es.orig))
	assert.Equal(t, generateTestDDSketchDataPointSlice(), es)

	// Test ensure larger capacity
	const ensureLargeLen = 9
	es.EnsureCapacity(ensureLargeLen)
	assert.Less(t, generateTestDDSketchDataPointSlice().Len(), ensureLargeLen)
	assert.Equal(t, ensureLargeLen, cap(*es.orig))
	assert.Equal(t, generateTestDDSketchDataPointSlice(), es)
}

func TestDDSketchDataPointSlice_MoveAndAppendTo(t *testing.T) {
	// Test MoveAndAppendTo to empty
	expectedSlice := generateTestDDSketchDataPointSlice()
	dest := NewDDSketchDataPointSlice()
	src := generateTestDDSketchDataPointSlice()
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestDDSketchDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo empty slice
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestDDSketchDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo not empty slice
	generateTestDDSketchDataPointSlice().MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}

	dest.MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}
}

func TestDDSketchDataPointSlice_RemoveIf(t *testing.T) {
	// Test RemoveIf on empty slice
	emptySlice := NewDDSketchDataPointSlice()
	emptySlice.RemoveIf(func(el DDSketchDataPoint) bool {
		t.Fail()
		return false
	})

	// Test RemoveIf
	filtered := generateTestDDSketchDataPointSlice()
	pos := 0
	filtered.RemoveIf(func(el DDSketchDataPoint) bool {
		pos++
		return pos%2 == 1
	})
	assert.Equal(t, 2, filtered.Len())
}

func TestDDSketchDataPointSlice_RemoveIfAll(t *testing.T) {
	got := generateTestDDSketchDataPointSlice()
	got.RemoveIf(func(el DDSketchDataPoint) bool {
		return true
	})
	assert.Equal(t, 0, got.Len())
}

func TestDDSketchDataPointSliceAll(t *testing.T) {
	ms := generateTestDDSketchDataPointSlice()
	assert.NotEmpty(t, ms.Len())

	var c int
	for i, v := range ms.All() {
		assert.Equal(t, ms.At(i), v, "element should match")
		c++
	}
	assert.Equal(t, ms.Len(), c, "All elements should have been visited")
}

func TestDDSketchDataPointSlice_Sort(t *testing.T) {
	es := generateTestDDSketchDataPointSlice()
	es.Sort(func(a, b DDSketchDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) < uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Less(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
	es.Sort(func(a, b DDSketchDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) > uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Greater(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
}

func generateTestDDSketchDataPointSlice() DDSketchDataPointSlice {
	ms := NewDDSketchDataPointSlice()
	*ms.orig = internal.GenTestDDSketchDataPointPtrSlice()
	return ms
}
