// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// SumAggDataPoint is a single data point carrying a scalar Sum aggregate as a portable {sum,count} envelope in the Sketch bytes.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewSumAggDataPoint function to create new instances.
// Important: zero-initialized instance is not valid for use.
type SumAggDataPoint struct {
	orig  *internal.SumAggDataPoint
	state *internal.State
}

func newSumAggDataPoint(orig *internal.SumAggDataPoint, state *internal.State) SumAggDataPoint {
	return SumAggDataPoint{orig: orig, state: state}
}

// NewSumAggDataPoint creates a new empty SumAggDataPoint.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewSumAggDataPoint() SumAggDataPoint {
	return newSumAggDataPoint(internal.NewSumAggDataPoint(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms SumAggDataPoint) MoveTo(dest SumAggDataPoint) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteSumAggDataPoint(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// Attributes returns the Attributes associated with this SumAggDataPoint.
func (ms SumAggDataPoint) Attributes() pcommon.Map {
	return pcommon.Map(internal.NewMapWrapper(&ms.orig.Attributes, ms.state))
}

// SeriesID returns the seriesid associated with this SumAggDataPoint.
func (ms SumAggDataPoint) SeriesID() uint64 {
	return ms.orig.SeriesID
}

// SetSeriesID replaces the seriesid associated with this SumAggDataPoint.
func (ms SumAggDataPoint) SetSeriesID(v uint64) {
	ms.state.AssertMutable()
	ms.orig.SeriesID = v
}

// StartTimestamp returns the starttimestamp associated with this SumAggDataPoint.
func (ms SumAggDataPoint) StartTimestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.StartTimeUnixNano)
}

// SetStartTimestamp replaces the starttimestamp associated with this SumAggDataPoint.
func (ms SumAggDataPoint) SetStartTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.StartTimeUnixNano = uint64(v)
}

// Timestamp returns the timestamp associated with this SumAggDataPoint.
func (ms SumAggDataPoint) Timestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.TimeUnixNano)
}

// SetTimestamp replaces the timestamp associated with this SumAggDataPoint.
func (ms SumAggDataPoint) SetTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.TimeUnixNano = uint64(v)
}

// Sketch returns the sketch associated with this SumAggDataPoint.
func (ms SumAggDataPoint) Sketch() []byte {
	return ms.orig.Sketch
}

// SetSketch replaces the sketch associated with this SumAggDataPoint.
func (ms SumAggDataPoint) SetSketch(v []byte) {
	ms.state.AssertMutable()
	ms.orig.Sketch = v
}

// Encoding returns the encoding associated with this SumAggDataPoint.
func (ms SumAggDataPoint) Encoding() SumAggEncoding {
	return SumAggEncoding(ms.orig.Encoding)
}

// SetEncoding replaces the encoding associated with this SumAggDataPoint.
func (ms SumAggDataPoint) SetEncoding(v SumAggEncoding) {
	ms.state.AssertMutable()
	ms.orig.Encoding = internal.SumAggEncoding(v)
}

// Exemplars returns the Exemplars associated with this SumAggDataPoint.
func (ms SumAggDataPoint) Exemplars() ExemplarSlice {
	return newExemplarSlice(&ms.orig.Exemplars, ms.state)
}

// Flags returns the flags associated with this SumAggDataPoint.
func (ms SumAggDataPoint) Flags() DataPointFlags {
	return DataPointFlags(ms.orig.Flags)
}

// SetFlags replaces the flags associated with this SumAggDataPoint.
func (ms SumAggDataPoint) SetFlags(v DataPointFlags) {
	ms.state.AssertMutable()
	ms.orig.Flags = uint32(v)
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms SumAggDataPoint) CopyTo(dest SumAggDataPoint) {
	dest.state.AssertMutable()
	internal.CopySumAggDataPoint(dest.orig, ms.orig)
}
