// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// CountMinSketchDataPoint is a single data point that encodes frequency estimations using Count-Min Sketch.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewCountMinSketchDataPoint function to create new instances.
// Important: zero-initialized instance is not valid for use.
type CountMinSketchDataPoint struct {
	orig  *internal.CountMinSketchDataPoint
	state *internal.State
}

func newCountMinSketchDataPoint(orig *internal.CountMinSketchDataPoint, state *internal.State) CountMinSketchDataPoint {
	return CountMinSketchDataPoint{orig: orig, state: state}
}

// NewCountMinSketchDataPoint creates a new empty CountMinSketchDataPoint.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewCountMinSketchDataPoint() CountMinSketchDataPoint {
	return newCountMinSketchDataPoint(internal.NewCountMinSketchDataPoint(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms CountMinSketchDataPoint) MoveTo(dest CountMinSketchDataPoint) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteCountMinSketchDataPoint(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// Attributes returns the Attributes associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) Attributes() pcommon.Map {
	return pcommon.Map(internal.NewMapWrapper(&ms.orig.Attributes, ms.state))
}

// StartTimestamp returns the starttimestamp associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) StartTimestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.StartTimeUnixNano)
}

// SetStartTimestamp replaces the starttimestamp associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) SetStartTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.StartTimeUnixNano = uint64(v)
}

// Timestamp returns the timestamp associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) Timestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.TimeUnixNano)
}

// SetTimestamp replaces the timestamp associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) SetTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.TimeUnixNano = uint64(v)
}

// Sketch returns the sketch associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) Sketch() []byte {
	return ms.orig.Sketch
}

// SetSketch replaces the sketch associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) SetSketch(v []byte) {
	ms.state.AssertMutable()
	ms.orig.Sketch = v
}

// Encoding returns the encoding associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) Encoding() CountMinSketchEncoding {
	return CountMinSketchEncoding(ms.orig.Encoding)
}

// SetEncoding replaces the encoding associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) SetEncoding(v CountMinSketchEncoding) {
	ms.state.AssertMutable()
	ms.orig.Encoding = internal.CountMinSketchEncoding(v)
}

// Flags returns the flags associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) Flags() DataPointFlags {
	return DataPointFlags(ms.orig.Flags)
}

// SetFlags replaces the flags associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) SetFlags(v DataPointFlags) {
	ms.state.AssertMutable()
	ms.orig.Flags = uint32(v)
}

// SeriesID returns the seriesid associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) SeriesID() uint64 {
	return ms.orig.SeriesID
}

// SetSeriesID replaces the seriesid associated with this CountMinSketchDataPoint.
func (ms CountMinSketchDataPoint) SetSeriesID(v uint64) {
	ms.state.AssertMutable()
	ms.orig.SeriesID = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms CountMinSketchDataPoint) CopyTo(dest CountMinSketchDataPoint) {
	dest.state.AssertMutable()
	internal.CopyCountMinSketchDataPoint(dest.orig, ms.orig)
}
