// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// DDSketch represents the type of a metric encoded with the DataDog DDSketch data structure.
// The DDSketch payload holds an approximation of the underlying value distribution and optional extrema/sum tracking, similar to the Sum and Histogram aggregations.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewDDSketch function to create new instances.
// Important: zero-initialized instance is not valid for use.
type DDSketch struct {
	orig  *internal.DDSketch
	state *internal.State
}

func newDDSketch(orig *internal.DDSketch, state *internal.State) DDSketch {
	return DDSketch{orig: orig, state: state}
}

// NewDDSketch creates a new empty DDSketch.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewDDSketch() DDSketch {
	return newDDSketch(internal.NewDDSketch(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms DDSketch) MoveTo(dest DDSketch) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteDDSketch(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// DataPoints returns the DataPoints associated with this DDSketch.
func (ms DDSketch) DataPoints() DDSketchDataPointSlice {
	return newDDSketchDataPointSlice(&ms.orig.DataPoints, ms.state)
}

// AggregationTemporality returns the aggregationtemporality associated with this DDSketch.
func (ms DDSketch) AggregationTemporality() AggregationTemporality {
	return AggregationTemporality(ms.orig.AggregationTemporality)
}

// SetAggregationTemporality replaces the aggregationtemporality associated with this DDSketch.
func (ms DDSketch) SetAggregationTemporality(v AggregationTemporality) {
	ms.state.AssertMutable()
	ms.orig.AggregationTemporality = internal.AggregationTemporality(v)
}

// RelativeAccuracy returns the relativeaccuracy associated with this DDSketch.
func (ms DDSketch) RelativeAccuracy() float64 {
	return ms.orig.RelativeAccuracy
}

// SetRelativeAccuracy replaces the relativeaccuracy associated with this DDSketch.
func (ms DDSketch) SetRelativeAccuracy(v float64) {
	ms.state.AssertMutable()
	ms.orig.RelativeAccuracy = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms DDSketch) CopyTo(dest DDSketch) {
	dest.state.AssertMutable()
	internal.CopyDDSketch(dest.orig, ms.orig)
}
