// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// CountMinSketch represents the type of a metric encoded using the Count-Min Sketch frequency estimation algorithm.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewCountMinSketch function to create new instances.
// Important: zero-initialized instance is not valid for use.
type CountMinSketch struct {
	orig  *internal.CountMinSketch
	state *internal.State
}

func newCountMinSketch(orig *internal.CountMinSketch, state *internal.State) CountMinSketch {
	return CountMinSketch{orig: orig, state: state}
}

// NewCountMinSketch creates a new empty CountMinSketch.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewCountMinSketch() CountMinSketch {
	return newCountMinSketch(internal.NewCountMinSketch(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms CountMinSketch) MoveTo(dest CountMinSketch) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteCountMinSketch(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// DataPoints returns the DataPoints associated with this CountMinSketch.
func (ms CountMinSketch) DataPoints() CountMinSketchDataPointSlice {
	return newCountMinSketchDataPointSlice(&ms.orig.DataPoints, ms.state)
}

// AggregationTemporality returns the aggregationtemporality associated with this CountMinSketch.
func (ms CountMinSketch) AggregationTemporality() AggregationTemporality {
	return AggregationTemporality(ms.orig.AggregationTemporality)
}

// SetAggregationTemporality replaces the aggregationtemporality associated with this CountMinSketch.
func (ms CountMinSketch) SetAggregationTemporality(v AggregationTemporality) {
	ms.state.AssertMutable()
	ms.orig.AggregationTemporality = internal.AggregationTemporality(v)
}

// Rows returns the rows associated with this CountMinSketch.
func (ms CountMinSketch) Rows() int32 {
	return ms.orig.Rows
}

// SetRows replaces the rows associated with this CountMinSketch.
func (ms CountMinSketch) SetRows(v int32) {
	ms.state.AssertMutable()
	ms.orig.Rows = v
}

// Cols returns the cols associated with this CountMinSketch.
func (ms CountMinSketch) Cols() int32 {
	return ms.orig.Cols
}

// SetCols replaces the cols associated with this CountMinSketch.
func (ms CountMinSketch) SetCols(v int32) {
	ms.state.AssertMutable()
	ms.orig.Cols = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms CountMinSketch) CopyTo(dest CountMinSketch) {
	dest.state.AssertMutable()
	internal.CopyCountMinSketch(dest.orig, ms.orig)
}
