// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestHLLSketch_MoveTo(t *testing.T) {
	ms := generateTestHLLSketch()
	dest := NewHLLSketch()
	ms.MoveTo(dest)
	assert.Equal(t, NewHLLSketch(), ms)
	assert.Equal(t, generateTestHLLSketch(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestHLLSketch(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newHLLSketch(internal.NewHLLSketch(), sharedState)) })
	assert.Panics(t, func() { newHLLSketch(internal.NewHLLSketch(), sharedState).MoveTo(dest) })
}

func TestHLLSketch_CopyTo(t *testing.T) {
	ms := NewHLLSketch()
	orig := NewHLLSketch()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestHLLSketch()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newHLLSketch(internal.NewHLLSketch(), sharedState)) })
}

func TestHLLSketch_DataPoints(t *testing.T) {
	ms := NewHLLSketch()
	assert.Equal(t, NewHLLSketchDataPointSlice(), ms.DataPoints())
	ms.orig.DataPoints = internal.GenTestHLLSketchDataPointPtrSlice()
	assert.Equal(t, generateTestHLLSketchDataPointSlice(), ms.DataPoints())
}

func TestHLLSketch_AggregationTemporality(t *testing.T) {
	ms := NewHLLSketch()
	assert.Equal(t, AggregationTemporality(internal.AggregationTemporality(0)), ms.AggregationTemporality())
	testValAggregationTemporality := AggregationTemporality(internal.AggregationTemporality(1))
	ms.SetAggregationTemporality(testValAggregationTemporality)
	assert.Equal(t, testValAggregationTemporality, ms.AggregationTemporality())
}

func TestHLLSketch_Precision(t *testing.T) {
	ms := NewHLLSketch()
	assert.Equal(t, uint32(0), ms.Precision())
	ms.SetPrecision(uint32(13))
	assert.Equal(t, uint32(13), ms.Precision())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newHLLSketch(internal.NewHLLSketch(), sharedState).SetPrecision(uint32(13)) })
}

func generateTestHLLSketch() HLLSketch {
	return newHLLSketch(internal.GenTestHLLSketch(), internal.NewState())
}
