// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// HLLSketchDataPoint is a single data point that encodes cardinality estimations using HyperLogLog.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewHLLSketchDataPoint function to create new instances.
// Important: zero-initialized instance is not valid for use.
type HLLSketchDataPoint struct {
	orig  *internal.HLLSketchDataPoint
	state *internal.State
}

func newHLLSketchDataPoint(orig *internal.HLLSketchDataPoint, state *internal.State) HLLSketchDataPoint {
	return HLLSketchDataPoint{orig: orig, state: state}
}

// NewHLLSketchDataPoint creates a new empty HLLSketchDataPoint.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewHLLSketchDataPoint() HLLSketchDataPoint {
	return newHLLSketchDataPoint(internal.NewHLLSketchDataPoint(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms HLLSketchDataPoint) MoveTo(dest HLLSketchDataPoint) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteHLLSketchDataPoint(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// Attributes returns the Attributes associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) Attributes() pcommon.Map {
	return pcommon.Map(internal.NewMapWrapper(&ms.orig.Attributes, ms.state))
}

// StartTimestamp returns the starttimestamp associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) StartTimestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.StartTimeUnixNano)
}

// SetStartTimestamp replaces the starttimestamp associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) SetStartTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.StartTimeUnixNano = uint64(v)
}

// Timestamp returns the timestamp associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) Timestamp() pcommon.Timestamp {
	return pcommon.Timestamp(ms.orig.TimeUnixNano)
}

// SetTimestamp replaces the timestamp associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) SetTimestamp(v pcommon.Timestamp) {
	ms.state.AssertMutable()
	ms.orig.TimeUnixNano = uint64(v)
}

// Sketch returns the sketch associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) Sketch() []byte {
	return ms.orig.Sketch
}

// SetSketch replaces the sketch associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) SetSketch(v []byte) {
	ms.state.AssertMutable()
	ms.orig.Sketch = v
}

// Encoding returns the encoding associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) Encoding() HLLSketchEncoding {
	return HLLSketchEncoding(ms.orig.Encoding)
}

// SetEncoding replaces the encoding associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) SetEncoding(v HLLSketchEncoding) {
	ms.state.AssertMutable()
	ms.orig.Encoding = internal.HLLSketchEncoding(v)
}

// Flags returns the flags associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) Flags() DataPointFlags {
	return DataPointFlags(ms.orig.Flags)
}

// SetFlags replaces the flags associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) SetFlags(v DataPointFlags) {
	ms.state.AssertMutable()
	ms.orig.Flags = uint32(v)
}

// SeriesID returns the seriesid associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) SeriesID() uint64 {
	return ms.orig.SeriesID
}

// SetSeriesID replaces the seriesid associated with this HLLSketchDataPoint.
func (ms HLLSketchDataPoint) SetSeriesID(v uint64) {
	ms.state.AssertMutable()
	ms.orig.SeriesID = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms HLLSketchDataPoint) CopyTo(dest HLLSketchDataPoint) {
	dest.state.AssertMutable()
	internal.CopyHLLSketchDataPoint(dest.orig, ms.orig)
}
