// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestCountSketchDataPointSlice(t *testing.T) {
	es := NewCountSketchDataPointSlice()
	assert.Equal(t, 0, es.Len())
	es = newCountSketchDataPointSlice(&[]*internal.CountSketchDataPoint{}, internal.NewState())
	assert.Equal(t, 0, es.Len())

	emptyVal := NewCountSketchDataPoint()
	testVal := generateTestCountSketchDataPoint()
	for i := 0; i < 7; i++ {
		es.AppendEmpty()
		assert.Equal(t, emptyVal, es.At(i))
		(*es.orig)[i] = internal.GenTestCountSketchDataPoint()
		assert.Equal(t, testVal, es.At(i))
	}
	assert.Equal(t, 7, es.Len())
}

func TestCountSketchDataPointSliceReadOnly(t *testing.T) {
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	es := newCountSketchDataPointSlice(&[]*internal.CountSketchDataPoint{}, sharedState)
	assert.Equal(t, 0, es.Len())
	assert.Panics(t, func() { es.AppendEmpty() })
	assert.Panics(t, func() { es.EnsureCapacity(2) })
	es2 := NewCountSketchDataPointSlice()
	es.CopyTo(es2)
	assert.Panics(t, func() { es2.CopyTo(es) })
	assert.Panics(t, func() { es.MoveAndAppendTo(es2) })
	assert.Panics(t, func() { es2.MoveAndAppendTo(es) })
}

func TestCountSketchDataPointSlice_CopyTo(t *testing.T) {
	dest := NewCountSketchDataPointSlice()
	src := generateTestCountSketchDataPointSlice()
	src.CopyTo(dest)
	assert.Equal(t, generateTestCountSketchDataPointSlice(), dest)
	dest.CopyTo(dest)
	assert.Equal(t, generateTestCountSketchDataPointSlice(), dest)
}

func TestCountSketchDataPointSlice_EnsureCapacity(t *testing.T) {
	es := generateTestCountSketchDataPointSlice()

	// Test ensure smaller capacity.
	const ensureSmallLen = 4
	es.EnsureCapacity(ensureSmallLen)
	assert.Less(t, ensureSmallLen, es.Len())
	assert.Equal(t, es.Len(), cap(*es.orig))
	assert.Equal(t, generateTestCountSketchDataPointSlice(), es)

	// Test ensure larger capacity
	const ensureLargeLen = 9
	es.EnsureCapacity(ensureLargeLen)
	assert.Less(t, generateTestCountSketchDataPointSlice().Len(), ensureLargeLen)
	assert.Equal(t, ensureLargeLen, cap(*es.orig))
	assert.Equal(t, generateTestCountSketchDataPointSlice(), es)
}

func TestCountSketchDataPointSlice_MoveAndAppendTo(t *testing.T) {
	// Test MoveAndAppendTo to empty
	expectedSlice := generateTestCountSketchDataPointSlice()
	dest := NewCountSketchDataPointSlice()
	src := generateTestCountSketchDataPointSlice()
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestCountSketchDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo empty slice
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestCountSketchDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo not empty slice
	generateTestCountSketchDataPointSlice().MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}

	dest.MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}
}

func TestCountSketchDataPointSlice_RemoveIf(t *testing.T) {
	// Test RemoveIf on empty slice
	emptySlice := NewCountSketchDataPointSlice()
	emptySlice.RemoveIf(func(el CountSketchDataPoint) bool {
		t.Fail()
		return false
	})

	// Test RemoveIf
	filtered := generateTestCountSketchDataPointSlice()
	pos := 0
	filtered.RemoveIf(func(el CountSketchDataPoint) bool {
		pos++
		return pos%2 == 1
	})
	assert.Equal(t, 2, filtered.Len())
}

func TestCountSketchDataPointSlice_RemoveIfAll(t *testing.T) {
	got := generateTestCountSketchDataPointSlice()
	got.RemoveIf(func(el CountSketchDataPoint) bool {
		return true
	})
	assert.Equal(t, 0, got.Len())
}

func TestCountSketchDataPointSliceAll(t *testing.T) {
	ms := generateTestCountSketchDataPointSlice()
	assert.NotEmpty(t, ms.Len())

	var c int
	for i, v := range ms.All() {
		assert.Equal(t, ms.At(i), v, "element should match")
		c++
	}
	assert.Equal(t, ms.Len(), c, "All elements should have been visited")
}

func TestCountSketchDataPointSlice_Sort(t *testing.T) {
	es := generateTestCountSketchDataPointSlice()
	es.Sort(func(a, b CountSketchDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) < uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Less(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
	es.Sort(func(a, b CountSketchDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) > uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Greater(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
}

func generateTestCountSketchDataPointSlice() CountSketchDataPointSlice {
	ms := NewCountSketchDataPointSlice()
	*ms.orig = internal.GenTestCountSketchDataPointPtrSlice()
	return ms
}
