// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// KLLSketch represents the type of a metric encoded using the KLL quantile sketch algorithm.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewKLLSketch function to create new instances.
// Important: zero-initialized instance is not valid for use.
type KLLSketch struct {
	orig  *internal.KLLSketch
	state *internal.State
}

func newKLLSketch(orig *internal.KLLSketch, state *internal.State) KLLSketch {
	return KLLSketch{orig: orig, state: state}
}

// NewKLLSketch creates a new empty KLLSketch.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewKLLSketch() KLLSketch {
	return newKLLSketch(internal.NewKLLSketch(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms KLLSketch) MoveTo(dest KLLSketch) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteKLLSketch(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// DataPoints returns the DataPoints associated with this KLLSketch.
func (ms KLLSketch) DataPoints() KLLSketchDataPointSlice {
	return newKLLSketchDataPointSlice(&ms.orig.DataPoints, ms.state)
}

// AggregationTemporality returns the aggregationtemporality associated with this KLLSketch.
func (ms KLLSketch) AggregationTemporality() AggregationTemporality {
	return AggregationTemporality(ms.orig.AggregationTemporality)
}

// SetAggregationTemporality replaces the aggregationtemporality associated with this KLLSketch.
func (ms KLLSketch) SetAggregationTemporality(v AggregationTemporality) {
	ms.state.AssertMutable()
	ms.orig.AggregationTemporality = internal.AggregationTemporality(v)
}

// K returns the k associated with this KLLSketch.
func (ms KLLSketch) K() uint32 {
	return ms.orig.K
}

// SetK replaces the k associated with this KLLSketch.
func (ms KLLSketch) SetK(v uint32) {
	ms.state.AssertMutable()
	ms.orig.K = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms KLLSketch) CopyTo(dest KLLSketch) {
	dest.state.AssertMutable()
	internal.CopyKLLSketch(dest.orig, ms.orig)
}
