// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestKLLSketch_MoveTo(t *testing.T) {
	ms := generateTestKLLSketch()
	dest := NewKLLSketch()
	ms.MoveTo(dest)
	assert.Equal(t, NewKLLSketch(), ms)
	assert.Equal(t, generateTestKLLSketch(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestKLLSketch(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newKLLSketch(internal.NewKLLSketch(), sharedState)) })
	assert.Panics(t, func() { newKLLSketch(internal.NewKLLSketch(), sharedState).MoveTo(dest) })
}

func TestKLLSketch_CopyTo(t *testing.T) {
	ms := NewKLLSketch()
	orig := NewKLLSketch()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestKLLSketch()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newKLLSketch(internal.NewKLLSketch(), sharedState)) })
}

func TestKLLSketch_DataPoints(t *testing.T) {
	ms := NewKLLSketch()
	assert.Equal(t, NewKLLSketchDataPointSlice(), ms.DataPoints())
	ms.orig.DataPoints = internal.GenTestKLLSketchDataPointPtrSlice()
	assert.Equal(t, generateTestKLLSketchDataPointSlice(), ms.DataPoints())
}

func TestKLLSketch_AggregationTemporality(t *testing.T) {
	ms := NewKLLSketch()
	assert.Equal(t, AggregationTemporality(internal.AggregationTemporality(0)), ms.AggregationTemporality())
	testValAggregationTemporality := AggregationTemporality(internal.AggregationTemporality(1))
	ms.SetAggregationTemporality(testValAggregationTemporality)
	assert.Equal(t, testValAggregationTemporality, ms.AggregationTemporality())
}

func TestKLLSketch_K(t *testing.T) {
	ms := NewKLLSketch()
	assert.Equal(t, uint32(0), ms.K())
	ms.SetK(uint32(13))
	assert.Equal(t, uint32(13), ms.K())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newKLLSketch(internal.NewKLLSketch(), sharedState).SetK(uint32(13)) })
}

func generateTestKLLSketch() KLLSketch {
	return newKLLSketch(internal.GenTestKLLSketch(), internal.NewState())
}
