// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestHLLSketchDataPointSlice(t *testing.T) {
	es := NewHLLSketchDataPointSlice()
	assert.Equal(t, 0, es.Len())
	es = newHLLSketchDataPointSlice(&[]*internal.HLLSketchDataPoint{}, internal.NewState())
	assert.Equal(t, 0, es.Len())

	emptyVal := NewHLLSketchDataPoint()
	testVal := generateTestHLLSketchDataPoint()
	for i := 0; i < 7; i++ {
		es.AppendEmpty()
		assert.Equal(t, emptyVal, es.At(i))
		(*es.orig)[i] = internal.GenTestHLLSketchDataPoint()
		assert.Equal(t, testVal, es.At(i))
	}
	assert.Equal(t, 7, es.Len())
}

func TestHLLSketchDataPointSliceReadOnly(t *testing.T) {
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	es := newHLLSketchDataPointSlice(&[]*internal.HLLSketchDataPoint{}, sharedState)
	assert.Equal(t, 0, es.Len())
	assert.Panics(t, func() { es.AppendEmpty() })
	assert.Panics(t, func() { es.EnsureCapacity(2) })
	es2 := NewHLLSketchDataPointSlice()
	es.CopyTo(es2)
	assert.Panics(t, func() { es2.CopyTo(es) })
	assert.Panics(t, func() { es.MoveAndAppendTo(es2) })
	assert.Panics(t, func() { es2.MoveAndAppendTo(es) })
}

func TestHLLSketchDataPointSlice_CopyTo(t *testing.T) {
	dest := NewHLLSketchDataPointSlice()
	src := generateTestHLLSketchDataPointSlice()
	src.CopyTo(dest)
	assert.Equal(t, generateTestHLLSketchDataPointSlice(), dest)
	dest.CopyTo(dest)
	assert.Equal(t, generateTestHLLSketchDataPointSlice(), dest)
}

func TestHLLSketchDataPointSlice_EnsureCapacity(t *testing.T) {
	es := generateTestHLLSketchDataPointSlice()

	// Test ensure smaller capacity.
	const ensureSmallLen = 4
	es.EnsureCapacity(ensureSmallLen)
	assert.Less(t, ensureSmallLen, es.Len())
	assert.Equal(t, es.Len(), cap(*es.orig))
	assert.Equal(t, generateTestHLLSketchDataPointSlice(), es)

	// Test ensure larger capacity
	const ensureLargeLen = 9
	es.EnsureCapacity(ensureLargeLen)
	assert.Less(t, generateTestHLLSketchDataPointSlice().Len(), ensureLargeLen)
	assert.Equal(t, ensureLargeLen, cap(*es.orig))
	assert.Equal(t, generateTestHLLSketchDataPointSlice(), es)
}

func TestHLLSketchDataPointSlice_MoveAndAppendTo(t *testing.T) {
	// Test MoveAndAppendTo to empty
	expectedSlice := generateTestHLLSketchDataPointSlice()
	dest := NewHLLSketchDataPointSlice()
	src := generateTestHLLSketchDataPointSlice()
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestHLLSketchDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo empty slice
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestHLLSketchDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo not empty slice
	generateTestHLLSketchDataPointSlice().MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}

	dest.MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}
}

func TestHLLSketchDataPointSlice_RemoveIf(t *testing.T) {
	// Test RemoveIf on empty slice
	emptySlice := NewHLLSketchDataPointSlice()
	emptySlice.RemoveIf(func(el HLLSketchDataPoint) bool {
		t.Fail()
		return false
	})

	// Test RemoveIf
	filtered := generateTestHLLSketchDataPointSlice()
	pos := 0
	filtered.RemoveIf(func(el HLLSketchDataPoint) bool {
		pos++
		return pos%2 == 1
	})
	assert.Equal(t, 2, filtered.Len())
}

func TestHLLSketchDataPointSlice_RemoveIfAll(t *testing.T) {
	got := generateTestHLLSketchDataPointSlice()
	got.RemoveIf(func(el HLLSketchDataPoint) bool {
		return true
	})
	assert.Equal(t, 0, got.Len())
}

func TestHLLSketchDataPointSliceAll(t *testing.T) {
	ms := generateTestHLLSketchDataPointSlice()
	assert.NotEmpty(t, ms.Len())

	var c int
	for i, v := range ms.All() {
		assert.Equal(t, ms.At(i), v, "element should match")
		c++
	}
	assert.Equal(t, ms.Len(), c, "All elements should have been visited")
}

func TestHLLSketchDataPointSlice_Sort(t *testing.T) {
	es := generateTestHLLSketchDataPointSlice()
	es.Sort(func(a, b HLLSketchDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) < uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Less(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
	es.Sort(func(a, b HLLSketchDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) > uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Greater(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
}

func generateTestHLLSketchDataPointSlice() HLLSketchDataPointSlice {
	ms := NewHLLSketchDataPointSlice()
	*ms.orig = internal.GenTestHLLSketchDataPointPtrSlice()
	return ms
}
