// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"iter"
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
)

// CountMinSketchDataPointSlice logically represents a slice of CountMinSketchDataPoint.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewCountMinSketchDataPointSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type CountMinSketchDataPointSlice struct {
	orig  *[]*internal.CountMinSketchDataPoint
	state *internal.State
}

func newCountMinSketchDataPointSlice(orig *[]*internal.CountMinSketchDataPoint, state *internal.State) CountMinSketchDataPointSlice {
	return CountMinSketchDataPointSlice{orig: orig, state: state}
}

// NewCountMinSketchDataPointSlice creates a CountMinSketchDataPointSliceWrapper with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewCountMinSketchDataPointSlice() CountMinSketchDataPointSlice {
	orig := []*internal.CountMinSketchDataPoint(nil)
	return newCountMinSketchDataPointSlice(&orig, internal.NewState())
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewCountMinSketchDataPointSlice()".
func (es CountMinSketchDataPointSlice) Len() int {
	return len(*es.orig)
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//
//	for i := 0; i < es.Len(); i++ {
//	    e := es.At(i)
//	    ... // Do something with the element
//	}
func (es CountMinSketchDataPointSlice) At(i int) CountMinSketchDataPoint {
	return newCountMinSketchDataPoint((*es.orig)[i], es.state)
}

// All returns an iterator over index-value pairs in the slice.
//
//	for i, v := range es.All() {
//	    ... // Do something with index-value pair
//	}
func (es CountMinSketchDataPointSlice) All() iter.Seq2[int, CountMinSketchDataPoint] {
	return func(yield func(int, CountMinSketchDataPoint) bool) {
		for i := 0; i < es.Len(); i++ {
			if !yield(i, es.At(i)) {
				return
			}
		}
	}
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new CountMinSketchDataPointSlice can be initialized:
//
//	es := NewCountMinSketchDataPointSlice()
//	es.EnsureCapacity(4)
//	for i := 0; i < 4; i++ {
//	    e := es.AppendEmpty()
//	    // Here should set all the values for e.
//	}
func (es CountMinSketchDataPointSlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(*es.orig)
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*internal.CountMinSketchDataPoint, len(*es.orig), newCap)
	copy(newOrig, *es.orig)
	*es.orig = newOrig
}

// AppendEmpty will append to the end of the slice an empty CountMinSketchDataPoint.
// It returns the newly added CountMinSketchDataPoint.
func (es CountMinSketchDataPointSlice) AppendEmpty() CountMinSketchDataPoint {
	es.state.AssertMutable()
	*es.orig = append(*es.orig, internal.NewCountMinSketchDataPoint())
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es CountMinSketchDataPointSlice) MoveAndAppendTo(dest CountMinSketchDataPointSlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if es.orig == dest.orig {
		return
	}
	if *dest.orig == nil {
		// We can simply move the entire vector and avoid any allocations.
		*dest.orig = *es.orig
	} else {
		*dest.orig = append(*dest.orig, *es.orig...)
	}
	*es.orig = nil
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es CountMinSketchDataPointSlice) RemoveIf(f func(CountMinSketchDataPoint) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(*es.orig); i++ {
		if f(es.At(i)) {
			internal.DeleteCountMinSketchDataPoint((*es.orig)[i], true)
			(*es.orig)[i] = nil

			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		(*es.orig)[newLen] = (*es.orig)[i]
		// Cannot delete here since we just move the data(or pointer to data) to a different position in the slice.
		(*es.orig)[i] = nil
		newLen++
	}
	*es.orig = (*es.orig)[:newLen]
}

// CopyTo copies all elements from the current slice overriding the destination.
func (es CountMinSketchDataPointSlice) CopyTo(dest CountMinSketchDataPointSlice) {
	dest.state.AssertMutable()
	if es.orig == dest.orig {
		return
	}
	*dest.orig = internal.CopyCountMinSketchDataPointPtrSlice(*dest.orig, *es.orig)
}

// Sort sorts the CountMinSketchDataPoint elements within CountMinSketchDataPointSlice given the
// provided less function so that two instances of CountMinSketchDataPointSlice
// can be compared.
func (es CountMinSketchDataPointSlice) Sort(less func(a, b CountMinSketchDataPoint) bool) {
	es.state.AssertMutable()
	sort.SliceStable(*es.orig, func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
