// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestSumAggDataPointSlice(t *testing.T) {
	es := NewSumAggDataPointSlice()
	assert.Equal(t, 0, es.Len())
	es = newSumAggDataPointSlice(&[]*internal.SumAggDataPoint{}, internal.NewState())
	assert.Equal(t, 0, es.Len())

	emptyVal := NewSumAggDataPoint()
	testVal := generateTestSumAggDataPoint()
	for i := 0; i < 7; i++ {
		es.AppendEmpty()
		assert.Equal(t, emptyVal, es.At(i))
		(*es.orig)[i] = internal.GenTestSumAggDataPoint()
		assert.Equal(t, testVal, es.At(i))
	}
	assert.Equal(t, 7, es.Len())
}

func TestSumAggDataPointSliceReadOnly(t *testing.T) {
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	es := newSumAggDataPointSlice(&[]*internal.SumAggDataPoint{}, sharedState)
	assert.Equal(t, 0, es.Len())
	assert.Panics(t, func() { es.AppendEmpty() })
	assert.Panics(t, func() { es.EnsureCapacity(2) })
	es2 := NewSumAggDataPointSlice()
	es.CopyTo(es2)
	assert.Panics(t, func() { es2.CopyTo(es) })
	assert.Panics(t, func() { es.MoveAndAppendTo(es2) })
	assert.Panics(t, func() { es2.MoveAndAppendTo(es) })
}

func TestSumAggDataPointSlice_CopyTo(t *testing.T) {
	dest := NewSumAggDataPointSlice()
	src := generateTestSumAggDataPointSlice()
	src.CopyTo(dest)
	assert.Equal(t, generateTestSumAggDataPointSlice(), dest)
	dest.CopyTo(dest)
	assert.Equal(t, generateTestSumAggDataPointSlice(), dest)
}

func TestSumAggDataPointSlice_EnsureCapacity(t *testing.T) {
	es := generateTestSumAggDataPointSlice()

	// Test ensure smaller capacity.
	const ensureSmallLen = 4
	es.EnsureCapacity(ensureSmallLen)
	assert.Less(t, ensureSmallLen, es.Len())
	assert.Equal(t, es.Len(), cap(*es.orig))
	assert.Equal(t, generateTestSumAggDataPointSlice(), es)

	// Test ensure larger capacity
	const ensureLargeLen = 9
	es.EnsureCapacity(ensureLargeLen)
	assert.Less(t, generateTestSumAggDataPointSlice().Len(), ensureLargeLen)
	assert.Equal(t, ensureLargeLen, cap(*es.orig))
	assert.Equal(t, generateTestSumAggDataPointSlice(), es)
}

func TestSumAggDataPointSlice_MoveAndAppendTo(t *testing.T) {
	// Test MoveAndAppendTo to empty
	expectedSlice := generateTestSumAggDataPointSlice()
	dest := NewSumAggDataPointSlice()
	src := generateTestSumAggDataPointSlice()
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestSumAggDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo empty slice
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestSumAggDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo not empty slice
	generateTestSumAggDataPointSlice().MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}

	dest.MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}
}

func TestSumAggDataPointSlice_RemoveIf(t *testing.T) {
	// Test RemoveIf on empty slice
	emptySlice := NewSumAggDataPointSlice()
	emptySlice.RemoveIf(func(el SumAggDataPoint) bool {
		t.Fail()
		return false
	})

	// Test RemoveIf
	filtered := generateTestSumAggDataPointSlice()
	pos := 0
	filtered.RemoveIf(func(el SumAggDataPoint) bool {
		pos++
		return pos%2 == 1
	})
	assert.Equal(t, 2, filtered.Len())
}

func TestSumAggDataPointSlice_RemoveIfAll(t *testing.T) {
	got := generateTestSumAggDataPointSlice()
	got.RemoveIf(func(el SumAggDataPoint) bool {
		return true
	})
	assert.Equal(t, 0, got.Len())
}

func TestSumAggDataPointSliceAll(t *testing.T) {
	ms := generateTestSumAggDataPointSlice()
	assert.NotEmpty(t, ms.Len())

	var c int
	for i, v := range ms.All() {
		assert.Equal(t, ms.At(i), v, "element should match")
		c++
	}
	assert.Equal(t, ms.Len(), c, "All elements should have been visited")
}

func TestSumAggDataPointSlice_Sort(t *testing.T) {
	es := generateTestSumAggDataPointSlice()
	es.Sort(func(a, b SumAggDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) < uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Less(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
	es.Sort(func(a, b SumAggDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) > uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Greater(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
}

func generateTestSumAggDataPointSlice() SumAggDataPointSlice {
	ms := NewSumAggDataPointSlice()
	*ms.orig = internal.GenTestSumAggDataPointPtrSlice()
	return ms
}
