// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestHLLSketchDataPoint_MoveTo(t *testing.T) {
	ms := generateTestHLLSketchDataPoint()
	dest := NewHLLSketchDataPoint()
	ms.MoveTo(dest)
	assert.Equal(t, NewHLLSketchDataPoint(), ms)
	assert.Equal(t, generateTestHLLSketchDataPoint(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestHLLSketchDataPoint(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newHLLSketchDataPoint(internal.NewHLLSketchDataPoint(), sharedState)) })
	assert.Panics(t, func() { newHLLSketchDataPoint(internal.NewHLLSketchDataPoint(), sharedState).MoveTo(dest) })
}

func TestHLLSketchDataPoint_CopyTo(t *testing.T) {
	ms := NewHLLSketchDataPoint()
	orig := NewHLLSketchDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestHLLSketchDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newHLLSketchDataPoint(internal.NewHLLSketchDataPoint(), sharedState)) })
}

func TestHLLSketchDataPoint_Attributes(t *testing.T) {
	ms := NewHLLSketchDataPoint()
	assert.Equal(t, pcommon.NewMap(), ms.Attributes())
	ms.orig.Attributes = internal.GenTestKeyValueSlice()
	assert.Equal(t, pcommon.Map(internal.GenTestMapWrapper()), ms.Attributes())
}

func TestHLLSketchDataPoint_StartTimestamp(t *testing.T) {
	ms := NewHLLSketchDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.StartTimestamp())
	testValStartTimestamp := pcommon.Timestamp(1234567890)
	ms.SetStartTimestamp(testValStartTimestamp)
	assert.Equal(t, testValStartTimestamp, ms.StartTimestamp())
}

func TestHLLSketchDataPoint_Timestamp(t *testing.T) {
	ms := NewHLLSketchDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.Timestamp())
	testValTimestamp := pcommon.Timestamp(1234567890)
	ms.SetTimestamp(testValTimestamp)
	assert.Equal(t, testValTimestamp, ms.Timestamp())
}

func TestHLLSketchDataPoint_Sketch(t *testing.T) {
	ms := NewHLLSketchDataPoint()
	assert.Equal(t, nil, ms.Sketch())
	ms.SetSketch([]byte{1, 2, 3})
	assert.Equal(t, []byte{1, 2, 3}, ms.Sketch())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newHLLSketchDataPoint(internal.NewHLLSketchDataPoint(), sharedState).SetSketch([]byte{1, 2, 3})
	})
}

func TestHLLSketchDataPoint_Encoding(t *testing.T) {
	ms := NewHLLSketchDataPoint()
	assert.Equal(t, HLLSketchEncoding(internal.HLLSketchEncoding(0)), ms.Encoding())
	testValEncoding := HLLSketchEncoding(internal.HLLSketchEncoding(1))
	ms.SetEncoding(testValEncoding)
	assert.Equal(t, testValEncoding, ms.Encoding())
}

func TestHLLSketchDataPoint_Flags(t *testing.T) {
	ms := NewHLLSketchDataPoint()
	assert.Equal(t, DataPointFlags(0), ms.Flags())
	testValFlags := DataPointFlags(1)
	ms.SetFlags(testValFlags)
	assert.Equal(t, testValFlags, ms.Flags())
}

func TestHLLSketchDataPoint_SeriesID(t *testing.T) {
	ms := NewHLLSketchDataPoint()
	assert.Equal(t, uint64(0), ms.SeriesID())
	ms.SetSeriesID(uint64(13))
	assert.Equal(t, uint64(13), ms.SeriesID())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newHLLSketchDataPoint(internal.NewHLLSketchDataPoint(), sharedState).SetSeriesID(uint64(13)) })
}

func generateTestHLLSketchDataPoint() HLLSketchDataPoint {
	return newHLLSketchDataPoint(internal.GenTestHLLSketchDataPoint(), internal.NewState())
}
