// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"go.opentelemetry.io/collector/pdata/internal"
)

// CountSketch represents the type of a metric encoded using the CountSketch frequency estimation algorithm.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewCountSketch function to create new instances.
// Important: zero-initialized instance is not valid for use.
type CountSketch struct {
	orig  *internal.CountSketch
	state *internal.State
}

func newCountSketch(orig *internal.CountSketch, state *internal.State) CountSketch {
	return CountSketch{orig: orig, state: state}
}

// NewCountSketch creates a new empty CountSketch.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewCountSketch() CountSketch {
	return newCountSketch(internal.NewCountSketch(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms CountSketch) MoveTo(dest CountSketch) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteCountSketch(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// DataPoints returns the DataPoints associated with this CountSketch.
func (ms CountSketch) DataPoints() CountSketchDataPointSlice {
	return newCountSketchDataPointSlice(&ms.orig.DataPoints, ms.state)
}

// AggregationTemporality returns the aggregationtemporality associated with this CountSketch.
func (ms CountSketch) AggregationTemporality() AggregationTemporality {
	return AggregationTemporality(ms.orig.AggregationTemporality)
}

// SetAggregationTemporality replaces the aggregationtemporality associated with this CountSketch.
func (ms CountSketch) SetAggregationTemporality(v AggregationTemporality) {
	ms.state.AssertMutable()
	ms.orig.AggregationTemporality = internal.AggregationTemporality(v)
}

// Rows returns the rows associated with this CountSketch.
func (ms CountSketch) Rows() int32 {
	return ms.orig.Rows
}

// SetRows replaces the rows associated with this CountSketch.
func (ms CountSketch) SetRows(v int32) {
	ms.state.AssertMutable()
	ms.orig.Rows = v
}

// Cols returns the cols associated with this CountSketch.
func (ms CountSketch) Cols() int32 {
	return ms.orig.Cols
}

// SetCols replaces the cols associated with this CountSketch.
func (ms CountSketch) SetCols(v int32) {
	ms.state.AssertMutable()
	ms.orig.Cols = v
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms CountSketch) CopyTo(dest CountSketch) {
	dest.state.AssertMutable()
	internal.CopyCountSketch(dest.orig, ms.orig)
}
