// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestCountMinSketchDataPointSlice(t *testing.T) {
	es := NewCountMinSketchDataPointSlice()
	assert.Equal(t, 0, es.Len())
	es = newCountMinSketchDataPointSlice(&[]*internal.CountMinSketchDataPoint{}, internal.NewState())
	assert.Equal(t, 0, es.Len())

	emptyVal := NewCountMinSketchDataPoint()
	testVal := generateTestCountMinSketchDataPoint()
	for i := 0; i < 7; i++ {
		es.AppendEmpty()
		assert.Equal(t, emptyVal, es.At(i))
		(*es.orig)[i] = internal.GenTestCountMinSketchDataPoint()
		assert.Equal(t, testVal, es.At(i))
	}
	assert.Equal(t, 7, es.Len())
}

func TestCountMinSketchDataPointSliceReadOnly(t *testing.T) {
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	es := newCountMinSketchDataPointSlice(&[]*internal.CountMinSketchDataPoint{}, sharedState)
	assert.Equal(t, 0, es.Len())
	assert.Panics(t, func() { es.AppendEmpty() })
	assert.Panics(t, func() { es.EnsureCapacity(2) })
	es2 := NewCountMinSketchDataPointSlice()
	es.CopyTo(es2)
	assert.Panics(t, func() { es2.CopyTo(es) })
	assert.Panics(t, func() { es.MoveAndAppendTo(es2) })
	assert.Panics(t, func() { es2.MoveAndAppendTo(es) })
}

func TestCountMinSketchDataPointSlice_CopyTo(t *testing.T) {
	dest := NewCountMinSketchDataPointSlice()
	src := generateTestCountMinSketchDataPointSlice()
	src.CopyTo(dest)
	assert.Equal(t, generateTestCountMinSketchDataPointSlice(), dest)
	dest.CopyTo(dest)
	assert.Equal(t, generateTestCountMinSketchDataPointSlice(), dest)
}

func TestCountMinSketchDataPointSlice_EnsureCapacity(t *testing.T) {
	es := generateTestCountMinSketchDataPointSlice()

	// Test ensure smaller capacity.
	const ensureSmallLen = 4
	es.EnsureCapacity(ensureSmallLen)
	assert.Less(t, ensureSmallLen, es.Len())
	assert.Equal(t, es.Len(), cap(*es.orig))
	assert.Equal(t, generateTestCountMinSketchDataPointSlice(), es)

	// Test ensure larger capacity
	const ensureLargeLen = 9
	es.EnsureCapacity(ensureLargeLen)
	assert.Less(t, generateTestCountMinSketchDataPointSlice().Len(), ensureLargeLen)
	assert.Equal(t, ensureLargeLen, cap(*es.orig))
	assert.Equal(t, generateTestCountMinSketchDataPointSlice(), es)
}

func TestCountMinSketchDataPointSlice_MoveAndAppendTo(t *testing.T) {
	// Test MoveAndAppendTo to empty
	expectedSlice := generateTestCountMinSketchDataPointSlice()
	dest := NewCountMinSketchDataPointSlice()
	src := generateTestCountMinSketchDataPointSlice()
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestCountMinSketchDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo empty slice
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestCountMinSketchDataPointSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo not empty slice
	generateTestCountMinSketchDataPointSlice().MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}

	dest.MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}
}

func TestCountMinSketchDataPointSlice_RemoveIf(t *testing.T) {
	// Test RemoveIf on empty slice
	emptySlice := NewCountMinSketchDataPointSlice()
	emptySlice.RemoveIf(func(el CountMinSketchDataPoint) bool {
		t.Fail()
		return false
	})

	// Test RemoveIf
	filtered := generateTestCountMinSketchDataPointSlice()
	pos := 0
	filtered.RemoveIf(func(el CountMinSketchDataPoint) bool {
		pos++
		return pos%2 == 1
	})
	assert.Equal(t, 2, filtered.Len())
}

func TestCountMinSketchDataPointSlice_RemoveIfAll(t *testing.T) {
	got := generateTestCountMinSketchDataPointSlice()
	got.RemoveIf(func(el CountMinSketchDataPoint) bool {
		return true
	})
	assert.Equal(t, 0, got.Len())
}

func TestCountMinSketchDataPointSliceAll(t *testing.T) {
	ms := generateTestCountMinSketchDataPointSlice()
	assert.NotEmpty(t, ms.Len())

	var c int
	for i, v := range ms.All() {
		assert.Equal(t, ms.At(i), v, "element should match")
		c++
	}
	assert.Equal(t, ms.Len(), c, "All elements should have been visited")
}

func TestCountMinSketchDataPointSlice_Sort(t *testing.T) {
	es := generateTestCountMinSketchDataPointSlice()
	es.Sort(func(a, b CountMinSketchDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) < uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Less(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
	es.Sort(func(a, b CountMinSketchDataPoint) bool {
		return uintptr(unsafe.Pointer(a.orig)) > uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.Greater(t, uintptr(unsafe.Pointer(es.At(i-1).orig)), uintptr(unsafe.Pointer(es.At(i).orig)))
	}
}

func generateTestCountMinSketchDataPointSlice() CountMinSketchDataPointSlice {
	ms := NewCountMinSketchDataPointSlice()
	*ms.orig = internal.GenTestCountMinSketchDataPointPtrSlice()
	return ms
}
