// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestKLLSketchDataPoint_MoveTo(t *testing.T) {
	ms := generateTestKLLSketchDataPoint()
	dest := NewKLLSketchDataPoint()
	ms.MoveTo(dest)
	assert.Equal(t, NewKLLSketchDataPoint(), ms)
	assert.Equal(t, generateTestKLLSketchDataPoint(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestKLLSketchDataPoint(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newKLLSketchDataPoint(internal.NewKLLSketchDataPoint(), sharedState)) })
	assert.Panics(t, func() { newKLLSketchDataPoint(internal.NewKLLSketchDataPoint(), sharedState).MoveTo(dest) })
}

func TestKLLSketchDataPoint_CopyTo(t *testing.T) {
	ms := NewKLLSketchDataPoint()
	orig := NewKLLSketchDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestKLLSketchDataPoint()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newKLLSketchDataPoint(internal.NewKLLSketchDataPoint(), sharedState)) })
}

func TestKLLSketchDataPoint_Attributes(t *testing.T) {
	ms := NewKLLSketchDataPoint()
	assert.Equal(t, pcommon.NewMap(), ms.Attributes())
	ms.orig.Attributes = internal.GenTestKeyValueSlice()
	assert.Equal(t, pcommon.Map(internal.GenTestMapWrapper()), ms.Attributes())
}

func TestKLLSketchDataPoint_StartTimestamp(t *testing.T) {
	ms := NewKLLSketchDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.StartTimestamp())
	testValStartTimestamp := pcommon.Timestamp(1234567890)
	ms.SetStartTimestamp(testValStartTimestamp)
	assert.Equal(t, testValStartTimestamp, ms.StartTimestamp())
}

func TestKLLSketchDataPoint_Timestamp(t *testing.T) {
	ms := NewKLLSketchDataPoint()
	assert.Equal(t, pcommon.Timestamp(0), ms.Timestamp())
	testValTimestamp := pcommon.Timestamp(1234567890)
	ms.SetTimestamp(testValTimestamp)
	assert.Equal(t, testValTimestamp, ms.Timestamp())
}

func TestKLLSketchDataPoint_Sketch(t *testing.T) {
	ms := NewKLLSketchDataPoint()
	assert.Equal(t, nil, ms.Sketch())
	ms.SetSketch([]byte{1, 2, 3})
	assert.Equal(t, []byte{1, 2, 3}, ms.Sketch())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newKLLSketchDataPoint(internal.NewKLLSketchDataPoint(), sharedState).SetSketch([]byte{1, 2, 3})
	})
}

func TestKLLSketchDataPoint_Encoding(t *testing.T) {
	ms := NewKLLSketchDataPoint()
	assert.Equal(t, KLLSketchEncoding(internal.KLLSketchEncoding(0)), ms.Encoding())
	testValEncoding := KLLSketchEncoding(internal.KLLSketchEncoding(1))
	ms.SetEncoding(testValEncoding)
	assert.Equal(t, testValEncoding, ms.Encoding())
}

func TestKLLSketchDataPoint_Flags(t *testing.T) {
	ms := NewKLLSketchDataPoint()
	assert.Equal(t, DataPointFlags(0), ms.Flags())
	testValFlags := DataPointFlags(1)
	ms.SetFlags(testValFlags)
	assert.Equal(t, testValFlags, ms.Flags())
}

func TestKLLSketchDataPoint_SeriesID(t *testing.T) {
	ms := NewKLLSketchDataPoint()
	assert.Equal(t, uint64(0), ms.SeriesID())
	ms.SetSeriesID(uint64(13))
	assert.Equal(t, uint64(13), ms.SeriesID())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newKLLSketchDataPoint(internal.NewKLLSketchDataPoint(), sharedState).SetSeriesID(uint64(13)) })
}

func generateTestKLLSketchDataPoint() KLLSketchDataPoint {
	return newKLLSketchDataPoint(internal.GenTestKLLSketchDataPoint(), internal.NewState())
}
