// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetricotlp

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestSeriesAssignment_MoveTo(t *testing.T) {
	ms := generateTestSeriesAssignment()
	dest := NewSeriesAssignment()
	ms.MoveTo(dest)
	assert.Equal(t, NewSeriesAssignment(), ms)
	assert.Equal(t, generateTestSeriesAssignment(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestSeriesAssignment(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newSeriesAssignment(internal.NewSeriesAssignment(), sharedState)) })
	assert.Panics(t, func() { newSeriesAssignment(internal.NewSeriesAssignment(), sharedState).MoveTo(dest) })
}

func TestSeriesAssignment_CopyTo(t *testing.T) {
	ms := NewSeriesAssignment()
	orig := NewSeriesAssignment()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestSeriesAssignment()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newSeriesAssignment(internal.NewSeriesAssignment(), sharedState)) })
}

func TestSeriesAssignment_ResourceKey(t *testing.T) {
	ms := NewSeriesAssignment()
	assert.Empty(t, ms.ResourceKey())
	ms.SetResourceKey("test_resourcekey")
	assert.Equal(t, "test_resourcekey", ms.ResourceKey())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newSeriesAssignment(internal.NewSeriesAssignment(), sharedState).SetResourceKey("test_resourcekey")
	})
}

func TestSeriesAssignment_ScopeKey(t *testing.T) {
	ms := NewSeriesAssignment()
	assert.Empty(t, ms.ScopeKey())
	ms.SetScopeKey("test_scopekey")
	assert.Equal(t, "test_scopekey", ms.ScopeKey())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newSeriesAssignment(internal.NewSeriesAssignment(), sharedState).SetScopeKey("test_scopekey") })
}

func TestSeriesAssignment_MetricName(t *testing.T) {
	ms := NewSeriesAssignment()
	assert.Empty(t, ms.MetricName())
	ms.SetMetricName("test_metricname")
	assert.Equal(t, "test_metricname", ms.MetricName())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newSeriesAssignment(internal.NewSeriesAssignment(), sharedState).SetMetricName("test_metricname")
	})
}

func TestSeriesAssignment_MetricType(t *testing.T) {
	ms := NewSeriesAssignment()
	assert.Empty(t, ms.MetricType())
	ms.SetMetricType("test_metrictype")
	assert.Equal(t, "test_metrictype", ms.MetricType())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newSeriesAssignment(internal.NewSeriesAssignment(), sharedState).SetMetricType("test_metrictype")
	})
}

func TestSeriesAssignment_AttributesFingerprint(t *testing.T) {
	ms := NewSeriesAssignment()
	assert.Equal(t, nil, ms.AttributesFingerprint())
	ms.SetAttributesFingerprint([]byte{1, 2, 3})
	assert.Equal(t, []byte{1, 2, 3}, ms.AttributesFingerprint())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newSeriesAssignment(internal.NewSeriesAssignment(), sharedState).SetAttributesFingerprint([]byte{1, 2, 3})
	})
}

func TestSeriesAssignment_SeriesID(t *testing.T) {
	ms := NewSeriesAssignment()
	assert.Equal(t, uint64(0), ms.SeriesID())
	ms.SetSeriesID(uint64(13))
	assert.Equal(t, uint64(13), ms.SeriesID())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { newSeriesAssignment(internal.NewSeriesAssignment(), sharedState).SetSeriesID(uint64(13)) })
}

func generateTestSeriesAssignment() SeriesAssignment {
	return newSeriesAssignment(internal.GenTestSeriesAssignment(), internal.NewState())
}
