# Read data directly from FakePrometheusExporter
# based off max-throughput-prometheus-client.conf

[global_tags]
  scenario = "prometheus_inp"

[agent]
  interval = "1ms"
  flush_interval = "1ms"
  flush_jitter = "0s"
  collection_jitter = "0s"
  round_interval = false
  metric_batch_size = 10000
  metric_buffer_limit = 500000
  precision = "1ms"
  debug = true
  logfile = "/tmp/telegraf-prometheus-inp.log"

[[inputs.prometheus]]
  urls = [
    "http://localhost:8000/metrics",
    "http://localhost:8001/metrics",
  ]
  metric_version = 2
  url_tag = "scrape_url"
  name_prefix = "gorilla_local_"
  timeout = "5s"
  interval = "250ms"
  metric_batch_size = 10000
  metric_buffer_limit = 250000

[[inputs.internal]]
  per_instance = true
  collect_gostats = true

[[outputs.file]]
  files = ["../benchmarks/results/prometheus-inp.lp"]
  data_format = "influx"
  use_batch_format = false
  rotation_interval = "1m"
  rotation_max_size = "50MB"
  rotation_max_archives = 15
  namepass = ["internal_*"]

[[outputs.prometheus_client]]
  listen = ":9203"
  path = "/metrics"
  metric_version = 2
  export_timestamp = true
  expiration_interval = "30s"
