# OTLP Sketch Payload Flow - Batch mode - Local testing
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:53217
      http:
        endpoint: 0.0.0.0:53218

processors:
  countmin:
    mode: batch
    metric_name: "cms_sketch"
    rows: 5
    columns: 2000
    transmit_sketch: true
    group_by: []
    drop_original: true

exporters:
  otlphttp:
    endpoint: http://localhost:4318
    encoding: proto
    compression: gzip
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [countmin]
      exporters: [otlphttp]
  telemetry:
    logs:
      level: debug
    resource:
      service.name: countminsketchcol-sketch-payload-flow-batch-local
