# OTLP Pathway 2 - Window mode - Local testing 
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:53217
      http:
        endpoint: 0.0.0.0:53218

processors:
  countmin:
    mode: window
    metric_name: "cms_sketch"
    rows: 5
    columns: 2000
    transmit_sketch: true
    group_by: []
    drop_original: true
    window_interval: 60s

exporters:
  otlphttp:
    endpoint: http://localhost:4318
    encoding: proto
    compression: gzip
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [countmin]
      exporters: [otlphttp]
  telemetry:
    metrics:
      level: basic
    logs:
      level: debug
    resource:
      service.name: countminsketchcol-otlp-pathway2-local
