#!/usr/bin/env bash
# Regenerate agents-N<K>.yml for an arbitrary N. The compose
# files are deliberately flat (no `deploy: replicas:`) so each
# agent has a distinct AGENT_ID label — see base.yml comment.
#
# Usage: ./gen-agents.sh 100 > agents-N100.yml
set -euo pipefail
N="${1:-10}"
cat <<EOF
# Overlay: $N edge agents. Auto-generated by
# \`./gen-agents.sh $N > agents-N$N.yml\`. Do not edit by hand;
# edit \`gen-agents.sh\` if the per-agent template changes.

version: "3.9"

x-agent: &agent-base
  image: asap/sketchcol:dev
  depends_on:
    - gateway
    - controller
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: 512M

services:
EOF
for ((i=1; i<=N; i++)); do
  cat <<EOF
  agent-$i:
    <<: *agent-base
    hostname: agent-$i
    environment:
      AGENT_ID: "agent-$i"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://gateway:4317"
      CONTROLLER_OPAMP_URL: "ws://controller:4320/v1/opamp"
      SKETCH_RUNTIME_GRPC_ENDPOINT: "http://controller:4321"
      RUST_LOG: "info"
EOF
done
